### ISSUE TITLE
Thread panic while running jest tests in strapi project

### ISSUE THREAD

**Issue by Brooooooklyn** [swc-project/swc#1038]
strapi with latest `@swc-node/jest`: https://github.com/Brooooooklyn/strapi/pull/1

the `@swc-node/core@0.7.1` was built from `swc#57112fc4`.

The weird thing is I can run `yarn build && yarn test:front` on my `macOS` machine.
But while running tests in `Travis CI/node-10-slim Docker container`,  thread panic happened.

### Step to reproduce:

- Linux operation system
- clone `https://github.com/Brooooooklyn/strapi/tree/swc`
- checkout to `swc` branch
- yarn
- yarn build
- yarn test:front

### File to trigger the panic

`packages/strapi-helper-plugin/dist/strapi-helper-plugin.cjs.min.js`

### Rust backtrace:

```
/home/runner/.cargo/git/checkouts/swc-594f88c93b4170b2/57112fc/ecmascript/transforms/src/hygiene.rs:135:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: swc_ecma_transforms::hygiene::Hygiene::rename
  14: swc_ecma_transforms::hygiene::Hygiene::add_declared_ref
  15: swc_ecma_transforms::hygiene::Hygiene::visit_mut_fn
  16: <swc_ecma_ast::expr::Expr as swc_ecma_visit::VisitMutWith<V>>::visit_mut_children_with
  17: swc_ecma_visit::visit_mut_stmt
  18: <swc_ecma_transforms::hygiene::Hygiene as swc_ecma_visit::VisitMut>::visit_mut_module
  19: swc_ecma_visit::fold_program
  20: scoped_tls::ScopedKey<T>::set
  21: node_swc::jest_transform
  22: _ZN12_GLOBAL__N_16v8impl23FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  23: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  24: _ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE
```

### Error:

```
thread '<unnamed>' panicked at '{"defineProperty": [#196], "_arrayWithoutHoles": [#196], "_templateObject$F": [#196], "_templateObject$J": [#196], "ConcurrentMode": [#196], "parse$1": [#196], "ListWrapper": [#196], "reactIntl": [#196], "_ref": [#196], "LiLink": [#196], "vn": [#196], "_byLigature": [#196], "makeIconStandard": [#196], "_templateObject$A": [#196], "nextUniqueId": [#196], "getOwnPropertySymbols": [#196], "GlobalContext": [#196], "Wrapper$1": [#196], "StyledLabel": [#196], "coerce": [#196], "ContextProvider": [#196], "InputEmail": [#196], "Dropdown": [#196], "GlobalContextProvider": [#196], "_templateObject$U": [#196], "NotFound": [#196], "SizedInput": [#196], "l$1": [#196], "isAsyncMode": [#196], "DEFAULT_REPLACEMENT_CLASS": [#196], "Wrapper$6": [#196], "apiObject": [#196], "_default": [#196], "custom": [#196], "dateToUtcTime": [#196], "U": [#196], "isCaseAcronym": [#196], "LayoutHover": [#196], "_templateObject$C": [#196], "ReactPropTypesSecret_1": [#196], "styles$1": [#196], "_templateObject$b": [#196], "Clear$1": [#196], "InputToggleWithErrors": [#196], "P": [#196], "getCaseRanking": [#196], "isElement": [#196], "_templateObject$N": [#196], "Wrapper$4": [#196], "LeftMenuSubList": [#196], "PopUpWarning": [#196], "reactIs_production_min": [#196], "colors$1": [#196], "_templateObject$m": [#196], "allAccents": [#196], "NAMESPACE_IDENTIFIER": [#196], "_isNumerical": [#196], "classList": [#196], "errorsTrads": [#196], "RemoveButton": [#196], "Wrapper$9": [#196], "injectHooks": [#196], "StyledPluginHeaderActions": [#196], "InputNumber": [#196], "_templateObject$h": [#196], "StyledButtonSecondary": [#196], "idPool": [#196], "reactIs_development_25": [#196], "R": [#196], "StrapiProvider": [#196], "cleanData": [#196], "SelectOption": [#196], "KNOWN_STATICS": [#196], "OPACITY_ANIMATE": [#196], "DOT": [#196], "IS_BROWSER": [#196], "_templateObject$o": [#196], "has$1": [#196], "M": [#196], "InputSelect": [#196], "_cssInserted": [#196], "firstAccent": [#196], "Fragment": [#196], "LoadingIndicator": [#196], "makeIconMasking": [#196], "_defineProperty$2": [#196], "_objectWithoutPropertiesLoose$1": [#196], "_templateObject$f": [#196], "_templateObject$j": [#196], "noop$1": [#196], "reactIs_development_27": [#196], "H": [#196], "_ref$userAgent": [#196], "checkStatus": [#196], "_extends": [#196], "_templateObject2$2": [#196], "_templateObject$a": [#196], "hasAccents": [#196], "listener": [#196], "noop": [#196], "reactIs_development_22": [#196], "Select": [#196], "InputDescription": [#196], "asyncGeneratorStep": [#196], "inputs": [#196], "cn": [#196], "makeInlineSvgAbstract": [#196], "_PERFORMANCE": [#196], "_templateObject$1c": [#196], "emptyFunctionWithReset": [#196], "reactHelmet": [#196], "_templateObject$13": [#196], "rankings": [#196], "formatPermissionsForRequest": [#196], "TYPE_STATICS": [#196], "_templateObject5": [#196], "Manager": [#196], "_templateObject$Y": [#196], "core": [#196], "u": [#196], "reactIs_development_18": [#196], "StyledModal": [#196], "ExtendComponent": [#196], "Memo": [#196], "Button": [#196], "Q": [#196], "propTypes": [#196], "themeShape": [#196], "transformIsMeaningful": [#196], "_WINDOW": [#196], "index": [#196], "p": [#196], "loading": [#196], "_templateObject$$": [#196], "_templateObject$n": [#196], "HeaderModalTitle": [#196], "namespace": [#196], "iconFromMapping": [#196], "List$1": [#196], "InputWrapper": [#196], "ListButton": [#196], "parseJSON": [#196], "IcoNotFound": [#196], "p$2": [#196], "Close": [#196], "_templateObject": [#196], "reactIs_development_26": [#196], "getAllValuesToRank": [#196], "r$1": [#196], "fn": [#196], "sortRankedItems": [#196], "secondaryHotline": [#196], "StyledLink": [#196], "StyledPluginHeaderTitle": [#196], "invariant": [#196], "r": [#196, #196], "styleToObject": [#196], "spin$1": [#196], "formatQueryParams": [#196], "reactIs_development": [#196], "InputErrors": [#196], "_defineProperties": [#196], "_templateObject$1b": [#196], "ListTitle": [#196], "IcoContainer": [#196], "LoadingBar": [#196], "t1": [], "CheckPagePermissions": [#196], "y": [#196], "reactIs_development_14": [#196], "m": [#196], "Div": [#196], "generateMessageId": [#196], "LeftMenuLink$1": [#196], "x$1": [#196], "_toConsumableArray": [#196], "PluginHeaderTitle": [#196], "t": [], "Ide": [#196], "_templateObject$s": [#196], "_templateObject$G": [#196], "hasOwnProperty": [#196], "serverRestartWatcher": [#196], "Wrapper$7": [#196], "CloseButton": [#196], "DOCUMENT": [#196], "darken": [#196], "secondaryHotlineAdd": [#196], "Input$2": [#196], "_templateObject$B": [#196], "Li": [#196], "A$1": [#196], "_templateObject$1g": [#196], "Wrapper$5": [#196], "ownKeys": [#196], "_templateObject10": [#196], "_templateObject$y": [#196], "IcoWarning": [#196], "q": [#196], "isContextConsumer": [#196], "reactIs": [#196], "renderButton": [#196], "getStatics": [#196], "_templateObject$D": [#196], "_nonIterableSpread": [#196], "_iterableToArray": [#196], "UserProvider": [#196], "QUESTION": [#196], "generateAllowedActions": [#196], "_templateObject$1": [#196], "Wrapper": [#196], "_config": [#196], "sn": [#196], "c$1": [#196], "Wrapper$3": [#196], "GlobalPagination": [#196], "propIsEnumerable": [#196], "_templateObject6": [#196], "LeftMenu": [#196], "e21": [], "getItemValues": [#196], "PluginHeaderTitle$1": [#196], "Wrapper$f": [#196], "hoistNonReactStatics": [#196], "immutable": [#196], "_templateObject3$1": [#196], "index$1": [#196], "primaryAddShape": [#196], "Wrapper$8": [#196], "X": [#196], "FooterModal": [#196], "isValidElementType": [#196], "RING": [#196], "Container$1": [#196], "k": [#196], "_templateObject$3": [#196], "_templateObject$e": [#196], "HeaderSearch": [#196], "cn$1": [#196], "initial": [#196], "v$1": [#196], "_": [#196], "FormModal": [#196], "PRODUCTION": [#196], "InputNumberWithErrors": [#196], "storeData": [#196], "f": [#196], "Z": [#196], "Profiler": [#196], "BlockerComponent": [#196], "Suspense": [#196], "reactIs_development_5": [#196], "init": [#196], "_templateObject$g": [#196], "_templateObject$9": [#196], "objectPrototype": [#196], "ForwardRef": [#196], "toObject": [#196], "Container$3": [#196], "reactIs_development_28": [#196], "Container": [#196], "reactRouterDom": [#196], "library": [#196], "_templateObject3": [#196], "index$2": [#196], "request": [#196], "MissingIcon": [#196], "userAgent": [#196], "validateInput": [#196], "asIcon": [#196], "React": [#196], "capitalize": [#196], "handleClick": [#196], "sizes$1": [#196], "_arrayWithHoles": [#196], "ButtonWrapper": [#196], "colors": [#196], "reactIs_development_12": [#196], "asSymbol": [#196], "c": [#196], "matchSorter": [#196], "LeftMenuList": [#196], "IcoDanger": [#196], "ModalHeader": [#196], "W": [#196], "_templateObject$V": [#196], "_templateObject$Z": [#196], "reactIs_development_17": [#196], "IS_IE": [#196], "BackHeader": [#196], "_templateObject$d": [#196], "TOKEN_KEY": [#196], "getQueryParameters": [#196], "reactstrap": [#196], "Element1": [#196], "styles$2": [#196], "HeaderModal": [#196], "InputCheckbox": [#196], "Subtitle": [#196], "_templateObject$Q": [#196], "getFileExtension": [#196], "DATA_FA_I2SVG": [#196], "w$2": [#196], "_defineProperty": [#196], "isPartialOfCase": [#196], "HeaderModal$1": [#196], "reactIs_development_20": [#196], "_templateObject$1a": [#196], "SelectNav": [#196], "Search": [#196], "x": [#196], "reactIs_development_15": [#196], "factoryWithThrowingShims": [#196], "useUser": [#196], "LeftMenuHeader": [#196], "y$1": [#196], "WrapperModal": [#196], "getHighestRanking": [#196], "_templateObject$1d": [#196], "isPortal": [#196], "_templateObject$S": [#196], "t11": [#196], "chars": [#196], "Div$1": [#196], "_templateObject$r": [#196], "has": [#196], "shims": [#196], "Bloc": [#196], "StyledPluginHeader": [#196], "z": [#196], "reactIs_development_13": [#196], "Layout": [#196], "ListHeader": [#196], "PluginHeaderActions": [#196], "useGlobalContext": [#196], "_$1__default": [#196], "Input$1": [#196], "parse": [#196], "tn": [#196], "getFilterType": [#196], "CheckPermissions": [#196], "functions": [#196], "isForwardRef": [#196], "_templateObject$1f": [#196], "f$1": [#196], "_templateObject9": [#196], "_templateObject$x": [#196], "auth": [#196], "PRODUCTION$1": [#196], "PluginHeader": [#196], "InputSearch": [#196], "InputTextAreaWithErrors": [#196], "LeftMenuIcon": [#196], "B": [#196], "ln": [#196], "removeAccents": [#196], "reactIs_development_11": [#196], "isFragment": [#196], "ANIMATION_BASE": [#196], "typeOf": [#196], "ensureCss": [#196], "isNode": [#196], "WINDOW": [#196], "_objectWithoutProperties": [#196], "Label": [#196], "FontAwesomeIcon": [#196], "isMemo": [#196], "CircleButton": [#196], "InputsIndex": [#196], "_nonIterableRest": [#196], "w": [#196], "reactIs_development_16": [#196], "caseRankings": [#196], "prepareValueForComparison": [#196], "_templateObject$12": [#196], "_templateObject$v": [#196], "Portal": [#196], "_templateObject8": [#196], "_templateObject4": [#196], "FILL": [#196], "renderIde": [#196], "_templateObject$z": [#196], "OverlayBlocker": [#196], "_templateObject$15": [#196], "icons": [#196], "_templateObject$7": [#196], "_templateObject2$6": [#196], "_defineProperty$1": [#196], "InputText": [#196], "I": [#196], "Div$2": [#196], "_templateObject$q": [#196], "_templateObject$E": [#196], "StyledHeader": [#196], "D": [#196], "reactIs_development_6": [#196], "InputPassword": [#196], "_templateObject$18": [#196], "ViewContainer": [#196], "getOwnPropertySymbols$1": [#196], "_templateObject$2": [#196], "getOwnPropertyDescriptor": [#196], "InputAddonWithErrors": [#196], "_typeof": [#196], "_templateObject$17": [#196], "Wrapper$2": [#196], "bindInternal4": [#196], "b$1": [#196], "EXCLAMATION": [#196], "_classCallCheck": [#196], "FormBloc": [#196], "Wrapper$e": [#196], "_byUnicode": [#196], "isLazy": [#196], "InputSelectWithErrors": [#196], "getOwnPropertyNames": [#196], "asFoundIcon": [#196], "e": [], "moment": [#196], "deGroup": [#196], "A": [#196], "Element": [], "removeAccents_1": [#196], "Lazy": [#196], "_templateObject$4": [#196], "_templateObject$8": [#196], "List": [#196], "objectAssign": [#196], "stringify": [#196], "Ico": [#196], "ErrorBoundary": [#196], "Search$1": [#196], "React__default": [#196], "joinStyles": [#196], "resolveIcons": [#196], "Clear": [#196], "_extends$1": [#196], "Wrapper$c": [#196], "ReactDOM": [#196], "reactIs_development_2": [#196], "StyledBody": [#196], "FORWARD_REF_STATICS": [#196], "ReactPropTypesSecret": [#196], "emptyFunction": [#196], "_templateObject$6": [#196], "p$1": [#196], "Container$2": [#196], "Wrapper$h": [#196], "n": [#196, #196], "b": [#196], "getClosenessRanking": [#196], "d$1": [#196], "sizes": [#196], "LoadingIndicatorPage": [#196], "Wrapper$a": [#196], "spin$2": [#196], "i": [#196], "h$1": [#196], "HeaderNav": [#196], "getAttrConfig": [#196], "USER_INFO": [#196], "g$1": [#196], "getPrototypeOf": [#196], "parseTransformString": [#196], "_objectSpread": [#196], "objectWithKey": [#196], "_templateObject$L": [#196], "_templateObject$P": [#196], "StyledModal$1": [#196], "d": [#196], "IcoSuccess": [#196], "build": [#196], "secondary": [#196], "styled__default": [#196], "reactIs_development_7": [#196], "_templateObject$W": [#196], "characterMap": [#196], "isProfiler": [#196], "formatData": [#196], "config": [#196], "_taggedTemplateLiteralLoose": [#196], "remove": [#196], "StyledButton": [#196], "pn": [#196], "SearchInfos": [#196], "blink": [#196], "MEMO_STATICS": [#196], "_templateObject$R": [#196], "Row": [#196], "_createClass": [#196], "LeftMenuLink": [#196], "asyncSetTimer": [#196], "convert": [#196], "Wrapper$d": [#196], "SettingsPageTitle": [#196], "t$1": [#196], "createCommonjsModule": [#196], "joinAttributes": [#196], "_DOCUMENT": [#196], "reducer": [#196], "IS_DOM": [#196], "StyledFooter": [#196], "getKeyAttributes": [#196], "_templateObject$I": [#196], "dateFormats": [#196], "UserContext": [#196], "_iterableToArrayLimit": [#196], "a": [#196, #196], "InputCheckboxWithErrors": [#196], "BaselineAlignment": [#196], "normalizeIconArgs": [#196], "generateResultsObject": [#196], "_templateObject$T": [#196], "_templateObject$X": [#196], "BodyModal": [#196], "useQuery": [#196], "_templateObject$K": [#196], "getAcronym": [#196], "_templateObject$_": [#196], "_templateObject2$5": [#196], "k$1": [#196], "StrapiContext": [#196], "baseStyles": [#196], "Input": [#196], "DefaultInputError": [#196], "_templateObject$11": [#196], "q$1": [#196], "propTypes$1": [#196], "e22": [#196], "AsyncMode": [#196], "_templateObject2": [#196], "StyledButtonModalSuccess": [#196], "_templateObject$14": [#196], "InputSearchWithErrors": [#196], "_templateObject$u": [#196], "Overlay": [#196], "n$1": [#196], "spin": [#196], "O": [#196], "reactIs_development_10": [#196], "DEFAULT_FAMILY_PREFIX": [#196], "an": [#196], "_templateObject$l": [#196], "Div$3": [#196], "_templateObject$p": [#196], "REACT_STATICS": [#196], "isContextProvider": [#196], "back": [#196], "_templateObject$c": [#196], "_objectWithoutPropertiesLoose": [#196], "htmlEscape": [#196], "styles$3": [#196], "Div$4": [#196], "reactIs_development_24": [#196], "Bkg": [#196], "_templateObject$w": [#196], "_templateObject$16": [#196], "_templateObject2$1": [#196], "E": [#196], "InputEmailWithErrors": [#196], "EyeWrapper": [#196], "rn": [#196], "toHtml": [#196], "css": [#196], "_templateObject$19": [#196], "templateObject": [#196], "en": [#196], "L": [#196], "hasPermissions": [#196], "InputTextArea": [#196], "ContextConsumer": [#196], "_templateObject$10": [#196], "IcoInfo": [#196], "_templateObject$i": [#196], "S": [#196], "isConcurrentMode": [#196], "G": [#196], "meaninglessTransform": [#196], "un": [#196], "styles": [#196], "_templateObject2$3": [#196], "PERFORMANCE": [#196], "_objectSpread2": [#196], "PageFooter": [#196], "_templateObject$t": [#196], "N": [#196], "_slicedToArray": [#196], "reactIs_development_9": [#196], "reactIs_development_21": [#196], "_templateObject11": [#196], "deleteStyle": [#196], "subtractLight": [#196], "_templateObject2$4": [#196], "BackButton": [#196], "_templateObject$5": [#196], "nn": [#196], "ContainerFluid": [#196], "_templateObject$k": [#196], "Library": [#196], "on": [#196], "hoistNonReactStatics_cjs": [#196], "InputPasswordWithErrors": [#196], "ButtonModal": [#196], "useUserPermissions": [#196], "_templateObject$1e": [#196], "w$1": [#196], "fillBlack": [#196], "InputSpacer": [#196], "convertCurry": [#196], "reactIs_development_23": [#196], "reactIs_development_3": [#196], "Wrapper$b": [#196], "reactIs_development_19": [#196], "h": [#196], "insertCss": [#196], "_MUTATION_OBSERVER": [#196], "SelectWrapper": [#196], "shouldCheckPermissions": [#196], "useStrapi": [#196], "Filter$1": [#196], "_$1": [#196], "Wrapper$g": [#196], "defineIcons": [#196], "o": [#196], "InputTextWithErrors": [#196], "difference": [#196], "findIconDefinition": [#196], "ModalSection": [#196], "v": [#196], "styled": [#196], "reduce": [#196], "e2": [#196, #196], "Loader": [#196], "Loader$1": [#196], "loaded": [#196], "transformForSvg": [#196], "primary": [#196], "_templateObject$M": [#196], "reactIs_development_1": [#196], "_asyncToGenerator": [#196], "_interopDefault": [#196], "log": [#196], "j": [#196], "_templateObject7": [#196], "_byOldName": [#196], "z$1": [#196], "IntlInput": [#196], "isSuspense": [#196], "reactIs_development_8": [#196], "getMatchRanking": [#196], "reactIs_development_4": [#196], "InputToggle": [#196], "_templateObject$H": [#196], "DELAY": [#196], "StrictMode": [#196], "icon": [#196], "ALL_SPACE": [#196], "StyledBackHeader": [#196], "camelize": [#196], "DUOTONE_CLASSES": [#196], "l": [#196], "ListRow": [#196], "_templateObject$O": [#196], "shouldUseNative": [#196], "findMatchingPermissions": [#196], "Filter": [#196], "InputAddon": [#196], "isStrictMode": [#196], "g": [#196], "s": [#196]} does not contain e21#196'
```

**Comment by kdy1** [comment]
Fixed it.
