### ISSUE TITLE
You can enable decorator support. See https://swc-project.github.io/docs/configuring-swc.html#jscparser and https://swc-project.github.io/docs/configuring-swc.html#jsctransformdecoratormetadata

### ISSUE THREAD

**Issue by joebnb** [swc-project/swc#1061]
You can enable decorator support. See https://swc-project.github.io/docs/configuring-swc.html#jscparser and https://swc-project.github.io/docs/configuring-swc.html#jsctransformdecoratormetadata

_Originally posted by @kdy1 in https://github.com/swc-project/swc/issues/1055#issuecomment-690255478_

i tried it before submit issue ,its not working

**Comment by kdy1** [comment]
Can you share your error message?

**Comment by joebnb** [comment]
> Can you share your error message?

sure,wait moment

**Comment by joebnb** [comment]
i found if enable tsx 
```json
{
                loader: "swc-loader",
                options: {
                    sync: true,
                    "jsc": {
                        "parser": {
                            "syntax": "typescript",
                            "decorators": true,
                            "dynamicImport": true,
                            "tsx": true      //   may this cause
                        },
                        "transform": {
                            "legacyDecorator": true,
                            "decoratorMetadata": true
                        }
                    }
                }
            },
```
will throw 
```shell
ERROR in /Users/never/Documents/workSpace/reborn/src/pages/page_demo/components/common/module.ts
Module build failed (from ../sfe/sfe-builder-angular/node_modules/happypack/loader.js):
Error: GenericFailure: failed to process js file

Caused by:
    failed to parse module
    at Compiler.transformSync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/@swc/core/index.js:116:25)
    at Object.transformSync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/@swc/core/index.js:196:21)
    at Object.<anonymous> (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/swc-loader/src/index.js:73:36)
    at applySyncOrAsync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:283:9
    at /Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:339:17
    at Object.callback (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/fnOncePedantic.js:10:15)
    at Object.module.exports (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/angular2-template-loader/index.js:56:10)
    at applySyncOrAsync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:277:5)
    at /Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:135:7
    at applyPitchLoader (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:188:14)
    at applyPitchLoader (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:196:14)
    at applyPitchLoader (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:196:14)
    at applyPitchLoaders (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:226:4)

ERROR in /Users/never/Documents/workSpace/reborn/src/common/components/rich-text/rich-editor.component.ts
Module build failed (from ../sfe/sfe-builder-angular/node_modules/happypack/loader.js):
Error: GenericFailure: failed to process js file

Caused by:
    failed to parse module
    at Compiler.transformSync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/@swc/core/index.js:116:25)
    at Object.transformSync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/@swc/core/index.js:196:21)
    at Object.<anonymous> (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/swc-loader/src/index.js:73:36)
    at applySyncOrAsync (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:350:21)
    at apply (/Users/never/Documents/workSpace/sfe/sfe-builder-angular/node_modules/happypack/lib/applyLoaders.js:277:5)
```

if set jsx disable,it seems working

```
ERROR in /Users/never/Documents/workSpace/reborn/node_modules/@toast-ui/editor/dist/i18n/zh-cn.js 18:12
Module parse failed: Unexpected token (18:12)
File was processed with these loaders:
 * ../sfe/sfe-builder-angular/node_modules/happypack/loader.js
You may need an additional loader to handle the result of these loaders.
| })(window, function(__WEBPACK_EXTERNAL_MODULE__0__) {
|     return /******/
>     function(modules) {
|         /******/
|         // The module cache

ERROR in /Users/never/Documents/workSpace/reborn/node_modules/@toast-ui/editor/dist/toastui-editor-viewer.js 22:12
Module parse failed: Unexpected token (22:12)
File was processed with these loaders:
 * ../sfe/sfe-builder-angular/node_modules/happypack/loader.js
You may need an additional loader to handle the result of these loaders.
| })(window, function() {
|     return /******/
>     function(modules) {
|         /******/
|         // The module cache

```

**Comment by kdy1** [comment]
Thanks for a detailed report! I'll fix it soon.

**Comment by joebnb** [comment]
> Thanks for a detailed report! I'll fix it soon.

im looking forward to it.

by the way how to solve this problem,Is it caused by my configuration?
```shell
ERROR in /Users/never/Documents/workSpace/reborn/node_modules/@toast-ui/editor/dist/i18n/zh-cn.js 18:12
Module parse failed: Unexpected token (18:12)
File was processed with these loaders:
 * ../sfe/sfe-builder-angular/node_modules/happypack/loader.js
You may need an additional loader to handle the result of these loaders.
| })(window, function(__WEBPACK_EXTERNAL_MODULE__0__) {
|     return /******/
>     function(modules) {
|         /******/
|         // The module cache
```

**Comment by kdy1** [comment]
It seems like a bug of codegen. A return statement should not have newline between `return` and the returned value.
If a newline exists, function is parsed as function declaration, which *must* have ident. But there's no one, so it results in a parsing error.


Btw, can you share some part of your code? I want to test it, and finding breaking code is hard.

**Comment by joebnb** [comment]
> It seems like a bug of codegen. A return statement should not have newline between `return` and the returned value.
> If a newline exists, function is parsed as function declaration, which _must_ have ident. But there's no one, so it results in a parsing error.
> 
> Btw, can you share some part of your code? I want to test it, and finding breaking code is hard.

yes,i remove `newline between return and the returned value`  this error has gone,but it seems generated code still have some error.

![image](https://user-images.githubusercontent.com/1646883/92852542-6d1df780-f421-11ea-99c9-3ca48dac6726.png)

package you can find in toast ui editor `npm i @toast-ui/editor@2.3.1`

![image](https://user-images.githubusercontent.com/1646883/92853565-912e0880-f422-11ea-8413-c34b2cefe7ba.png)

**Comment by joebnb** [comment]
this issue should be closed

**Comment by kdy1** [comment]
@joebnb Did you verified that `swc@v1.2.26` works?

**Comment by joebnb** [comment]
> @joebnb Did you verified that `swc@v1.2.26` works?

works well,this error message was gone
