### ISSUE TITLE
Panic compiling three.js

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [swc-project/swc#1088]
**Panic compiling three.js**

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ecmascript/utils/src/constructor.rs:18:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ecmascript/utils/src/constructor.rs:18:34
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ecmascript/utils/src/constructor.rs:18:34
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ecmascript/utils/src/constructor.rs:18:34
fatal runtime error: failed to initiate panic, error 5
```

**Input code**
```sh
git clone clone https://github.com/mrdoob/three.js.git
cd three.js
npm i -D @swc/core @swc/cli
npx swc src -d dist
```

**Expected behavior**
Compile src into directory dist

**Version**
The version of @swc/core: 
@swc/cli@0.1.26
@swc/core@1.2.30

**Additional context**

**OS:** Arch Linux

**Comment by kdy1** [comment]
Closing as fixed.

I used 


`spack.config.js`:

```
module.exports = {
    entry: {
        'app': __dirname + '/src/Three.js',
    },
    output: {
        path: __dirname + '/lib'
    },
};

```
