### ISSUE TITLE
Legacy octal escape is not permitted in strict mode

### ISSUE THREAD

**Issue by vinz243** [swc-project/swc#128]
HI,

I'm getting this error when trying to compile a few test files :

```
C:\...>npx -p swc -p swc-cli swc *.js -o out.js
error: Legacy octal escape is not permitted in strict mode
 --> <GLOBAL.Path>:1:45
  |
1 | 'C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\In
tel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\S
ystem32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Java\jdk-11.0.1\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files\nodejs\;C:\Users\vrs\AppData\Local\Microsoft\WindowsApps;C:\Users\vrs\AppData\Local\Programs\Mi
crosoft VS Code\bin;C:\Users\vrs\AppData\Roaming\npm;C:\Users\vrs\bin\Sencha\Cmd;'
  |                                             ^^

Error: internal error in Neon module: failed to parse global variable Path=`'C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windo
ws;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\I
ntel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOW
S\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Java\jdk-11.0.1\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files\nodejs\;C:\Users\vrs\Ap
pData\Local\Microsoft\WindowsApps;C:\Users\vrs\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\vrs\AppData\Roaming\npm;C:\Users\vrs\bin\Sencha\Cmd;'` as module
    at Object.transformFileSync (C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc\lib\index.js:15:43)
    at Promise (C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\util.js:68:32)
    at new Promise (<anonymous>)
    at Object.compile (C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\util.js:66:12)
    at C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\file.js:155:47
    at Generator.next (<anonymous>)
    at C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\file.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\file.js:3:12)
    at C:\Users\vrs\AppData\Roaming\npm-cache\_npx\7000\node_modules\swc-cli\lib\src\file.js:148:28
```

Thanks in advance

**Comment by kdy1** [comment]
It was a bug of the `InlineGlobals` pass. It previously tried to inline *all* environment variables.
I fixed it with `swc@1.0.0-beta.25`

**Comment by vinz243** [comment]
Indeed, it's working. Thanks ! I get an error tho 👍 
```
error: Class property requires `esnext.classProperty` to be true 
```

Inside my `jsc.parser` (alongside the .js files)

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "numericSeparator": true,
      "classPrivateProperty": true,
      "privateMethod": true,
      "classProperty": true,
      "functionBind": true,
      "decorators": true,
      "decoratorsBeforeExport": true
    }
  }
}
```

**Comment by kdy1** [comment]
Do you mean swc reports an error even though `classProperty: true` is set?

And error message is misleading... I'll fix it soon.

**Comment by quickAppPlus** [comment]
> Do you mean swc reports an error even though `classProperty: true` is set?
> 
> And error message is misleading... I'll fix it soon.

Did you fix it now ? I got this error too.

**Comment by kdy1** [comment]
@quickAppPlus Do you mean legacy octal escape?
If it is, I fixed in swc but I forgot fixing @swc/cli
