### ISSUE TITLE
panic: re-export alias

### ISSUE THREAD

**Issue by tamasfe** [swc-project/swc#1307]
<s>Probably a data race, `--sync` fixes it.</s>

1. Source code
```ts
export * as foo from "./foo";
```

2. `.swcrc` file
```json
{
  "exclude": ".*.test.ts$",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": true
    },
    "target": "es2020",
    "loose": true
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

3. Error message gained from `swc --sync <input.js>`
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: export default from 'foo'; should be removed by previous pass', ecmascript/transforms/src/modules/import_analysis.rs:106:18
```

4. Backtrace

```
Backtrace:    0: node::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:493:5
   5: std::panicking::begin_panic_fmt
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:435:5
   6: <swc_ecma_transforms::modules::import_analysis::ImportAnalyzer as swc_ecma_visit::Fold>::fold_module
   7: swc_ecma_visit::fold_program
   8: swc::Compiler::process_js_file
   9: napi::async_work::execute
  10: worker
             at /home/iojs/build/ws/out/../deps/uv/src/threadpool.c:122:5
  11: start_thread
  12: __clone
```

**Comment by tamasfe** [comment]
Actually, just `--sync` doesn't seem to fix it, as the generated code will still be either incorrect, or will still panic in some cases.

The following can be used as a workaround:

```ts
import * as _foo from "./foo";

export const foo = _foo;
```
