### ISSUE TITLE
TypeError: Can not find node binding files from @swc/core-darwin-x64 and /Users/jayfong/Documents/github/vtils/node_modules/.pnpm/registry.npm.taobao.org/@swc/core@1.2.48/node_modules/@swc/core/swc.darwin-x64.node     at Object.loadBinding (/Users/jayfong/Documents/github/vtils/node_modules/.pnpm/registry.npm.taobao.org/@node-rs/helper@1.1.0/node_modules/@node-rs/helper/lib/loader.js:27:11)

### ISSUE THREAD

**Issue by fjc0k** [swc-project/swc#1428]
```bash
TypeError: Can not find node binding files from @swc/core-darwin-x64 and /Users/jayfong/Documents/github/vtils/node_modules/.pnpm/registry.npm.taobao.org/@swc/core@1.2.48/node_modules/@swc/core/swc.darwin-x64.node
    at Object.loadBinding (/Users/jayfong/Documents/github/vtils/node_modules/.pnpm/registry.npm.taobao.org/@node-rs/helper@1.1.0/node_modules/@node-rs/helper/lib/loader.js:27:11)
```

but `1.2.47` ok.

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/108727187-3d902100-7563-11eb-82d0-7afea760b2ff.png)

**Comment by fjc0k** [comment]
😂😂😂😂😂😂 solved: https://npm.taobao.org/sync/@swc/core-darwin-x64

**Comment by sporto** [comment]
We are getting in 1.2.48
```
TypeError: Can not find node binding files from @swc/core-linux-x64-gnu, @swc/core-linux-x64-gnux32, @swc/core-linux-x64-musl ...
```

What is the fix? Thanks
