### ISSUE TITLE
bug: can't parse abstract class

### ISSUE THREAD

**Issue by ruscon** [swc-project/swc#1454]
**Input code**
```
export abstract class AbstractProviderDeliveryService {
}
```

**Describe the bug**
```bash
❯ npx swc src -s -d ./dist
error: Expected {, got abstract
  --> src/modules/delivery/provider/AbstractProviderDeliveryService.ts:73:8
   |
73 | export abstract class AbstractProviderDeliveryService {
   |        ^^^^^^^^

failed to process js file

Caused by:
    failed to parse module
Successfully compiled 188 files with swc.
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (node_modules/@swc/cli/lib/swc/util.js:152:15)
    at default_1 (node_modules/@swc/cli/lib/swc/dir.js:137:14)
```

**Config**

```json
{
    "test": ".*.ts$",
    "sourceMaps": true,
    "jsc": {
      "loose": true,
      "target": "es2018",
      "parser": {
        "syntax": "typescript",
        "tsx": false,
        "decorators": true,
        "dynamicImport": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
      }
    },
    "module": {
        "type": "commonjs",
        "strict": true,
        "strictMode": false,
        "lazy": false,
        "noInterop": false
    }
}
```

**Expected behavior**
Should be parsed without error

**Version**
The version of @swc/core: 1.2.50
The version of @swc/cli: 0.1.35

**Comment by ruscon** [comment]
Hi @kdy1, 
You closed the issue, but I don't understand if the bug is fixed or not.
I checked with the latest `"@swc/core": "1.2.54"` version and it doesn't work.

**Comment by kdy1** [comment]
I tested it but it works, both from rust side and using swc cli.


My output:

```sh
➜  lab npx swc index.ts
Successfully compiled 1 file with swc.
class AbstractProviderDeliveryService {
}
exports.AbstractProviderDeliveryService = AbstractProviderDeliveryService;


//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzdGRvdXQifQ==%
```


Please ensure that you are using the proper version of swc.
You have to install both of `@swc/cli` and `@swc/core` locally.

**Comment by ruscon** [comment]
@kdy1, I found the issue.

A simple example to reproduce:
``` typescript
// tmp/AbstractProviderDeliveryService.ts
export abstract class AbstractProviderDeliveryService {
     // legal typescript method annotation
    async prepareGetRequest?(): Promise<any>;
}
```


```shell
npx swc tmp -s -d ./dist
```

Output:
```
error: Expected {, got abstract
 --> tmp/AbstractProviderDeliveryService.ts:1:8
  |
1 | export abstract class AbstractProviderDeliveryService {
  |        ^^^^^^^^

failed to process js file

Caused by:
    failed to parse module
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (node_modules/@swc/cli/lib/swc/util.js:152:15)
    at default_1 (node_modules/@swc/cli/lib/swc/dir.js:137:14)
```

But the real issue is in this typescript construction `?():`

**Comment by kdy1** [comment]
`?` after the method name seems to be a cause.

**Comment by ruscon** [comment]
> `?` after the method name seems to be a cause.

Yes, but this is valid typescript code

**Comment by fregante** [comment]
I still have this issue with  `@swc/core": "^1.2.60`

```

error: Expected {, got abstract
   --> ./src/extensionPoints/menuItemExtension.ts:104:8
    |
104 | export abstract class MenuItem extends Extension<MenuItemConfig> {
    |        ^^^^^^^^
```

**Comment by kdy1** [comment]
Closing as the example is wrong.
