### ISSUE TITLE
No output when running npx swc /index.ts

### ISSUE THREAD

**Issue by nemonemi** [swc-project/swc#1469]
Hello,
I'm trying out this tool, which, btw. looks very promising, with a super simple setup.
```
/mod
  index.ts
index.ts
.swcrc
spack.config.js
```

**Describe the bug**
When I run the `npx swc /index.ts`, the command gets executed, but no output in the terminal and no bundle being produced.
When I run the `npx spack` the following error gets shown:
```ts
λ npx spack
(node:38224) UnhandledPromiseRejectionWarning: Error: load_transformed failed

Caused by:
    0: Bundler.load() failed
    1: Bundler.loader.load(C:\www\playground\graphql_ensemble\playground\services\service_2\index.js) failed
    2: failed to load file `C:\www\playground\graphql_ensemble\playground\services\service_2\index.js`
    3: The system cannot find the file specified. (os error 2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Input code**
```ts
// /mod/index.ts
export const sum = (a: number, b: number) => a + b;

// index.ts
import {sum as add} from "./mod";

console.log(add(1,2));
```

**Config**
.swcrc
```json
{
    "jsc": {
        "target": "es5",
        "parser": {
            "syntax": "typescript",
        }
    }
}
```
spack.config.js
```ts
const { config } = require("@swc/core/spack");
const path = require("path");

module.exports = config({
    entry: {
        build: path.join(__dirname, "index.js"),
    },
    output: {
        path: path.join(__dirname, '/lib'),
    },
});
```

**Expected behavior**
I expect bundling and transpilation to be performed.

**Version**
The version of @swc/core:

    @swc/core: 1.2.50

--
Other:

    @swc/cli: 0.1.35
    @swc/helpers: 0.2.4
    node: 14.16.0
    yarn: 12.22.10

**Additional context**
If I run the command like this `npx swc index.ts` (no slash in front of the file), then it produces the following error output:
```ts
λ npx swc index.ts
failed to process js file

Caused by:
    0: failed to load config for file 'Real("index.ts")'
    1: failed to read swcrc file (index.ts)
    2: failed to deserialize .swcrc (json) file: syntax error: 6:9
    3: trailing comma at line 6 column 9
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (C:\www\playground\graphql_ensemble\playground\services\service_2\node_modules\@swc\cli\lib\swc\util.js:152:15)
    at files (C:\www\playground\graphql_ensemble\playground\services\service_2\node_modules\@swc\cli\lib\swc\file.js:176:18)
    at async default_1 (C:\www\playground\graphql_ensemble\playground\services\service_2\node_modules\@swc\cli\lib\swc\file.js:190:9)
```

**Comment by kdy1** [comment]
I think you need to run `npx swc index.ts`

**Comment by nemanjamilosavljevic-newtron** [comment]
@kdy1, I've tried it. Please check the **Additional context** section above.

**Comment by kdy1** [comment]
I found that your .swcrc is invalid.

```json
{
    "jsc": {
        "target": "es5",
        "parser": {
            "syntax": "typescript", // <- This comma is wrong
        }
    }
}
```

**Comment by nemonemi** [comment]
Thanks, @kdy1.
