### ISSUE TITLE
panic: async function

### ISSUE THREAD

**Issue by mirek** [swc-project/swc#1477]
1. Source code
```js
async function f(a, b) {
  const [ { a: a_ = 1 } ] = JSON.parse(b)
}
```
or:
```
npx swc --no-swcrc << 'END'
async function f(a, b) {
  const [ { a: a_ = 1 } ] = JSON.parse(b)
}
END
```

2. `.swcrc` file
`--no-swcrc`

3. Error message
```
npx swc --no-swcrc --sync swc-bug.ts
thread '<unnamed>' panicked at 'not implemented: assignment pattern AssignPat { span: Span { lo: BytePos(40), hi: BytePos(46), ctxt: #0 }, left: Ident(BindingIdent { id: Ident { span: Span { lo: BytePos(40), hi: BytePos(42), ctxt: #2 }, sym: Atom('a_' type=inline), optional: false }, type_ann: None }), right: Lit(Num(Number { span: Span { lo: BytePos(45), hi: BytePos(46), ctxt: #0 }, value: 1.0 })), type_ann: None }', ecmascript/transforms/compat/src/es2015/destructuring.rs:810:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
not implemented: assignment pattern AssignPat { span: Span { lo: BytePos(40), hi: BytePos(46), ctxt: #0 }, left: Ident(BindingIdent { id: Ident { span: Span { lo: BytePos(40), hi: BytePos(42), ctxt: #2 }, sym: Atom('a_' type=inline), optional: false }, type_ann: None }), right: Lit(Num(Number { span: Span { lo: BytePos(45), hi: BytePos(46), ctxt: #0 }, value: 1.0 })), type_ann: None }
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/mirek/.../node_modules/@swc/cli/lib/swc/util.js:152:15)
    at files (/Users/mirek/.../node_modules/@swc/cli/lib/swc/file.js:176:18)
```

4. Backtrace
```
SWC_DEBUG=1 npx swc --no-swcrc --sync swc-bug.ts
Backtrace:    0: _napi_register_module_v1
   1: <unknown>
   2: _rust_eh_personality
   3: _rust_eh_personality
   4: _rust_eh_personality
   5: _rust_eh_personality
   6: _rust_eh_personality
   7: _rust_eh_personality
   8: _rust_eh_personality
   9: _rust_eh_personality
  10: _rust_eh_personality
  11: _rust_eh_personality
  12: _rust_eh_personality
  13: _rust_eh_personality
  14: _rust_eh_personality
  15: _rust_eh_personality
  16: _rust_eh_personality
  17: _rust_eh_personality
  18: _rust_eh_personality
  19: _rust_eh_personality
  20: _rust_eh_personality
  21: _rust_eh_personality
  22: _rust_eh_personality
  23: _rust_eh_personality
  24: _rust_eh_personality
  25: _rust_eh_personality
  26: _rust_eh_personality
  27: _rust_eh_personality
  28: _rust_eh_personality
  29: _rust_eh_personality
  30: _rust_eh_personality
  31: _rust_eh_personality
  32: _rust_eh_personality
  33: _rust_eh_personality
  34: _rust_eh_personality
  35: _rust_eh_personality
  36: _rust_eh_personality
  37: <unknown>
  38: __ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  39: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  40: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  41: __ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE

not implemented: assignment pattern AssignPat { span: Span { lo: BytePos(40), hi: BytePos(46), ctxt: #0 }, left: Ident(BindingIdent { id: Ident { span: Span { lo: BytePos(40), hi: BytePos(42), ctxt: #2 }, sym: Atom('a_' type=inline), optional: false }, type_ann: None }), right: Lit(Num(Number { span: Span { lo: BytePos(45), hi: BytePos(46), ctxt: #0 }, value: 1.0 })), type_ann: None }
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/mirek/.../node_modules/@swc/cli/lib/swc/util.js:152:15)
    at files (/Users/mirek/ab/.../@swc/cli/lib/swc/file.js:176:18)
```

**Comment by mirek** [comment]
Btw. dropping `async` from function seems to work just fine.
