### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by matiosfree** [swc-project/swc#1546]
**Describe the bug**
When I'm trying to use it on some project React+Webpack+TypeScript, I'm getting an error:
```
Error: Cannot find module 'node_modules\@swc\core\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
```

**Input code**

webpack config:
```
{
        test:/\.(js|jsx|ts|tsx)$/,
        loader: 'swc-loader',
        exclude: /node_modules/
},
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    }
  }
}
```

**Expected behavior**
no error happens

**Version**
The version of @swc/core: v1.2.52 (master branch)

**Comment by matiosfree** [comment]
ah, sorry for that. seems I installed sources from master but not the builded package
