### ISSUE TITLE
bug: _applyDecoratedDescriptor TypeError: Cannot redefine property

### ISSUE THREAD

**Issue by ruscon** [swc-project/swc#1592]
I think it is related to this 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_redefine_property#non-configurable_properties_created_by_object.defineproperty

**Describe the bug**
```shell
/dist/test.js:22
        Object.defineProperty(target, property, desc);
               ^

TypeError: Cannot redefine property: logger
    at Function.defineProperty (<anonymous>)
    at _applyDecoratedDescriptor (dist/test.js:22:16)
    at Object.<anonymous> (dist/test.js:66:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Input code**
```typescript
class LoggerService {
    debug(message: string): void {
        console.log({ message });
    }
}

export function Logger(): any {
    return (target: Record<string, any>, key: string | symbol): void => {
        const loggerService: LoggerService = new LoggerService();
        const updated: boolean = Reflect.defineProperty(target, key, {
            configurable: false,
            enumerable: true,
            value: loggerService,
            writable: false,
        });

        if (!updated) {
            throw new Error(`Unable to define ${String(key)} property for ${JSON.stringify(target)}`);
        }
    };
}

class TestClass1 {
    @Logger() private readonly logger: LoggerService;

    test(): void {
        this.logger.debug('test1');
    }
}

class TestClass2 {
    @Logger() private readonly logger: LoggerService;

    test(): void {
        this.logger.debug('test2');
    }
}

(async (): Promise<void> => {
    new TestClass1().test();
    new TestClass2().test();
    console.log('OK');
})();
```

**Config**

```json
{
    "test": ".*.ts$",
    "sourceMaps": true,
    "jsc": {
      "loose": true,
      "target": "es2020",
      "parser": {
        "syntax": "typescript",
        "tsx": false,
        "decorators": true,
        "dynamicImport": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
      }
    },
    "module": {
        "type": "commonjs",
        "strict": true,
        "strictMode": false,
        "lazy": false,
        "noInterop": false
    }
}
```

compiled code with`@swc/cli`:

```javascript
// dist/test.js

exports.Logger = Logger;
function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) {
    var desc = {
    };
    Object.keys(descriptor).forEach(function(key) {
        desc[key] = descriptor[key];
    });
    desc.enumerable = !!desc.enumerable;
    desc.configurable = !!desc.configurable;
    if ("value" in desc || desc.initializer) {
        desc.writable = true;
    }
    desc = decorators.slice().reverse().reduce(function(desc, decorator) {
        return decorator(target, property, desc) || desc;
    }, desc);
    if (context && desc.initializer !== void 0) {
        desc.value = desc.initializer ? desc.initializer.call(context) : void 0;
        desc.initializer = undefined;
    }
    if (desc.initializer === void 0) {
        Object.defineProperty(target, property, desc);
        desc = null;
    }
    return desc;
}
function _initializerDefineProperty(target, property, descriptor, context) {
    if (!descriptor) return;
    Object.defineProperty(target, property, {
        enumerable: descriptor.enumerable,
        configurable: descriptor.configurable,
        writable: descriptor.writable,
        value: descriptor.initializer ? descriptor.initializer.call(context) : void 0
    });
}
var _class, _descriptor, _class1, _descriptor1;
class LoggerService {
    debug(message) {
        console.log({
            message
        });
    }
}
function Logger() {
    return (target, key)=>{
        const loggerService = new LoggerService();
        const updated = Reflect.defineProperty(target, key, {
            configurable: false,
            enumerable: true,
            value: loggerService,
            writable: false
        });
        if (!updated) {
            throw new Error(`Unable to define ${String(key)} property for ${JSON.stringify(target)}`);
        }
    };
}
var _dec = Logger(), _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", typeof LoggerService === "undefined" ? Object : LoggerService);
let TestClass1 = ((_class = class TestClass11 {
    test() {
        this.logger.debug('test1');
    }
    constructor(){
        _initializerDefineProperty(this, "logger", _descriptor, this);
    }
}) || _class, _descriptor = _applyDecoratedDescriptor(_class.prototype, "logger", [
    _dec,
    _dec1
], {
    configurable: true,
    enumerable: true,
    writable: true,
    initializer: void 0
}), _class);
var _dec2 = Logger(), _dec3 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", typeof LoggerService === "undefined" ? Object : LoggerService);
let TestClass2 = ((_class1 = class TestClass21 {
    test() {
        this.logger.debug('test2');
    }
    constructor(){
        _initializerDefineProperty(this, "logger", _descriptor1, this);
    }
}) || _class1, _descriptor1 = _applyDecoratedDescriptor(_class1.prototype, "logger", [
    _dec2,
    _dec3
], {
    configurable: true,
    enumerable: true,
    writable: true,
    initializer: void 0
}), _class1);
(async ()=>{
    new TestClass1().test();
    new TestClass2().test();
    console.log('OK');
})();

//# sourceMappingURL=../test.js.map
```

**How to run the code**
```shell
node -r ./node_modules/reflect-metadata/Reflect.js dist/test.js
```

**Expected behavior**
Code should run without error.
This code example runs successfully if compiled with tsc.

As I see, the main issue is that in our `Logger` function we use `configurable: false` and the  `swc` function `_applyDecoratedDescriptor ` does not check if it has the right to update the given property

I found a solution for `swc`:
Change part of the `_applyDecoratedDescriptor` function from this 
```javascript
    if (desc.initializer === void 0) {
        Object.defineProperty(target, property, desc);
        desc = null;
    }
```
to this:
```javascript
    if (desc.initializer === void 0) {
        const descriptors = Object.getOwnPropertyDescriptors(target); // add this
        if (descriptors[property].configurable) { // add this
            Object.defineProperty(target, property, desc);
        } // add this
        desc = null;
    }
```

**Version**
The version of @swc/core: "1.2.54"
The version of @swc/cli: "0.1.39"

**Comment by ruscon** [comment]
@kdy1 any news about this bug?

**Comment by ruscon** [comment]
@kdy1, can we fix this ?
I have described a possible solution

**Comment by kdy1** [comment]
@ruscon Of course, but I have lots of things to do.
