### ISSUE TITLE
panic: Fails when applying Visitor to Typescipt const assertion on default export

### ISSUE THREAD

**Issue by quickgiant** [swc-project/swc#1625]
1. Source code
```
const { transformSync } = require("@swc/core");
const Visitor = require("@swc/core/Visitor").default;

transformSync(
    `
export default {
  foo: 'foo',
} as const;
`,
    { jsc: { parser: { syntax: 'typescript' } }, plugin: (p) => new Visitor().visitProgram(p) }
);

```

2. Error message
```
node_modules/@swc/core/index.js:125
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                        ^

Error: failed to deserialize Program: Error("missing field `expression`", line: 0, column: 0)
    at Compiler.transformSync (node_modules/@swc/core/index.js:125:25)
    at Compiler.transformSync (node_modules/@swc/core/index.js:123:25)
    at transformSync (node_modules/@swc/core/index.js:203:21)
    at Object.<anonymous> (swc-test.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'GenericFailure'
}
```

3. Backtrace
```
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
   9: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  10: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  11: <unknown>
             at /home/iojs/build/ws/out/../../deps/v8/src/builtins/base.tq:1866
```

**Comment by quickgiant** [comment]
Looks like const assertions on strings inside of objects fail in a similar way:
```
const { transformSync } = require("@swc/core");
const Visitor = require("@swc/core/Visitor").default;

transformSync(
    `
const fooObj = {
  foo: 'foo' as const,
};
`,
    { jsc: { parser: { syntax: 'typescript' } }, plugin: (p) => new Visitor().visitProgram(p) }
);
```

Error:
```
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
   9: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  10: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  11: <unknown>
             at /home/iojs/build/ws/out/../../deps/v8/src/builtins/base.tq:1866

node_modules/@swc/core/index.js:125
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                        ^

Error: failed to deserialize Program: Error("missing field `value`", line: 0, column: 0)
    at Compiler.transformSync (node_modules/@swc/core/index.js:125:25)
    at Compiler.transformSync (node_modules/@swc/core/index.js:123:25)
    at transformSync (node_modules/@swc/core/index.js:203:21)
    at Object.<anonymous> (swc-test.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'GenericFailure'
}
```

**Comment by dimooze** [comment]
Hello, 

I have a similar problem when using tsx and angle bracket assertion:

```
const { transformSync } = require("@swc/core");
const Visitor = require("@swc/core/Visitor").default;

transformSync(
    `
const fooObj = {
  foo: <const>'foo',
};
`,
    { jsc: { parser: { syntax: 'typescript', tsx: true } }, plugin: (p) => new Visitor().visitProgram(p) }
);
```

```
Error: error: Unexpected token `const`. Expected jsx identifier
 --> <anon>:3:9
  |
3 |   foo: <const>'foo',
  |         ^^^^^



Caused by:
    failed to parse module
    at Compiler.parseSync (node_modules/@swc/core/index.js:72:36)
    at Compiler.transformSync (node_modules/@swc/core/index.js:132:54)
    at transformSync (node_modules/@swc/core/index.js:215:21)
    at Object.<anonymous> (config/babel/testbis.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'GenericFailure'
}
```

**Comment by kdy1** [comment]
@dimooze You can't use type casting syntax in `.tsx` files

**Comment by dimooze** [comment]
Yes ! But i'm currently working on a plugin on a project with `.tsx` and `.ts` files. Should i split files ? With a specific config for those two extensions ?

**Comment by kdy1** [comment]
@dimooze You don't have to specify the config, but you have to split it if you want to use such syntax. It's a typescript spec.

**Comment by dimooze** [comment]
Arff yes i feel dumb 😓 
Thank you for your quick answers !
