### ISSUE TITLE
minifier wasm: time not implemented on this platform

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#1982]
**Describe the bug**

```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:13:9

Stack:

Error
    at module.exports.__wbg_new_59cb74e423758ede (node_modules/.pnpm/@swc+wasm@1.2.69/node_modules/@swc/wasm/wasm.js:183:15)
    at <anonymous>:wasm-function[3177]:0xd643be
    at <anonymous>:wasm-function[8158]:0xf3bf3f
    at <anonymous>:wasm-function[6679]:0xf1b34d
    at <anonymous>:wasm-function[7657]:0xf38756
    at <anonymous>:wasm-function[7599]:0xf37cb3
    at <anonymous>:wasm-function[7673]:0xf38a23
    at <anonymous>:wasm-function[8159]:0xf3bf51
    at <anonymous>:wasm-function[173]:0x3c06bf
    at module.exports.minifySync (node_modules/.pnpm/@swc+wasm@1.2.69/node_modules/@swc/wasm/wasm.js:121:20)


wasm://wasm/040a3cbe:1


RuntimeError: unreachable
    at <anonymous>:wasm-function[6679]:0xf1b369
    at <anonymous>:wasm-function[7657]:0xf38756
    at <anonymous>:wasm-function[7599]:0xf37cb3
    at <anonymous>:wasm-function[7673]:0xf38a23
    at <anonymous>:wasm-function[8159]:0xf3bf51
    at <anonymous>:wasm-function[173]:0x3c06bf
    at module.exports.minifySync (node_modules/.pnpm/@swc+wasm@1.2.69/node_modules/@swc/wasm/wasm.js:121:20)
    at Object.<anonymous> (x.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Input code**

```js
const { minifySync } = require("@swc/wasm");
const fs = require("fs");

const minified = minifySync(
	// react@17.0.1
	fs.readFileSync("./node_modules/react/cjs/react.development.js", "utf8"),
	{
		sourceMap: false,
	}
);
```

**Version**
The version of @swc/wasm: 1.2.69

**Comment by kdy1** [comment]
Thanks for reporting!
I wasn't aware of the fact that time api is not implemented for wasm.
I'm not sure about the timing api, but I'll disable time logging for wasm.
