### ISSUE TITLE
panic: thread '<unnamed>' panicked at 'Infinite loop detected (current pass = 31)'

### ISSUE THREAD

**Issue by marvinhagemeister** [swc-project/swc#2044]
1. Source code (reduced from bigger test case to a minimal failure case)

```js
function createCommonjsModule(fn) {
	return fn();
}
const isFile = config => true;
const pkgBrowserslist = {};
const config = {};
createCommonjsModule(function (module, exports) {
	Object.defineProperty(exports, '__esModule', {
		value: true
	});
});
createCommonjsModule(function (module) {
	module.exports = {
		findConfig: function findConfig(from) {
			var resolved = function (dir) {
				if (2) {
					throw new Error('');
				} else if (pkgBrowserslist) {
					throw new Error('');
				} else if (1) {
					throw new Error('');
				} else if (true) {
					return module.exports.findConfig(null);
				} else if (true) {
					return module.exports.findConfig(null);
				}
			};
			return resolved;
		}
	};
});
createCommonjsModule(function (module, exports) {
	Object.defineProperty(exports, '__esModule', {
		value: true
	});
});
createCommonjsModule(function (module, exports) {
	function _interopRequireDefault(obj) {
		return obj && obj.__esModule ? obj : { default: obj };
	}
	_interopRequireDefault();

	var _node = _interopRequireDefault();
});
createCommonjsModule(function (module, exports) {
	exports.default = null;
	module.exports = exports.default;
});
createCommonjsModule(function (module, exports) {
	exports.default = void 0;
});
var namespace$1 = createCommonjsModule(function (module, exports) {
	exports.default = void 0;

	function _interopRequireDefault(obj) {
		return obj && obj.__esModule ? obj : { default: obj };
	}

	module.exports = exports.default;
});
createCommonjsModule(function (module, exports) {
	exports.default = void 0;

	module.exports = exports.default;
});
createCommonjsModule(function (module, exports) {
	exports.default = void 0;

	exports.default = String;
});
createCommonjsModule(function (module, exports) {
	exports.default = void 0;

	var Pseudo = null;

	exports.default = String;
});

createCommonjsModule(function (module, exports) {
	exports.__esModule = true;
});
createCommonjsModule(function (module, exports) {
	exports.__esModule = true;
});
createCommonjsModule(function (module, exports) {
	exports.__esModule = true;
});
```

2. `.swcrc` file

```json
{
  "jsc": {
    "target": "es2021",
    "minify": {
      "compress": true
    }
  }
}
```

3. Error message gained from `swc --sync <input.js>`
   (--sync is required to get panic message)
   
```bash
thread '<unnamed>' panicked at 'Infinite loop detected (current pass = 31)', ecmascript/minifier/src/compress/mod.rs:229:13
```

4. Backtrace

```bash
stack backtrace:
   0:        0x107009bb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h041e853efbffdfe1
   1:        0x106dd5760 - core::fmt::write::h1cf04d7978b860f9
   2:        0x1070095ac - std::io::Write::write_fmt::hd483526a9eeb723f
   3:        0x107009080 - std::panicking::default_hook::{{closure}}::h7e0f9e42403ff1e9
   4:        0x107008590 - std::panicking::rust_panic_with_hook::hb78de7785bca444b
   5:        0x107025088 - std::panicking::begin_panic_handler::{{closure}}::h722ca64b9350d1cb
   6:        0x107025004 - std::sys_common::backtrace::__rust_end_short_backtrace::h4b32d46cce319137
   7:        0x107024fc0 - _rust_begin_unwind
   8:        0x107d43104 - std::panicking::begin_panic_fmt::hedc9d1ac5a623ed4
   9:        0x1074e7960 - swc_ecma_minifier::compress::Compressor::optimize_unit_repeatedly::h2aed1db86be4f863
  10:        0x107033b58 - swc_ecma_minifier::optimize::h9fd8bbc2800de85b
  11:        0x107030dc0 - <swc::builder::MinifierPass as swc_ecma_visit::VisitMut>::visit_mut_module::hf1897ab611e66522
  12:        0x1072224bc - swc_ecma_visit::fold_program::h1ae67ce37739ce5b
  13:        0x10721d960 - swc::Compiler::process_js_file::h897d9fba3e4ea224
  14:        0x106cde3f0 - napi::async_work::execute::h59d9ce585e070cf1
  15:        0x102b7847c - worker
                               at /Users/marvinhagemeister/.nvm/.cache/src/node-v15.12.0/files/out/../deps/uv/src/threadpool.c:122:5
  16:        0x18734b878 - _pthread_jit_write_protect_np
fatal runtime error: failed to initiate panic, error 5
```

**Comment by marvinhagemeister** [comment]
@kdy1 Thank you so much for the fix 🙌

**Comment by samouri** [comment]
I just tested out swapping `terser` with `swc` for amphtml, and ran into a similar panick:

```bash
thread '<unnamed>' panicked at 'Infinite loop detected (current pass = 31)', ecmascript/minifier/src/compress/mod.rs:225:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```
