### ISSUE TITLE
panic: unknown key "ff"

### ISSUE THREAD

**Issue by bostondv** [swc-project/swc#2102]
The below build script panics when adding the `env` option. Our browserslist is configured with custom stats (below). It appears that the `ff` alias for `firefox` as a browserslist key is causing the failure. Changing `"ff"` to `"firefox"` in our browserslist stats fixes the panic, however `ff` is a valid browserslist key https://github.com/browserslist/browserslist#browsers

1. Source code

Using `@swc/core` as a node script

```
swc.transformFile(filePath, {
    // Some options cannot be specified in .swcrc
    filename: fileName,

    jsc: {
      parser: {
        syntax: 'typescript',
        tsx: true,
        decorators: true
      },
      transform: {
        legacyDecorator: true
      },
      externalHelpers: true,
    },
    env: {
      coreJs: 3,
      path: appRootPath
    }
  })
```

2. `.swcrc` file

None

3. Error message gained from `swc --sync <input.js>`
   (--sync is required to get panic message)

```
thread '<unnamed>' panicked at 'Unknown key: ff', ecmascript/preset-env/src/lib.rs:418:16
stack backtrace:
thread '<unnamed>' panicked at 'Unknown key: ff', ecmascript/preset-env/src/lib.rs:418:16
   0:        0x1112abb53 - _rust_eh_personality
   1:        0x111203cdc - _napi_register_module_v1
   2:       thread '<unnamed>' panicked at 'Unknown key: ff', ecmascript/preset-env/src/lib.rs 0x1112aa62a: - _rust_eh_personality
418:16
   3:        0x1112aadaf - _rust_eh_personality
   4:        0x1112aa361 - _rust_eh_personality
   5:        0x1112c944a - _rust_eh_personality
   6:        0x1112c93c9 - _rust_eh_personality
   7:        0x1112c9385 - _rust_eh_personality
   8:        0x11240bdcf - _rust_eh_personality
   9:        0x111998a4e - _rust_eh_personality
  10:        0x1119945ce - _rust_eh_personality
  11:        0x1113106ee - _rust_eh_personality
  12:        0x1113079ac - _rust_eh_personality
  13:        0x11150e078 - _rust_eh_personality
  14:        0x11150ef9a - _rust_eh_personality
  15:        0x1110dce98 - <unknown>
thread '<unnamed>' panicked at 'Unknown key: ff', ecmascript/preset-env/src/lib.rs:418:16
  16:        0x1009f0bda - _worker
  17:     0x7fff72090109 - __pthread_start
stack backtrace:
fatal runtime error:    0failed to initiate panic, error 5
:        0x1112abb53 - _rust_eh_personality
```

4. Backtrace

(You can get it by invoking swc by setting an environment varaible`SWC_DEBUG` to `1`, invoke swc like `SWC_DEBUG=1 npx swc foo.js` on linux / darwin)

browserslist-stats.json file:

```
{
  "chrome": {
    "27": 0,
    "50": 0,
    "51": 0,
    "55": 0,
    "57": 0,
    "60": 0,
    "61": 0,
    "62": 0,
    "63": 0.01,
    "64": 0,
    "65": 0.03,
    "66": 0,
    "67": 0.04,
    "68": 0,
    "69": 0.01,
    "70": 0.01,
    "71": 0.01,
    "72": 0.01,
    "73": 0.01,
    "74": 0.01,
    "75": 0.03,
    "76": 0.09,
    "77": 0.03,
    "78": 0.02,
    "79": 0.03,
    "80": 0.05,
    "81": 0.04,
    "83": 0.05,
    "84": 0.07,
    "85": 0.08,
    "86": 0.12,
    "87": 0.48,
    "88": 0.46,
    "89": 0.94,
    "90": 11.95,
    "91": 28.13,
    "92": 0.04,
    "93": 0.01,
    "94": 0,
    "99": 0
  },
  "ios_saf": {
    "8": 0,
    "9": 0,
    "10": 0,
    "11": 0.03,
    "12": 0.3,
    "13": 0.62,
    "14": 15.55,
    "15": 0.01
  },
  "safari": {
    "5": 0,
    "8": 0,
    "10": 0,
    "11": 0.14,
    "12": 0.47,
    "13": 1.77,
    "14": 10.09,
    "15": 0.01
  },
  "edge": {
    "15": 0,
    "77": 0,
    "79": 0,
    "80": 0,
    "81": 0,
    "82": 0,
    "83": 0,
    "84": 0,
    "85": 0.01,
    "86": 0.01,
    "87": 0.01,
    "88": 0.02,
    "89": 0.05,
    "90": 1.52,
    "91": 6.24,
    "92": 0.01,
    "93": 0
  },
  "and_chr": {
    "60": 0,
    "61": 0,
    "62": 0,
    "63": 0,
    "64": 0,
    "65": 0,
    "66": 0,
    "67": 0,
    "68": 0,
    "69": 0,
    "70": 0.01,
    "71": 0,
    "72": 0,
    "73": 0,
    "74": 0.02,
    "75": 0,
    "76": 0,
    "77": 0.01,
    "78": 0.01,
    "79": 0.02,
    "80": 0.04,
    "81": 0.05,
    "83": 0.07,
    "84": 0.04,
    "85": 0.04,
    "86": 0.07,
    "87": 0.14,
    "88": 0.12,
    "89": 0.2,
    "90": 1.59,
    "91": 4.07,
    "92": 0,
    "93": 0,
    "99": 0
  },
  "ff": {
    "42": 0,
    "45": 0,
    "47": 0,
    "55": 0,
    "56": 0,
    "57": 0,
    "58": 0,
    "59": 0,
    "60": 0,
    "61": 0,
    "62": 0,
    "63": 0,
    "64": 0,
    "65": 0,
    "66": 0,
    "67": 0,
    "68": 0.01,
    "69": 0,
    "70": 0,
    "71": 0,
    "72": 0.01,
    "73": 0,
    "74": 0,
    "75": 0,
    "76": 0,
    "77": 0.01,
    "78": 0.27,
    "79": 0,
    "80": 0,
    "81": 0.01,
    "82": 0.01,
    "83": 0.01,
    "84": 0.02,
    "85": 0.02,
    "86": 0.03,
    "87": 0.04,
    "88": 1.15,
    "89": 2.44,
    "90": 0.1,
    "91": 0,
    "92": 0,
    "185": 0
  },
  "samsung": {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "7": 0,
    "8": 0,
    "9": 0.01,
    "10": 0,
    "11": 0.02,
    "12": 0.01,
    "13": 0.06,
    "14": 1.07,
    "15": 0
  },
  "android": {
    "30": 0,
    "37": 0,
    "44": 0,
    "46": 0,
    "52": 0,
    "55": 0,
    "58": 0,
    "60": 0,
    "61": 0,
    "62": 0,
    "64": 0,
    "65": 0,
    "66": 0,
    "68": 0,
    "69": 0,
    "70": 0,
    "71": 0,
    "72": 0,
    "73": 0,
    "74": 0,
    "75": 0,
    "76": 0,
    "77": 0,
    "78": 0,
    "79": 0,
    "80": 0,
    "81": 0.01,
    "83": 0.01,
    "84": 0.01,
    "85": 0.01,
    "86": 0.01,
    "87": 0.02,
    "88": 0.02,
    "89": 0.03,
    "90": 0.33,
    "91": 0.91,
    "92": 0,
    "93": 0
  },
  "opera": {
    "47": 0,
    "48": 0,
    "49": 0,
    "53": 0,
    "57": 0,
    "58": 0,
    "61": 0,
    "62": 0,
    "63": 0,
    "64": 0,
    "65": 0,
    "67": 0,
    "68": 0,
    "69": 0,
    "70": 0,
    "71": 0,
    "72": 0,
    "73": 0,
    "74": 0,
    "75": 0.01,
    "76": 0.06,
    "77": 0.04,
    "78": 0
  },
  "and_ff": {
    "57": 0,
    "59": 0,
    "62": 0,
    "63": 0,
    "64": 0,
    "65": 0,
    "66": 0,
    "67": 0,
    "68": 0,
    "74": 0,
    "77": 0,
    "78": 0,
    "79": 0,
    "80": 0,
    "81": 0,
    "82": 0,
    "83": 0,
    "84": 0,
    "85": 0,
    "86": 0,
    "87": 0,
    "88": 0.01,
    "89": 0.03,
    "90": 0,
    "91": 0,
    "92": 0
  }
}
```

**Comment by kdy1** [comment]
Is this still an issue?
If so, how can I reproduce this?

**Comment by kdy1** [comment]
Closing as the author didn't respond
