### ISSUE TITLE
Error: unable to locate global object

### ISSUE THREAD

**Issue by muhibbudins** [swc-project/swc#214]
Hi there,

I found a bug when using SWC on Webpack, for this error i use **node-fetch** like code below :

```js
import fetch from 'node-fetch'

const Test = (data) => {
  return fetch('http://jsonplaceholder.typicode.com/users', {})
    .then(res => res.json())
    .then(res => {
      console.log(res)
    })
}

Test('foo')
```

And then i run `yarn webpack`, after that i run builded code using `node build/bundle.js`. But, i got error like this :

```
/Users/katana/Sites/hello-swc/build/bundle.js:1
(function (exports, require, module, __filename, __dirname) { !function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=1)}([

Error: unable to locate global object
    at /Users/katana/Sites/hello-swc/build/bundle.js:1:1134
    at Object.<anonymous> (/Users/katana/Sites/hello-swc/build/bundle.js:1:1178)
    at n (/Users/katana/Sites/hello-swc/build/bundle.js:1:172)
    at Module.<anonymous> (/Users/katana/Sites/hello-swc/build/bundle.js:1:1332)
    at n (/Users/katana/Sites/hello-swc/build/bundle.js:1:172)
    at /Users/katana/Sites/hello-swc/build/bundle.js:1:964
    at Object.<anonymous> (/Users/katana/Sites/hello-swc/build/bundle.js:1:973)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

---

Owh ya, below is my webpack config. 

```js
const path = require('path')

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          // `.swcrc` can be used to configure swc
          loader: 'swc-loader'
        }
      },
      {
        test: /\.ts$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'swc-loader',
          options: {
            jsc: {
              parser: {
                syntax: 'typescript'
              }
            }
          }
        }
      }
    ]
  },
  stats: {
    colors: true
  },
  devtool: 'source-map'
}
```

Thank you,
Great project btw 👍

**Comment by kdy1** [comment]
It seems like a bug of `node-fetch` or `webpack`. I think webpack is using file for browser instead of file for nodejs.

https://github.com/bitinn/node-fetch/blob/e996bdab73baf996cf2dbf25643c8fe2698c3249/browser.js#L4-L12


See: https://stackoverflow.com/questions/53393363/unable-to-run-script-after-i-run-it-through-webpack-error-unable-to-locate-gl

**Comment by kdy1** [comment]
Fixed with @swc/core@1.0.13.
Note that `swc` is renamed to `@swc/core` and `swc-cli` is renamed to `@swc/cli`.

**Comment by muhibbudins** [comment]
Hi @kdy1,

Sound good! Thanks for the solutions.

**Comment by oksep** [comment]
In case anyone is wondering where to set target: 'node': You have to add it to module.exports in webpack.config.js
