### ISSUE TITLE
TS bracket casts with JSX panics: `assertion failed: (left == right)`

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#2173]
**Describe the bug**

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(BraceExpr)`,
 right: `Some(JSXOpeningTag)`', /Users/niklas/Documents/_dev/_git/parcel/swc/ecmascript/parser/src/parser/expr.rs:85:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ccffcafd55e58f769d4b0efc0064bf65e76998e4/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/ccffcafd55e58f769d4b0efc0064bf65e76998e4/library/core/src/panicking.rs:93:14
   2: core::panicking::assert_failed_inner
             at /rustc/ccffcafd55e58f769d4b0efc0064bf65e76998e4/library/core/src/panicking.rs:175:17
   3: core::panicking::assert_failed
             at /rustc/ccffcafd55e58f769d4b0efc0064bf65e76998e4/library/core/src/panicking.rs:132:5
   4: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr_base::{{closure}}
             at ./ecmascript/parser/src/parser/expr.rs:85:21
   5: swc_ecma_parser::parser::typescript::<impl swc_ecma_parser::parser::Parser<I>>::try_parse_ts
             at ./ecmascript/parser/src/parser/typescript.rs:501:19
   6: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr_base
             at ./ecmascript/parser/src/parser/expr.rs:83:23
   7: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr
             at ./ecmascript/parser/src/parser/expr.rs:69:9
   8: swc_ecma_parser::parser::object::<impl swc_ecma_parser::parser::util::ParseObject<alloc::boxed::Box<swc_ecma_ast::expr::Expr>> for swc_ecma_parser::parser::Parser<I>>::parse_object_prop
             at ./ecmascript/parser/src/parser/object.rs:154:24
   9: swc_ecma_parser::parser::object::<impl swc_ecma_parser::parser::Parser<I>>::parse_object
             at ./ecmascript/parser/src/parser/object.rs:33:24
  10: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_primary_expr
             at ./ecmascript/parser/src/parser/expr.rs:293:28
  11: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_member_expr_or_new_expr
             at ./ecmascript/parser/src/parser/expr.rs:535:19
  12: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_new_expr
             at ./ecmascript/parser/src/parser/expr.rs:546:9
  13: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_lhs_expr
             at ./ecmascript/parser/src/parser/expr.rs:1148:22
  14: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_unary_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:334:20
  15: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_bin_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:13:26
  16: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_cond_expr
             at ./ecmascript/parser/src/parser/expr.rs:194:20
  17: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr_base
             at ./ecmascript/parser/src/parser/expr.rs:129:20
  18: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr
             at ./ecmascript/parser/src/parser/expr.rs:69:9
  19: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_expr_or_spread
             at ./ecmascript/parser/src/parser/expr.rs:598:13
  20: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_args
             at ./ecmascript/parser/src/parser/expr.rs:578:34
  21: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_lhs_expr
             at ./ecmascript/parser/src/parser/expr.rs:1185:24
  22: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_unary_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:334:20
  23: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_bin_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:13:26
  24: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_cond_expr
             at ./ecmascript/parser/src/parser/expr.rs:194:20
  25: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr_base
             at ./ecmascript/parser/src/parser/expr.rs:129:20
  26: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr
             at ./ecmascript/parser/src/parser/expr.rs:69:9
  27: <swc_ecma_parser::parser::Parser<I> as swc_ecma_parser::parser::class_and_fn::FnBodyParser<swc_ecma_ast::expr::BlockStmtOrExpr>>::parse_fn_body_inner
             at ./ecmascript/parser/src/parser/class_and_fn.rs:1361:13
  28: swc_ecma_parser::parser::class_and_fn::<impl swc_ecma_parser::parser::Parser<I>>::parse_fn_body
             at ./ecmascript/parser/src/parser/class_and_fn.rs:1160:9
  29: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_paren_expr_or_arrow_fn
             at ./ecmascript/parser/src/parser/expr.rs:683:41
  30: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_primary_expr
             at ./ecmascript/parser/src/parser/expr.rs:329:28
  31: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_member_expr_or_new_expr
             at ./ecmascript/parser/src/parser/expr.rs:535:19
  32: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_new_expr
             at ./ecmascript/parser/src/parser/expr.rs:546:9
  33: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_lhs_expr
             at ./ecmascript/parser/src/parser/expr.rs:1148:22
  34: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_unary_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:334:20
  35: swc_ecma_parser::parser::expr::ops::<impl swc_ecma_parser::parser::Parser<I>>::parse_bin_expr
             at ./ecmascript/parser/src/parser/expr/ops.rs:13:26
  36: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_cond_expr
             at ./ecmascript/parser/src/parser/expr.rs:194:20
  37: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr_base
             at ./ecmascript/parser/src/parser/expr.rs:129:20
  38: swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_assignment_expr
             at ./ecmascript/parser/src/parser/expr.rs:69:9
  39: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_var_declarator
             at ./ecmascript/parser/src/parser/stmt.rs:775:28
  40: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_var_stmt
             at ./ecmascript/parser/src/parser/stmt.rs:710:24
  41: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_stmt_internal
             at ./ecmascript/parser/src/parser/stmt.rs:259:25
  42: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_stmt_like
             at ./ecmascript/parser/src/parser/stmt.rs:84:9
  43: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_block_body
             at ./ecmascript/parser/src/parser/stmt.rs:28:24
  44: swc_ecma_parser::parser::Parser<I>::parse_module
             at ./ecmascript/parser/src/parser/mod.rs:189:9
  45: usage::parse
             at ./examples/usage.rs:82:11
  46: usage::main
             at ./examples/usage.rs:26:30
  47: core::ops::function::FnOnce::call_once
             at /rustc/ccffcafd55e58f769d4b0efc0064bf65e76998e4/library/core/src/ops/function.rs:227:5
```

**Input code**

```rust
use swc_common::{
    chain, comments::SingleThreadedComments, sync::Lrc, FileName, Globals, Mark, SourceMap,
};
use swc_ecma_ast::Module;
use swc_ecma_codegen::{text_writer::JsWriter, Config, Emitter};
use swc_ecma_parser::{lexer::Lexer, EsConfig, PResult, Parser, StringInput, Syntax, TsConfig};
use swc_ecma_preset_env::preset_env;
use swc_ecma_transforms::{
    compat::reserved_words::reserved_words,
    fixer, helpers, hygiene,
    optimization::simplify::{dead_branch_remover, expr_simplifier},
    react,
    resolver::resolver_with_mark,
};
use swc_ecma_visit::FoldWith;

fn main() {
    let cm = Lrc::<SourceMap>::default();
    let src = r#"
const setAction = (fields) =>
setCurrentAction({
    ...<HeaderAction>getCurrentAction(),
    ...fields
});
"#;
    let (module, comments) = parse(src, "test.js", &cm).unwrap();
    let module = module.fold_with(&mut chain!(
        reserved_words(),
        hygiene(),
        fixer(Some(&comments))
    ));
    let code = emit(&module, &comments, cm);
    println!("{}", code);
}

fn parse(
    code: &str,
    filename: &str,
    cm: &Lrc<SourceMap>,
) -> PResult<(Module, SingleThreadedComments)> {
    let source_file = cm.new_source_file(FileName::Real(filename.into()), code.into());
    let comments = SingleThreadedComments::default();

    let lexer = Lexer::new(
        Syntax::Typescript(TsConfig {
            tsx: true,
            ..Default::default()
        }),
        Default::default(),
        StringInput::from(&*source_file),
        Some(&comments),
    );
    let mut parser = Parser::new_from(lexer);
    match parser.parse_module() {
        Err(err) => Err(err),
        Ok(module) => Ok((module, comments)),
    }
}

fn emit(module: &Module, comments: &SingleThreadedComments, cm: Lrc<SourceMap>) -> String {
    let mut buf = vec![];
    {
        let writer = Box::new(JsWriter::new(cm.clone(), "\n", &mut buf, None));
        let config = Config { minify: false };
        let mut emitter = Emitter {
            cfg: config,
            comments: Some(&comments),
            cm,
            wr: writer,
        };
        emitter.emit_module(&module).unwrap();
    }

    String::from_utf8(buf).unwrap()
}
```

**Current behavior**

On some older version of swc, this resulted in (this should parse fine)
```
@parcel/transformer-js: Unexpected token `HeaderAction`. Expected jsx identifier
  35 |   const setAction = (fields: Partial<HeaderAction>) =>
> 36 |  ...<HeaderAction>getCurrentAction(), ...fields 
})
>    |      ^^^^^^^^^^^^
  37 |
  38 |   _actions([
```

When trying to reproduce this and using the current swc, it instead panics.

**Version**
The version of @swc/core: 97514a754986eaf3a227cab95640327534aa183f

**Context**
https://github.com/parcel-bundler/parcel/issues/6719#issuecomment-907557726

**Comment by kdy1** [comment]
You should specify `tsx` based on the extension of the file.

**Comment by mischnic** [comment]
Yeah, we'll need to figure that out. But it should still not panic?

**Comment by kdy1** [comment]
Oh, you are right.
