### ISSUE TITLE
@swc/jest does not transform files in node_modules in CI environment

### ISSUE THREAD

**Issue by srmagura** [swc-project/swc#2240]
**Describe the bug**
I am using `@swc/jest` to run my tests. There's a TypeScript library (`@interface-technologies/iti-react`) in my `node_modules` that has not been transpiled yet. I've set `transformIgnorePatterns` in `jest.config.js` so that the Jest transformer converts the library's TypeScript code to normal JavaScript using CommonJS modules.

Everything works when I run locally. But when my tests run in CI (Azure Pipelines, Microsoft-hosted Windows build agent), I get:
```
➤ YN0000: FAIL src/__tests__/Pages/Home/LogIn.test.tsx
➤ YN0000:     By default "node_modules" folder is ignored by transformers.
➤ YN0000: 
➤ YN0000:     Here's what you can do:
➤ YN0000:      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
➤ YN0000:      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
➤ YN0000:      • If you need a custom transformation specify a "transform" option in your config.
➤ YN0000:      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
➤ YN0000: 
➤ YN0000:     You'll find more details and examples of these config options in the docs:
➤ YN0000:     https://jestjs.io/docs/configuration
➤ YN0000:     For information about custom transformations, see:
➤ YN0000:     https://jestjs.io/docs/code-transformation
➤ YN0000: 
➤ YN0000:     Details:
➤ YN0000: 
➤ YN0000:     D:\a\1\s\Source\node_modules\@interface-technologies\iti-react\src\index.ts:1
➤ YN0000:     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from '@interface-technologies/iti-react-core';
➤ YN0000:                                                                                       ^^^^^^
➤ YN0000: 
➤ YN0000:     SyntaxError: Unexpected token 'export'
➤ YN0000: 
➤ YN0000:       4 |     FormCheck,
➤ YN0000:       5 |     FormGroup,
➤ YN0000:     > 6 |     nullToUndefined,
➤ YN0000:         |                 ^
➤ YN0000:       7 |     SubmitButton,
➤ YN0000:       8 |     useFieldValidity,
➤ YN0000:       9 |     ValidatedInput,
➤ YN0000: 
➤ YN0000:       at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1479:14)
➤ YN0000:       at Object.<anonymous> (src/Pages/Home/LogIn.tsx:6:17)
```
You can see that the `export` statement is still there. The module has not been converted to CommonJS.

I have re-run the pipeline multiple times with the same result each time. I checked and the build agent is running Node 14, same as my local environment.

**Input code**
I tried to create a minimal repro but the tests succeeded in CI. If you are interested in pursuing this, I can privately send my application's whole code. Or I could start ripping out pieces of my application until the error goes away, which may lead us to the root cause.

**Config**

```json
{
   "jsc": {
      "parser": {
         "syntax": "typescript",
         "tsx": true,
         "dynamicImport": true
      },
      "target": "es2021"
   },
   "module": {
      "type": "commonjs"
   }
}
```

`jest.config.js`
```js
module.exports = {
    testEnvironment: 'jsdom',
    testTimeout: 15000,

    modulePaths: ['<rootDir>/src'],
    transformIgnorePatterns: ['node_modules/(?!@interface-technologies)'],
    setupFiles: ['./src/__tests__/__helpers__/jest.setup.ts'],

    transform: { "^.+\\.(t|j)sx?$": ["@swc/jest"], },

    // ignore files that don't have test.ts or test.tsx extension (.e.g. __helpers__)
    testMatch: ['**/__tests__/**/*.test.ts?(x)'],
}
```

**Expected behavior**
The `@interface-technologies/iti-react` code should be transpiled to a CommonJS module.

**Version**
The version of @swc/core: 1.2.85
The version of @swc/jest: 0.2.3

**Additional context**
I have another project that uses the same Jest config and the same library (`@interface-technologies/iti-react`), and its tests succeed in Azure Pipelines.

These same tests with the same Jest config were working with `babel-jest` and `@sucrase/jest-plugin`.

I understand this is probably not actionable because no minimal repro but I figured I would report it anyway.

**Comment by srmagura** [comment]
Closing in favor of #2246.
