### ISSUE TITLE
Possible to use swc with / for eslint?

### ISSUE THREAD

**Issue by rvolgers** [swc-project/swc#246]
`eslint` is a big part of our largest project's build times and it's currently configured to use babel-parser.

To get rid of babel entirely it'd be nice to be able to get eslint to use swc somehow:
https://eslint.org/docs/user-guide/configuring

On an unrelated note, with swc 1.0.21 the project finally builds and seems to mostly work (I haven't looked to closely yet). Thank you for your hard work and the quick responses to bug reports.

**Comment by kdy1** [comment]
It's blocked by #230 (because we can't emit esprima-compatible ast)

**Comment by ForsakenHarmony** [comment]
Would be pretty nice if the parser could be turned into a standalone project you can use in other rust projects 👀

**Comment by kdy1** [comment]
@ForsakenHarmony Parser is uploaded on crates.io, and it can be built with stable rust.

**Comment by kapouer** [comment]
I just tried but it seems eslint is expecting something a little bit different than the format returned by
```
exports.parse = function(str, opts) {
  return require('@swc/core').parseSync(str.toString(), {});
};
```

To test with eslint, just create a `node_modules/@swc/parser/index.js` file containing above snippet,
then put this into your project's `.eslintrc`:
```
{"parser": "@swc/parser"}
```

Then to debug,
```
DEBUG=eslint:* eslint somefile.js
```

For me it returns (usling @swc/core 1.1.2 and eslint 6.7.2
```
  eslint:linter TypeError: Cannot read property '__define' of null
    at PatternVisitor.visitPattern [as callback] (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/referencer.js:348:33)
    at PatternVisitor.Identifier (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/pattern-visitor.js:66:14)
    at PatternVisitor.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/esrecurse/esrecurse.js:104:34)
    at traverseIdentifierInPattern (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/referencer.js:53:13)
    at Referencer.visitPattern (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/referencer.js:168:9)
    at Referencer.visitVariableDeclaration (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/referencer.js:347:14)
    at Referencer.VariableDeclaration (/usr/local/lib/node_modules/eslint/node_modules/eslint-scope/lib/referencer.js:534:18)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/esrecurse/esrecurse.js:107:14) +7ms
  eslint:linter Generating fixed text for /home/dev/Software/github/postinstall-js/index.js (pass 1) +0ms
  eslint:source-code-fixer Applying fixes +0ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
  eslint:file-enumerator Complete iterating files: ["index.js"] +43ms
  eslint:cli-engine Linting complete in: 44ms +9ms

/home/dev/Software/github/postinstall-js/index.js
  0:0  error  Parsing error: Cannot read property '__define' of null

```

**Comment by pbadenski** [comment]
@kdy1 I'm a bit confused about the status of this, hope you can clarify. (As you might be guessing I'm also super excited about swc use with eslint because of speed).

A comment above (https://github.com/swc-project/swc/issues/246#issuecomment-465403756) is mentioning this having been blocked by #230. That issue is closed and merged. Considering the comment above "AST is missing the tokens array." I'm guessing there is more missing?

**Comment by kdy1** [comment]
It still requires lots of work

**Comment by axyz** [comment]
If I got it right #230 would allow to have the needed AST format as an output.

Would something like https://github.com/babel/babel-eslint/tree/master/lib/babylon-to-espree be an intermediate solution? Adapting it to work with the output from swc? Or is there some issue with the format that would make that solution used by babel impossible with swc?

**Comment by kdy1** [comment]
It's possible, but I'm not sure if it worths

**Comment by axyz** [comment]
Can you elaborate more? 

Do you mean that with #274 it is now natively possible to use swc as a eslint (espree) parser? And if not, what is missing to be done?

or do you mean that converting the format in js as it is done with babel is "possible, but not worth it"? Would that be too much work for a possibly small speed improvement?

In general I think this is a topic of interest to speed up eslint end if the remaining work to be done is clear maybe easier to get it contributed.

**Comment by kdy1** [comment]
> Do you mean that with #274 it is now natively possible to use swc as a eslint (espree) parser? And if not, what is missing to be done?

No, because eslint does not use babel ast.
It can be used if something like https://github.com/babel/babel-eslint/tree/master/lib/babylon-to-espree is used.

swc-to-espree is not done.

> or do you mean that converting the format in js as it is done with babel is "possible, but not worth it"? Would that be too much work for a possibly small speed improvement?

Is eslint slow because of the parser?
I know parsing in javsacript is very slow, but optimizations have only meaning if it was the bottleneck.

Note: It can be a huge difference if eslint custom parser api supports asynchronous parser. If it's the case, performance will be improved a lot even if the bottleneck wasn't the parser.

**Comment by kdy1** [comment]
I started a discussion on eslint about asynchronous parser api.
https://github.com/eslint/eslint/discussions/14733

**Comment by pbadenski** [comment]
It takes over 90 seconds to parse our project on my Mac to lint our project. Here's a screenshot of a CPU profile - hope it helps.

<img width="993" alt="Screenshot 2021-06-22 at 15 40 38" src="https://user-images.githubusercontent.com/68713/122945587-94bacc80-d370-11eb-9381-5c92363b6a44.png">

**Comment by kdy1** [comment]
It may worth then, but I expect conversion of swc ast -> babel ast -> espree ast to be slow.
Need some profiling I guess.

**Comment by extroonie** [comment]
Is there some insight on this? Is there a working solution that could make ESLint work with SWC yet?

**Comment by kdy1** [comment]
@extroonie swc has code to produce ESTree AST/ acorn AST, but it's not exposed to js world currently. It will be nice if you can patch it to expose it.

**Comment by extroonie** [comment]
@kdy1 sorry but I don't quite get that. What do you mean by patching it? Could you walk me through it please?

**Comment by kdy1** [comment]
@extroonie I mean adding a method that is callable from js world, like https://github.com/swc-project/swc/blob/a4e93eb2dff0614e7a39c4301c84654412cf68dc/crates/node/src/transform.rs#L140-L157

**Comment by extroonie** [comment]
@kdy1 thanks. Just want to double-check, the problem I'm having with ESLint and SWC is that some of the code with decorators and other ECMAScript proposals are throwing parser errors with ESLint. Now, I'm not sure whether SWC or ESLint has to deal with it.

**Comment by kdy1** [comment]
You need to patch both

**Comment by manuschillerdev** [comment]
> @extroonie swc has code to produce ESTree AST/ acorn AST, but it's not exposed to js world currently. It will be nice if you can patch it to expose it.

@kdy1 I'd love to give it a shot!

Which methods of `swc_estree_compat` would you expose for that?

**Comment by kdy1** [comment]
@manuschillerdev There's `babelify()`

**Comment by SrShark** [comment]
In my case, I just have deleted the attribute `"parser": "@babel/eslint-parser",` in the `.eslintrc` config fie.

Then I set up the following config in vscode.

```json
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "[javascript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
```

It works well for me.

**Comment by doox911-opensource** [comment]
How are things going?

**Comment by matheusmichels** [comment]
> @Extroonie swc has code to produce ESTree AST/ acorn AST, but it's not exposed to js world currently. It will be nice if you can patch it to expose it.

Hey everyone! Is anyone looking into this? I see the issue has been stale for a while and was wondering if we already have it exposed to JS? Really excited about the idea of moving off of @typescript-eslint/parser (as this is the main bottleneck of my current eslint code) to SWC!

**Comment by matheusmichels** [comment]
> @Extroonie swc has code to produce ESTree AST/ acorn AST, but it's not exposed to js world currently. It will be nice if you can patch it to expose it.

Hey everyone! Is anyone still looking into this? I see the issue has been stale for a while and was wondering if we already have it exposed in JS? Really excited about the idea of moving off of @typescript-eslint/parser (as this is the main bottleneck of my current eslint setup) to SWC!

**Comment by kdy1** [comment]
Nope. The linter should be written in Rust to make it performant enough.

**Comment by MidoAhmed** [comment]
Up

**Comment by webbertakken** [comment]
There's also [Oxlint](https://oxc.rs/docs/guide/usage/linter) now, which is Rust based and seems to be gaining a fair bit of traction.

**Comment by joshcartme** [comment]
@kdy1 would you be open to something like adding `ast_format` to `ParseOptions`, https://github.com/swc-project/swc/blob/dba23f5a72d26b3b62fbafe2d8a65c69c3642669/crates/swc/src/config/mod.rs#L114-L125

It would default to `"swc"` and would also accept `"babel"`.  If it was `babel` somewhere around where the parsed AST is strinigifed, e.g.: https://github.com/swc-project/swc/blob/dba23f5a72d26b3b62fbafe2d8a65c69c3642669/bindings/binding_core_node/src/parse.rs#L76
it would go through `babelify` like in this test
https://github.com/swc-project/swc/blob/dba23f5a72d26b3b62fbafe2d8a65c69c3642669/crates/swc_estree_compat/tests/convert.rs#L159

It could be piped through the bindings such that when using the various `parse*` you could opt into the `babelify` treatment.

edit: and for what it's worth, I'm interested in this because we have some in-house (not eslint) tooling that operates on a babel ast

**Comment by kdy1** [comment]
@joshcartme Do you have a concrete use case for it? I'm going to align the AST format of SWC to babel anyway, but I want to hear about the concrete usecases.

**Comment by joshcartme** [comment]
@kdy1 we have an internal tool that right now does something like (pseudo code):
```
import { parse } from '@babel/parser'
export function getAst(theFile) {
    return parse(theFile);
}
```
And then allows other functions to calculate various metrics based on the AST.  We use those metrics to see if PRs are making code quality (quality subjectively based on the criteria we have decided) better or worse.  Things like counting `@ts-ignore` comments or the number of experiments in a file.  It's slow and one thing we've thought about is getting rid of babel.

**Comment by alexander-akait** [comment]
@kdy1 

> @joshcartme Do you have a concrete use case for it? I'm going to align the AST format of SWC to babel anyway, but I want to hear about the concrete usecases.

Align to [`estree`](https://github.com/estree/estree) allows to do great things, things:
- using swc parser in tools like eslint/rollup/webpack/prettier/etc without hacks and problems
- swc is already using inside nodejs for typescript support, so if we will comply with the `estree` specification (for basic JS nodes, excluding ts/jsx/etc), we can ask node developers to add built-in JS parser and resuse it in tools, because nodejs is already compiled when you are installing it we will get good performance improvements

There are more things there it can be used, just top of them
