### ISSUE TITLE
JS parse error: `[code = 1] = []`

### ISSUE THREAD

**Issue by stefanpenner** [swc-project/swc#260]
parsing:

```js
[code = 1] = []
```

via

```js
require('@swc/core').transformSync('[a = 1] =[]');
```

yields:

```
internal error in Neon module: not yet implemented: assignment pattern Assign(AssignPat { span: Span { lo: BytePos(5194308), hi: BytePos(5194334), ctxt: #0 }, left: Ident(Ident { sym: code, span: Span { lo: BytePos(5194308), hi: BytePos(5194312), ctxt: #30290 }, type_ann: None, optional: false }), right: Member(MemberExpr { span: Span { lo: BytePos(5194325), hi: BytePos(5194334), ctxt: #0 }, obj: Expr(Ident(Ident { sym: httpStatus, span: Span { lo: BytePos(5194315), hi: BytePos(5194325), ctxt: #30284 }, type_ann: None, optional: false })), prop: Ident(Ident { sym: S_200_OK, span: Span { lo: BytePos(5194326), hi: BytePos(5194334), ctxt: #0 }, type_ann: None, optional: false }), computed: false }), type_ann: None })

Error: internal error in Neon module: not yet implemented: assignment pattern Assign(AssignPat { span: Span { lo: BytePos(5194308), hi: BytePos(5194334), ctxt: #0 }, left: Ident(Ident { sym: code, span: Span { lo: BytePos(5194308), hi: BytePos(5194312), ctxt: #30290 }, type_ann: None, optional: false }), right: Member(MemberExpr { span: Span { lo: BytePos(5194325), hi: BytePos(5194334), ctxt: #0 }, obj: Expr(Ident(Ident { sym: httpStatus, span: Span { lo: BytePos(5194315), hi: BytePos(5194325), ctxt: #30284 }, type_ann: None, optional: false })), prop: Ident(Ident { sym: S_200_OK, span: Span { lo: BytePos(5194326), hi: BytePos(5194334), ctxt: #0 }, type_ann: None, optional: false }), computed: false }), type_ann: None })
    at Object.transformSync (/Users/spenner/l/voyager-web_trunk/node_modules/@swc/core/lib/index.js:41:39)
    at SWC.processString (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/index.js:45:26)
    at resolve (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/default.js:10:19)
    at initializePromise (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:995:33)
    at Object.processString (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/strategies/default.js:9:18)
    at Processor.processString (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:353:16)
    at initializePromise (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:995:33)
    at invoke (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:352:10)
    at SWC.Filter.processFile (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:371:16)
    at Promise.resolve.then (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/broccoli-persistent-filter/index.js:337:21)
    at tryCatcher (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/spenner/l/voyager-web_trunk/node_modules/broccoli-babel-transpiler/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

versions of stuff:
 * @swc/helpers@0.2.0
 * node 10.9.0

**Comment by stefanpenner** [comment]
trying to come up with a reduced reproduction.

**Comment by stefanpenner** [comment]
the offending code is:

`[code = 1] = Array.from([])`
