### ISSUE TITLE
v. 1.2.120 - /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by yusuphgammut** [swc-project/swc#3198]
### Describe the bug

I've created a custom build using webpack and swc. When the build runs the jest script on Jenkins I get the following error.

```
+ npm run test
> interconnect-monkey-frontend@0.1.0 test /jenkins
> jest

Error: Can not load bindings, file: /jenkins/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node existed but error occurred while require it: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /jenkins/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node) 
file: /jenkins/node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node existed but error occurred while require it: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory 
Installed packages: [core-linux-x64-gnu, core-linux-x64-musl]
    at Object.loadBinding (/jenkins/node_modules/@node-rs/helper/lib/loader.js:50:11)
    at Object.<anonymous> (/jenkins/node_modules/@swc/core/index.js:40:92)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/jenkins/node_modules/@swc/jest/index.js:39:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myrepo@0.1.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myrepo@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I've seen that this error might be related to [issue 1430](https://github.com/swc-project/swc/issues/1430) but since that one is solved, I'm a bit lost on how can I address mine.

Any guidance on this is appreciated.

### Config

```javascript
// This object is imported in webpack and added to the swc loader options.
module.exports = {
  jsc: {
    // Target ECMAScript version to transpile the code to. This should be the
    // same as the target option in the Typescript configuration to avoid
    // mismatches between type checking and the desired output code.
    target: "es2016",
    // Parser options.
    parser: {
      // Specifies the parser to use. Only two options are available:
      // "typescript" and "ecmascript".
      syntax: "typescript",
      // Support for dynamic imports.
      dynamicImport: true,
      // Support for JSX.
      tsx: true,
    },
    // Transformation options.
    transform: {
      // React specific transformation options.
      react: {
        pragma: "React.createElement",
        pragmaFrag: "React.Fragment",
        // Throw an error if an XML namespaced tag name is used. For example:
        // <f:image />
        // JSX spec allows this, but React still doesn't support it.
        throwIfNamespace: true,
        // Use "Object.assign()" instead of "_extends". Defaults to false.
        useBuiltins: true,
      },
    },
  },
};
```

### Expected behavior

Jenkins job without error.

### Actual behavior

Jenkins job has the above error.

### Version

1.2.120

### Additional context

 I'm using Node 14 in Jenkins.

The job scripts are the following:

```
npm run clean-all
npm i
npm run test
npm run build
assets-publish2 --private ${PWD}/dist
```

**Comment by kdy1** [comment]
Please post your os info and glibc version

**Comment by bdellegrazie** [comment]
@kdy1 I have the identical issue and am running on CentOS 7 which only has GLIBC 2.17.
I found a related note here that might help: https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms  (Note 8 down the bottom)
> The Enterprise Linux devtoolset-8 allows us to compile binaries with GCC 8 but linked to the glibc and libstdc++ versions of the host platforms (CentOS 7 / RHEL 7). Therefore, binaries produced on these systems are compatible with glibc >= 2.17 and libstdc++ >= 6.0.20 (GLIBCXX_3.4.20). These are available on distributions natively supporting GCC 4.9, such as Ubuntu 14.04 and Debian 8

**Comment by yusuphgammut** [comment]
The OS is CentOS 6. However, I was unable to get the glibc version. It's running in a machine that I do not control.

**Comment by claytonfbell** [comment]
I have this error also with Node 14 on CentOS 7 with Jenkins, and I also don't control the build environment.

```
/lib64/libc.so.6: version `GLIBC_2.18' not found
```

**Comment by claytonfbell** [comment]
Upgrading to the new `v1.2.133` resolved the error for me on CentOS 7.
