### ISSUE TITLE
@swc/core/native/index.node: undefined symbol

### ISSUE THREAD

**Issue by marianobianchi** [swc-project/swc#329]
When I run webpack to build dev or production bundles everything works fine. But when I run webpack-dev-server I'm getting this error.

I don't know what the problem is. The packages versions are:

"@swc/core": "^1.0.35",
"swc-loader": "^0.1.4",
"webpack": "^4.29.6",
"webpack-cli": "^3.2.3",
"webpack-dev-server": "^3.2.1"

My main.js file has just a console.log("hello world").

**Comment by kdy1** [comment]
What is your os and node js version?

**Comment by marianobianchi** [comment]
I'm on Ubuntu 18.04.2 and using node v10.15.3

**Comment by kdy1** [comment]
Can you give me more detailed error message?
I think error message is in form `Undefined symbol: xxxxxx`

**Comment by marianobianchi** [comment]
The complete error message is:

```
[./public/js/index.js] 1.05 KiB {main} [not cacheable] [built] [failed] [1 error]                                                                                        
[./public/js/more.js] 1.05 KiB {secondary} [not cacheable] [built] [failed] [1 error]                                                                                    
    + 13 hidden modules                                                                                                                                                  
                                                                                                                                                                         
ERROR in ./public/js/index.js                                                                                                                                            
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: <PROJECT_ABSOLUTE_PATH>/node_modules/@swc/core/native/index.node: undefined symbol: _ZN2v88Function3NewENS_5LocalINS_7$
ontextEEEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS1_IS5_EEiNS_19ConstructorBehaviorE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (<PROJECT_ABSOLUTE_PATH>/node_modules/@swc/core/lib/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9000 ./public/js/index.js main[1]

ERROR in ./public/js/more.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: <PROJECT_ABSOLUTE_PATH>/node_modules/@swc/core/native/index.node: undefined symbol: _ZN2v88Function3NewENS_5LocalINS_7$
ontextEEEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS1_IS5_EEiNS_19ConstructorBehaviorE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (<PROJECT_ABSOLUTE_PATH>/node_modules/@swc/core/lib/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9000 ./public/js/more.js secondary[1]
```

**Comment by marianobianchi** [comment]
Well, this is strange. I updated to 1.0.38 and it start working. Then, I tried to see which version was the one that fixed the problem. I installed 1.0.36 and it worked. Then, I went back to 1.0.35 to verify the problem was there and it is not failing either. So I don't know what the problem was...
