### ISSUE TITLE
REGRESSION: panic when private property is not defined in constructor

### ISSUE THREAD

**Issue by edwincoronado** [swc-project/swc#3599]
### Describe the bug

As part of some testing, when going through the [test262 suite](https://github.com/tc39/test262) and most specifically test case [privatename-not-valid-earlyerr-script-1.js](https://github.com/tc39/test262/blob/main/test/language/statements/class/elements/privatename-not-valid-earlyerr-script-1.js), SWC is crashing with the following error (Detailed log when using `RUST_BACKTRACE=1 SWC_DEBUG=1 npx swc --sync <file>`):

```log
Panic: PanicInfo { payload: Any { .. }, message: Some(Private name #x is not defined.), location: Location { file: "crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs", line: 50, col: 9 } }
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: _rust_eh_personality
   4: _rust_eh_personality
   5: _rust_eh_personality
   6: _rust_eh_personality
   7: _wasmer_vm_f64_nearest
   8: _rust_eh_personality
   9: _rust_eh_personality
  10: _rust_eh_personality
  11: _rust_eh_personality
  12: _rust_eh_personality
  13: _rust_eh_personality
  14: _rust_eh_personality
  15: _rust_eh_personality
  16: _rust_eh_personality
  17: <unknown>
  18: __ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  19: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  20: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  21: __ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE

failed to handle: Private name #x is not defined.

Stack backtrace:
   0: _rust_eh_personality
   1: _wasmer_vm_f64_nearest
   2: <unknown>
   3: __ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
   4: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
   5: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
   6: __ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (/Users/edwin.coronado/git/swc-tester/node_modules/@swc/cli/lib/swc/util.js:115:15)
    at files (/Users/edwin.coronado/git/swc-tester/node_modules/@swc/cli/lib/swc/file.js:175:18)
    at async _default (/Users/edwin.coronado/git/swc-tester/node_modules/@swc/cli/lib/swc/file.js:194:9)
```

It seems that this was working up to v.1.2.136 and broke starting from v1.2.137.

### Input code

```typescript
class C {
  constructor() {
    this.#x;
  }
}
```

### Config

```json
{
  "jsc": {
    "target": "es5",
    "parser": {
      "syntax": "ecmascript"
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.141&code=H4sIAAAAAAAAA0vOSSwuVnBWqOZSUEjOzysuKSpNLskv0tAEiygolGRkFuspV1gDObVctVwA%2Fa2Cti8AAAA%3D&config=H4sIAAAAAAAAA0WOSwoDMQiG7%2BI6225yhx5CUmfIkBfqQEPI3RvbQFfq%2F%2FhwwCUB%2FICGLMS2SS%2BKb%2FBAIaMEjk3BrdiSlG%2BaDhT5JLWEPJaVahX6mQ5yLPHoxgk1NyYR8AcmMQvLmWifc3Fyfd0mDNDe1rRKruUSmH%2FQLkd57vT3iQ%2BfOTFluAAAAA%3D%3D

### Expected behavior

Proper error should be logged and no panic should occurr.

### Version

v1.2.141

**Comment by Austaras** [comment]
@kdy1 could you provide some doc about how to use error handler?

**Comment by kdy1** [comment]
@Austaras Of course, I'll add the documentation to the `Handler` type.
