### ISSUE TITLE
jest.spyOn does not work when compared ts-jest

### ISSUE THREAD

**Issue by Lycolia** [swc-project/swc#3843]
## Problem

- Doesn't work test when another function is called inside function.
- But this works with ts-jest.
- I understand that can do the same by injecting it as a callback function.

### index.ts

```ts
export const child = () => {
  console.log('Hello World!');
};

export const callChild = () => {
  child();
};
```

### index.spec.ts

```ts
import * as index from '.';

describe('index', () => {
  it('called', () => {
    const spiedChild = jest.spyOn(index, 'child');
    index.callChild();

    expect(spiedChild).toHaveBeenCalled();
  });
});
```

#### jest.config.js

```js
module.exports = {
  clearMocks: true,
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  preset: 'ts-jest',
  clearMocks: true,
  testEnvironment: 'node',
  roots: ['<rootDir>/src/'],
  moduleFileExtensions: ['ts', 'js'],
  collectCoverageFrom: ['src/**/*.{ts,js}'],
  testPathIgnorePatterns: ['<rootDir>[/\\\\](node_modules|dist)[/\\\\]'],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  silent: false,
};
```

#### Result

```
> jest

  console.log
    Hello World!

      at child (src/index.ts:4:11)

 PASS  src/index.spec.ts
  index
    √ called (29 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.603 s, estimated 3 s
Ran all test suites.
```

#### jest.swc.config.js

```js
module.exports = {
  clearMocks: true,
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest'],
  },
  clearMocks: true,
  testEnvironment: 'node',
  roots: ['<rootDir>/src/'],
  moduleFileExtensions: ['ts', 'js'],
  collectCoverageFrom: ['src/**/*.{ts,js}'],
  testPathIgnorePatterns: ['<rootDir>[/\\\\](node_modules|dist)[/\\\\]'],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  silent: false,
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
};
```

#### Result

```
> jest -c jest.swc.config.js

  console.log
    Hello World!

      at child (src/index.ts:7:13)

 FAIL  src/index.spec.ts
  index
    × called (22 ms)

  ● index › called

    expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0



      at Object.<anonymous> (src/index.spec.ts:30:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.408 s, estimated 1 s
Ran all test suites.
```

**Comment by Austaras** [comment]
I have runned a local test on my machine and can confirm ts-jest could work fine.

However, if I use babel and `babel/preset-typescript` to transform source code, or use native esm as tsc output result(which involves lots of manual config), tests would fail. So I suggest not to rely on specific implmentation of compiler

**Comment by kdy1** [comment]
If native esm mode fails, `jest.spyOne` working with ts-jest is simply a bug of `tsc`.
Closing as swc is doing the correct thing.

**Comment by ctsstc** [comment]
Kind of confused what the resolution to this issue is exactly.

Tried what @develra  mentioned like so:

```
import * as Router from 'next/router';

jest.mock('Router', () => {
  const actualModule = jest.requireActual('next/router');
  return {
    __esModule: true,
    ...actualModule,
  };
});
```

But then I get this error:

```
Cannot find module 'Router' from 'test-file.test.tsx'
```
