### ISSUE TITLE
swc.bundle() throws error: unknown variant `development`

### ISSUE THREAD

**Issue by nolanlawson** [swc-project/swc#3908]
### Describe the bug

Here is [a minimal repro](https://gist.github.com/nolanlawson/e85ac3faafde7ae13872025afa1fe37d).

Here is the code that throws the error:

```js
const swc = require('@swc/core')
const bundleResult = await swc.bundle({
  mode: 'development',
  entry: './index.js',
})
```

### Input code

```typescript
let exported
if (process.env.NODE_ENV === 'development') {
  exported = 'development'
} else {
  exported = 'production'
}

export default exported
```

### Config

```json
N/A
```

### Expected behavior

The output code should be:

```js
var exported;
exported = 'development';
export { exported as default };
```

### Actual behavior

An error is thrown:

```
Error: Failed to deserialize buffer as node::bundle::StaticConfigItem
JSON: {"mode":"development","entry":"./index.js","module":{"type":"esm"}}

Caused by:
    unknown variant `development`, there are no variants at line 1 column 67
    at Compiler.<anonymous> (/Users/nlawson/workspace/repro-dev-mode-spack/node_modules/@swc/core/index.js:182:29)
    at Generator.next (<anonymous>)                                                                                                    
    at fulfilled (/Users/nlawson/workspace/repro-dev-mode-spack/node_modules/@swc/core/index.js:15:58) {
  code: 'GenericFailure'
}
```

### Version

1.2.151

### Additional context

When changing `mode` to `'production'`, it compiles correctly with no error:

```js
var exported;
exported = 'production';
export { exported as default };
```

**Comment by kdy1** [comment]
This is not a bug, although api will be changed in v2.
