### ISSUE TITLE
can not transpile dependence modules in a entry js file

### ISSUE THREAD

**Issue by alanchenchen** [swc-project/swc#395]
@swc/core version : 1.0.42
node version: 10.15.3

Hi! I found a problem that when i transpile an entry js file with @swc/core, it always throws an error . It seems that swc coud not transpile the dependeces. For instance,
```js
  // entry.js
 import Test from './moduleA.js'

 @Test('0.0.1')
 class Demo {
   constructor() {
      this.author = 'alan'
   }
 }
```
```js
// moduleA.js

// a decorator
 const Test = (version) => {
  return (target) => {
    target.version = version
 }
}

export default Test
```

when i use the @swc/core api to transform codes, it throws an error about not founding module and decorator syntax error of moduleA.js

well, may i transpile dependece module like babel?

**Comment by kdy1** [comment]
Please upload your swcrc file and error message

**Comment by alanchenchen** [comment]
Here are the swcrc file configs and error message:

```js
// swcrc config
{
"jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": false,
            "dynamicImport": true,
            "numericSeparator": false,
            "classPrivateProperty": false,
            "privateMethod": false,
            "classProperty": true,
            "functionBind": false,
            "decorators": true,
            "decoratorsBeforeExport": false
        }, 
        "target": "es2015",
    },
    "module": {
        // You can specify "commonjs", "amd", "umd"
        "type": "commonjs",
        "strict": false,
        "strictMode": true,
        "lazy": false,
        "noInterop": true
    },
    "minify": true,
}

// error message
D:\VS Code Files\swc\a.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

As i use the @swc/core api to make a development tool, so i use the `swc.transformFile()` function and put the returned code to nodejs vm module.

**Comment by kdy1** [comment]
@alanchenchen swc does not transpile dependencies by default (at this time). You should transcompile each files by yourself.

BTW, I don't know why does 

`(function (exports, require, module, __filename, __dirname) {`

is appended. It seems like code added by your tool, is this correct?
