### ISSUE TITLE
Source maps error on static class methods

### ISSUE THREAD

**Issue by guybedford** [swc-project/swc#4006]
### Describe the bug

Running the following command:

```
swc src/app.ts -o lib/app.js --no-swcrc --source-maps -C jsc.target=es2019 -C jsc.parser.syntax=typescript
```

I get a failure with this message in the console:

```
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
    at SourceMapGenerator._validateMapping (C:\Users\Guy\Projects\app\node_modules\source-map\lib\source-map-generator.js:271:15)
    at SourceMapGenerator.addMapping (C:\Users\Guy\Projects\app\node_modules\source-map\lib\source-map-generator.js:107:12)
    at C:\Users\Guy\Projects\app\node_modules\@swc\cli\lib\swc\file.js:54:25       
    at Array.<anonymous> (C:\Users\Guy\Projects\app\node_modules\source-map\lib\source-map-consumer.js:382:19)
    at mapping_callback (C:\Users\Guy\Projects\app\node_modules\source-map\lib\wasm.js:64:52)
    at wasm://wasm/0002f8d6:wasm-function[30]:0x3cac
    at C:\Users\Guy\Projects\app\node_modules\source-map\lib\source-map-consumer.js:387:30
    at Object.withMappingCallback (C:\Users\Guy\Projects\app\node_modules\source-map\lib\wasm.js:95:11)
    at BasicSourceMapConsumer.eachMapping (C:\Users\Guy\Projects\app\node_modules\source-map\lib\source-map-consumer.js:371:16)
    at concatResults (C:\Users\Guy\Projects\app\node_modules\@swc\cli\lib\swc\file.js:52:26)
```

This seems to happen specifically for static class properties per the code example below.

### Input code

```typescript
import {html, css, LitElement} from 'lit';

export class App extends LitElement {
  name: string;

  static styles = css`p { color: blue }`;

  static properties = {
    name: { type: String },
  };

  constructor() {
    super();
    this.name = 'Somebody';
  }

  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}
customElements.define('app', App);
```

### Config

```json
<none>
```

### Expected behavior

Should compile with correct source maps.

### Version

CLI 0.1.55, Core 1.2.154

**Comment by kdy1** [comment]
I'll work on this.
I always wanted a way to automatically validate sourcemaps

**Comment by kdy1** [comment]
How did you get

```
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

```

? This is required to fix this issue, as the sourcemap works well with visualizers

**Comment by guybedford** [comment]
It only happens for the exact source being transformed, with the TypeScript static class methods. Did you try with the exact same input?

**Comment by kdy1** [comment]
I didn't. Does `swc` cli fails with it?

**Comment by guybedford** [comment]
Yes this is with the CLI not the API.
