### ISSUE TITLE
`declare` modifier not allowed for code already in an ambient context

### ISSUE THREAD

**Issue by kaname-png** [swc-project/swc#4015]
### Describe the bug

I have upgraded to the latest version of @swc/core and now I get this error.

I have not updated any libraries or code, it is still the same as it was with the previous version of @swc/core.

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "externalHelpers": false,
    "baseUrl": "./src",
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "paths": {
      "#arguments/*": ["arguments/*"],
      "#commands/*": ["commands/*"],
      "#listeners/*": ["listeners/*"],
      "#preconditions/*": ["preconditions/*"],
      "#decorators": ["lib/decorators/index.ts"],
      "#api/*": ["lib/api/*"],
      "#lib/*": ["lib/*"],
      "#root/*": ["*"]
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  },
  "module": {
    "type": "es6"
  }
}
```

### Expected behavior

A successful compilation as well as it happened with the previous version I had of `@swc/core@1.2.147`.

### Actual behavior

Compilation error.

```
PS E:\Proyectos\Personal\Naeko\naeko> yarn build
src/tsconfig.json
src/languages/en-US/api/cdn.json
src/languages/en-US/api/guild.json
 WARN import rewriter: failed to resolve: index not found
src/languages/en-US/api/main.json
src/languages/en-US/api/user.json
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
src/languages/en-US/commands/anime.json
... more files

  × `declare` modifier not allowed for code already in an ambient context
    ╭────
 32 │ declare module 'discord.js' {
    · ───────
    ╰────

  × `declare` modifier not allowed for code already in an ambient context
    ╭────
 38 │ declare module '@sapphire/pieces' {
    · ───────
    ╰────

  × `declare` modifier not allowed for code already in an ambient context
    ╭────
 75 │ declare module '@sapphire/framework' {
    · ───────
    ╰────

  × `declare` modifier not allowed for code already in an ambient context
     ╭────
 118 │ declare global {
     · ───────
     ╰────


Caused by:
    0: failed to process input file
    1: error was recoverable, but proceeding would result in wrong codegen
    2: Syntax Error
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
 WARN import rewriter: failed to resolve: index not found
Successfully compiled: 315 files, copied 97 files with swc (869.19ms)
Failed to compile 1 file with swc.
Error: Failed to compile
    at initialCompilation (E:\Proyectos\Personal\Naeko\naeko\node_modules\@swc\cli\lib\swc\dir.js:162:19)
    at async dir (E:\Proyectos\Personal\Naeko\naeko\node_modules\@swc\cli\lib\swc\dir.js:222:5)
PS E:\Proyectos\Personal\Naeko\naeko>
```

### Version

1.2.155

### Additional context

The packages have no error because if I compile directly with typescript (tsc) I don't get any error.

**Comment by kdy1** [comment]
Please post the input file

**Comment by alvin-nt** [comment]
can confirm that I am also encountering the same error.

Here's the sample code that causes the error

```ts
declare namespace Express {
  export interface Response {
    react: (viewName: string, initialState?: object) => void;
    success: (data: object, message: string, status: number) => void;
  }
}

declare const HOST: string;

declare interface ServerSidePaginationOptions<T> {
  page: number;
  perPage: number;
  sortBy: string;
  sortDesc: boolean;
  filters: T;
}
declare interface UploadFileState {
  file: File | null;
  percentage: number;
  inProgress: boolean;
}

declare type Await<T> = T extends PromiseLike<infer U> ? U : T;
```

**Comment by PxlBuzzard** [comment]
As another sample, I can reproduce with a one line .d.ts file:

```typescript
declare module 'open-web-browser';
```

**Comment by helmoski** [comment]
@kdy1  Thank you for quickly addressing this issue 👏 🥇
