### ISSUE TITLE
Implement swcx compile to feature parity to @swc/cli

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#4017]
### Describe the feature

Related with https://github.com/swc-project/swc/discussions/3859.

We want to establish initial feature parity to existing @swc/cli to plan out migration with possible breaking changes.

These are initial flags we'd like to have. 

- [ ] `config`
- [x] `config_file`
- [ ] `filename`
- [ ] `env_name`
- [ ] `ignore`
- [ ] `source_maps` (https://github.com/swc-project/cli/blob/d60fa69498e970ec045b194bf13a31c9ed6ce413/src/swc/file.ts#L78)
- [ ] `source_maps_target`
- [ ] `source_file_name`
- [ ] `source_root`
- [ ] `watch`
- [ ] `out_file` (https://github.com/swc-project/swc/pull/4016)
- [x] `out_dir`
- [x] `extensions`
- [x] `files`
- [x] `experimental_trace`
- [x] `trace_out_file`

**Comment by RiESAEX** [comment]
just found `filename` is Implemented in #4016

**Comment by Bruce-Hopkins** [comment]
I'm looking to contribute to this project, but it seems all the flags here have already been implemented according to the [docs](https://swc.rs/docs/usage/cli#--config-file).

**Comment by kwonoj** [comment]
It is not, please see above list with checkboxes.

**Comment by Bruce-Hopkins** [comment]
> It is not, please see above list with checkboxes.

Oh, I'm sorry, I got confused with the JS cli tool. I will open a PR hopefully soon to add one of these.

**Comment by HosseinAgha** [comment]
Hi, just wanted to report that looks like the commonjs target outputs es6.

**Comment by realtimetodie** [comment]
- [x]  source_maps 

was resolved in https://github.com/swc-project/swc/pull/6708

**Comment by realtimetodie** [comment]
- [x]  source_maps 
- [x]  source_maps _target

were resolved in https://github.com/swc-project/swc/pull/6708

**Comment by realtimetodie** [comment]
- [x]  source_maps 
- [x]  source_maps_target

were resolved in https://github.com/swc-project/swc/pull/6708

**Comment by realtimetodie** [comment]
I'm working on the implementation of the `--config` option.

**Comment by alexeagle** [comment]
Another TODO item: document the CLI options on the docsite somewhere. Right now tools like Bazel have to recommend that users run `swcx --help` to see how to use it.

**Comment by Aghassi** [comment]
+1 on the documentation. I see the `--config` option was implemented, but when I run it I get an error with the old syntax

```sh
❯ ~/Downloads/swc-darwin-arm64 compile --config=jsc.transform.react.importSource=@emotion/core
error: Invalid value "jsc.transform" for '--config <CONFIG>': expected value at line 1 column 1
```

@realtimetodie Would you be able to explain the changes here? I see this _just_ came out in 1.3.34 so no worries, I know it's fairly new.

**Comment by realtimetodie** [comment]
https://github.com/swc-project/swc/pull/6835

**Comment by alexeagle** [comment]
We document that in a user example now too: https://github.com/aspect-build/rules_swc/commit/8db4ee5e5e26ba6dce331fca9164dbcfcdc1e1ff

**Comment by Aghassi** [comment]
Thanks @alexeagle and @realtimetodie . So it looks like the `--config` now takes a json object instead of a dot notation object when switching between the node and rust based cli(s)

**Comment by alexeagle** [comment]
FWIW I suspect that's not intentional. @titanous when you added the `--config` support, did you mean for the syntax to be different from `@swc/cli` ?

**Comment by kdy1** [comment]
Should we revert it for now? Maybe it should be another name...
cc @kwonoj

**Comment by titanous** [comment]
Ah, I didn't know that it was already implemented in `@swc/cli`. Maybe we should rename to `--config-json`? I don't really feel like implementing a custom parser for whatever syntax was previously used.

**Comment by kdy1** [comment]
I think so, we should rename it

**Comment by titanous** [comment]
Renamed in #6932.

**Comment by Klaitos** [comment]
Hello, is adding the --copy-files flag planned aswell ?

**Comment by realtimetodie** [comment]
- [x]  source_file_name
- [x]  source_root

were resolved in https://github.com/swc-project/swc/pull/6973

**Comment by hopefullToo** [comment]
I work on an Apple M1 machine. arch: arm64.
The problem described occurs regardless of whether swc_cli is also available as a binary installed by cargo.

As described here [(https://swc.rs/docs/getting-started)]() I installed @swc/cli and @swc/core.

Then when I call npx swc --help it shows the help,
When I call npx swcx --help I get this error message:

Error: No binary found matching your system. It's probably not supported.
     at BinWrapper.download (/....../_swc_cli_/node_modules/@mole-inc/bin-wrapper/index.cjs:33675:10)
     at BinWrapper.findExisting (/....../_swc_cli_/node_modules/@mole-inc/bin-wrapper/index.cjs:33658:17)
     at async BinWrapper.run (/........./_swc_cli_/node_modules/@mole-inc/bin-wrapper/index.cjs:33619:3)
     at async executeBinary (/......../_swc_cli_/node_modules/@swc/cli/lib/swcx/index.js:145:5)

swcx is available at node_modules/.bin/.

The swc.darwin-arm64.node file is located in the node_modules/@swc/core-darwin-arm64/ directory. I tentatively made swc.darwin-arm64.node executable with chmod 755. But I can't run it stand alone. This error message appears: 
zsh: exec format error: ./swc.darwin-arm64.node

**Comment by hopefullToo** [comment]
Should I open a new issue?

**Comment by Klaitos** [comment]
There is a difference in output directory structure when using swcx cli vs classic swc.

`npx swcx compile src --out-dir dist` will generate : 
```
➜  swc tree dist     
dist
└── src
    └── index.js
```
<img width="374" alt="Capture d’écran 2023-04-13 à 12 26 46" src="https://user-images.githubusercontent.com/644360/231731621-ee1d6a7c-2661-47c1-8906-832d8f011ece.png">

`npx swc src --out-dir dist` will generate : 
```
➜  swc tree dist                  
dist
└── index.js

1 directory, 1 file
```

<img width="364" alt="Capture d’écran 2023-04-13 à 12 26 33" src="https://user-images.githubusercontent.com/644360/231731668-6df62b7c-7aee-4a4d-847e-6801c30b7a51.png">

The src folder is kept in new version of the cli.

Is that a expected behavior ?
It gives me some issues when uploading source-map to Sentry because I have to manipulate some path

Thanks !

**Comment by realtimetodie** [comment]
@linux-system-roles @bachradsusi @jamacku @pcahyna @sergio-correia @tyll @wrabcak

Please, we need your help. Apparently, [rhel-system-roles](https://access.redhat.com/articles/3050101) does not work with ansible-lint on Red Hat OpenShift.

**Comment by giraffesyo** [comment]
Was trying this out but two issues (already mentioned) are blockers for using the new version:

- No `--copy-files`, use case is `.json` files and other arbitrary files inside the source tree that are required by the application.
- Output directory changes to include top level directory in output structure. i.e. `src` folder is included. I doubt this is intentional?

**Comment by theoludwig** [comment]
@Klaitos @giraffesyo 

> Output directory changes to include top level directory in output structure. i.e. src folder is included. I doubt this is intentional?

The workaround for this, is to use the `--strip-leading-paths` CLI flag.
Build command could be the following: `swc ./src --out-dir ./build --strip-leading-paths --delete-dir-on-start`.

**Comment by jwalton** [comment]
> The workaround for this, is to use the `--strip-leading-paths` CLI flag.

Is there a way to specify this in the config file?

**Comment by jfhbrook** [comment]
I can +1 [the arm mac issue](https://github.com/swc-project/swc/issues/4017#issuecomment-1475189636). This is on `0.4.1-nightly.30340914`.

**Comment by melroy89** [comment]
[The README](https://www.npmjs.com/package/@swc/cli?activeTab=readme) still mentions that there is a beta version available `@swc/cli@1`? Is this still true though..? I can't see it.

**Comment by XhmikosR** [comment]
The arm64 macOS issue might be fixed by https://github.com/XhmikosR/os-filter-obj/pull/1. If someone with such machine could confirm/or comment there, that would help move things forward.

Unfortunately, the project I had to fork bin-wrapper and its other dependencies for (hugo-bin -> Hugo) is using .pkg format on macOS, which bin-wrapper doesn't understand, so things have been stuck lately.

**Comment by XhmikosR** [comment]
The arm issue should be fixed hopefully, I just released https://github.com/XhmikosR/os-filter-obj/releases/tag/v4.1.0 and https://github.com/XhmikosR/bin-wrapper/releases/tag/v14.2.4.
