### ISSUE TITLE
@swc/core behavior inconsistency between macOS and Linux

### ISSUE THREAD

**Issue by roland-reed** [swc-project/swc#4107]
### Describe the bug

When requiring two different versions of @swc/core (for example, two dependencies requires two different versions of @swc/core) in Linux, an error is thrown, but not in macOS.

The error message in Linux is:

```plain
Error: /dir_to_home/swc-inconsistency/node_modules/.pnpm/@swc+core-linux-x64-gnu@1.2.147/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node: cannot allocate memory in static TLS block
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/dir_to_home/swc-inconsistency/node_modules/.pnpm/@swc+core@1.2.147/node_modules/@swc/core/binding.js:181:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

I test it in macOS 12.3 with Node.js 14.18.1 and Debian 9 with Node.js 14.16.1.

I create a reproduce repo in https://github.com/roland-reed/swc-inconsistency.

### Expected behavior

It should not throw error in Linux when requiring two different versions of @swc/core.

### Version

@swc/core@1.2.156

**Comment by kdy1** [comment]
Pleaae use latest version of `@swc/core`

**Comment by roland-reed** [comment]
> Pleaae use the latest version of `@swc/core`

Is this a known issue? I have tested with 1.2.159 and 1.2.158, error is still be thrown.

**Comment by kdy1** [comment]
Your log message prints a different version

**Comment by roland-reed** [comment]
```plain
Error: /dir_to_home/workspace/swc-test/swc-inconsistency/node_modules/.pnpm/@swc+core-linux-x64-gnu@1.2.158/node_modules/@swc/core-linux-x64-gnu/swc.linux-x64-gnu.node: cannot allocate memory in static TLS block
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/dir_to_home/workspace/swc-test/swc-inconsistency/node_modules/.pnpm/@swc+core@1.2.158/node_modules/@swc/core/binding.js:181:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

Above is the error message after update, I used 1.2.158 and 1.2.159 to test, error still exists.

**Comment by kdy1** [comment]
Did you compile node.js manually?

`cannot allocate memory in static TLS block ` is an error thrown by glibc (and this depends on a constant), and CI verifies that node bindings are properly loaded before publishing

**Comment by kdy1** [comment]
CI

 - node 12: https://github.com/swc-project/swc/runs/5611750596?check_suite_focus=true
 - node 14: https://github.com/swc-project/swc/runs/5611750610?check_suite_focus=true
 - node 16: https://github.com/swc-project/swc/runs/5611750619?check_suite_focus=true

**Comment by kdy1** [comment]
What's the version of your glibc?
I think `ldd --version` will print it.


cc @Brooooooklyn 
If this is an issue of old glibc, is there a way we can workaround it?

**Comment by Brooooooklyn** [comment]
@kdy1 please reopen this issue and assign it to me. I observed this issue in other packages after upgrading `zig` from `0.9.0` to `0.9.1`.

**Comment by roland-reed** [comment]
> What's the version of your glibc? I think `ldd --version` will print it.
> 
> cc @Brooooooklyn If this is an issue of old glibc, is there a way we can workaround it?

➜ ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by phated** [comment]
Just ran into this while working on the test suite for the `interpret` npm module. We install multiple copies of swc during our test suite run.

**Comment by wmaca** [comment]
Same here with the latest version available on npm today. In my case, it was running on a node:15 image. I just updated the node image, and left it running. Can post results later.

Curiously, I ran it on two containers with different packages of the same monorepo. Error was observed only in one.

**Comment by wmaca** [comment]
@Brooooooklyn and @kdy1, are there any workarounds for this problem?

**Comment by Brooooooklyn** [comment]
Do not run `@swc/core` in `worker_thread` is a valid workaround. I'll fix this problem soon.

**Comment by phated** [comment]
@kdy1 @Brooooooklyn this is still failing. Here are the test runs: https://github.com/gulpjs/interpret/runs/6296496885?check_suite_focus=true
