### ISSUE TITLE
source type "script" with "externalHelpers" causing runtime error

### ISSUE THREAD

**Issue by troy351** [swc-project/swc#4109]
### Describe the bug

`RuntimeError: unreachable
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[7418]:0xbe35e7
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[8014]:0xbfe8e9
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[9410]:0xc2269b
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[14]:0x3d19f
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[12]:0x21bf2
    at https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm_bg.wasm:wasm-function[997]:0x6ec04d
    at Module.transformSync (https://cdn.jsdelivr.net/npm/@swc/wasm-web@1.2.159/wasm.js:153:20)
    at _ (https://play.swc.rs/_next/static/chunks/894.fe508aa76b877e05.js:1:2352)
    at https://play.swc.rs/_next/static/chunks/894.fe508aa76b877e05.js:1:37685
    at Object.To [as useMemo] (https://play.swc.rs/_next/static/chunks/framework-5f4595e5518b5600.js:1:64145)`

### Input code

```typescript
const c = a?.b
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "externalHelpers": true
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.157&code=H4sIAAAAAAAAA0vOzysuUUhWsFVItNdLAgDbbp4%2FDgAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F22hm5ygmx5CuEpw8A9JgRiTu9cmBq9mmHm8CrtYWCpkZCHuTUpUPGEBsgHFsssKpmFtWtELXQYUeSPtiLwez3e7fUpCAzAQXHRr6TKbQmYSmRfGzdNU0anEEf2HfCZunPLR95B%2BR%2BcqaMktuymkuAtc0z%2BcTr6Dvq1%2FBgkq39UAAAA%3D

### Expected behavior

No Error

### Actual behavior

`RuntimeError: unreachable`

### Version

1.2.157

**Comment by kdy1** [comment]
You can't use `externalHelpers` in script mode.

**Comment by kdy1** [comment]
I'm not sure why it throws unreachable.

**Comment by troy351** [comment]
Any reason why this is by designed?
I think we can assume a global variable like `_swcHelpers` to be the external helpers object and let users import it manually

**Comment by kdy1** [comment]
Assuming seems good, I'll go with that way, but with an option to explicitly enable it.
