### ISSUE TITLE
Failed to compile 1 file with swc

### ISSUE THREAD

**Issue by fathnakbar** [swc-project/swc#4110]
### Describe the bug

I just installed the swc just like the guide did. But it keeps failed to compile any js file. I already have default config file.

### Input code

```typescript
unknown field `` at line 1 column 151
Failed to compile 1 file with swc.
Error: Failed to compile
    at initialCompilation (/home/fathan/Projects/bnpb/node_modules/@swc/cli/lib/swc/dir.js:162:19)
    at async dir (/home/fathan/Projects/bnpb/node_modules/@swc/cli/lib/swc/dir.js:222:5)
```

### Config

```json
{
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": true
      },
      "target": "es5",
      "loose": false,
      "minify": {
        "compress": false,
        "mangle": false
      }
    },
    "module": {
      "type": "es6"
    },
    "minify": true,
    "isModule": true
}
```

### Expected behavior

Just like the documentation, it should be producing the compiled js file

### Actual behavior

Keeps failed to compile

### Version

@swc/cli = 0.1.55;@swc/core = 1.2.159

**Comment by kdy1** [comment]
I tihnk `"isModule": true` should be removed

**Comment by kdy1** [comment]
But the error message is super unhelpful.

We should throw the original exception instead of creating a new one at https://github.com/swc-project/cli/blob/d60fa69498e970ec045b194bf13a31c9ed6ce413/src/swc/dir.ts#L207-L213

**Comment by fathnakbar** [comment]
It works! thank you. But if i try to run it through npm run-script, it still throw the error. So swc can't run on npm run-script?

**Comment by kdy1** [comment]
No, please post the error messgae

**Comment by fathnakbar** [comment]
`unknown field `` at line 1 column 151
Failed to compile 1 file with swc.
Error: Failed to compile
    at initialCompilation (/home/fathan/Projects/bnpb/node_modules/@swc/cli/lib/swc/dir.js:162:19)
    at async dir (/home/fathan/Projects/bnpb/node_modules/@swc/cli/lib/swc/dir.js:222:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bnpb@1.0.0 build: `esbuild index=app/index.js --bundle --loader:.jpg=dataurl --loader:.png=dataurl --loader:.svg=text --target=es6 --outdir=build --loader:.js=jsx && swc build -d public -C .swcrc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bnpb@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fathan/.npm/_logs/2022-03-21T11_10_58_690Z-debug.log
fathan@nimellum:~/Projects/bnpb$ npx swc build -d public/src
`

**Comment by kdy1** [comment]
Seems like an issue of your config
Can you create a reproduction? Or what's your `.swcrc`?

**Comment by fathnakbar** [comment]
The config file wasn't changed. I'm still using the same config file. 

`{
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": true
      },
      "target": "es5",
      "loose": false,
      "minify": {
        "compress": false,
        "mangle": false
      }
    },
    "module": {
      "type": "es6"
    },
    "minify": true
}`

**Comment by kdy1** [comment]
Can you retry with latest `@swc/cli`? I published `v0.1.56`

**Comment by fathnakbar** [comment]
Yes, it's fixed

**Comment by fathnakbar** [comment]
Thankyou!
