### ISSUE TITLE
Cannot access '_class1' before initialization

### ISSUE THREAD

**Issue by sevenJia** [swc-project/swc#4127]
### Describe the bug

When compiling ts, anonymous classes are exported by default, and the export declaration will appear before the variable declaration.

The problem only exists when using decorators。

`exports.default = _class1;
                  ^
ReferenceError: Cannot access '_class1' before initialization
    at Object.<anonymous> (E:\ts-server\dist\controller\example.controller.class.js:37:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (E:\ts-server\dist\core\export_ctrls.js:6:54)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (E:\ts-server\dist\core\protocol.js:11:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)`

### Input code

```typescript
// ts
function test(constructor: Function) {
    console.log(constructor);
}

@test
export default class {

}


// js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = void 0;
var _class;
exports.default = _class1;
/* eslint-disable @typescript-eslint/ban-types */ /* eslint-disable @typescript-eslint/no-unused-vars */ function test(constructor) {
    console.log(constructor);
}
let _class1 = _class = test((_class = class {
}) || _class) || _class;
```

### Config

```json
{
    "test": [".*.ts$", ".*.mts$"],
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "decorators": true,
            "dynamicImport": true,
            "topLevelAwait": true
        },
        "target": "es2022",
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "baseUrl": "./",
        "paths": {
            "~/*": ["src/*"],
            "~route": ["src/core/protocol_decorators.ts"],
            "~core/*": ["src/core/*"],
            "~server/*": ["src/core/server/*"],
            "~public/*": ["src/public/*"],
            "~vendor/*": ["src/vendor/*"]
        }
    },
    "module": {
        "type": "commonjs",
        "strict": false,
        "strictMode": true
    }
}
```

### Expected behavior

fix this bug

### Version

1.2.160

**Comment by kdy1** [comment]
I investigated this and this error occurs for common js, but not for esm
