### ISSUE TITLE
SyntaxError on valid code (anonymous function after newline in return statement)

### ISSUE THREAD

**Issue by crubier** [swc-project/swc#4213]
Jest-SWC fails to parse perfectly valid JS code: 

```javascript
// /Users/vincent/Code/react-openlayers-fiber/node_modules/ol/proj.js
return (
    /**
     * Blah
     */
    function (input, opt_output, opt_dimension) { 
       // Blah
       return;
    });
```

Throws:

```
/Users/vincent/Code/react-openlayers-fiber/node_modules/ol/proj.js:207
         */ function(input, opt_output, opt_dimension) {
            ^^^^^^^^

    SyntaxError: Function statements require a function name
```

To reproduce:

```bash
git clone https://github.com/crubier/react-openlayers-fiber.git
cd react-openlayers-fiber
yarn
cd packages/react-openlayers-fiber
yarn test # 🟢 jest with babel, works
yarn vitest # 🟢 vitest, works
yarn testswc # 🔴 jest swc, fails with error below
```

The error raised is:

```
 FAIL  src/test-rig.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/vincent/Code/react-openlayers-fiber/node_modules/ol/proj.js:207
         */ function(input, opt_output, opt_dimension) {
            ^^^^^^^^

    SyntaxError: Function statements require a function name

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/ol/geom/Geometry.js:24:64)
```

The code that fails to parse correctly is this section where the anonymous `function (input, opt_output, opt_dimension)` is returned as a value, but the comments and newlines between the `return` statement and the function declaration seem to throw off the parser:

```javascript
return (
    /**
     * Blah
     */
    function (input, opt_output, opt_dimension) { 
       // Blah
       return;
    });
```

Context:

```javascript
// node_modules/ol/proj.js line 306
export function createTransformFromCoordinateTransform(coordTransform) {
    return (
    /**
     * @param {Array<number>} input Input.
     * @param {Array<number>} [opt_output] Output.
     * @param {number} [opt_dimension] Dimension.
     * @return {Array<number>} Output.
     */
    function (input, opt_output, opt_dimension) {
        var length = input.length;
        var dimension = opt_dimension !== undefined ? opt_dimension : 2;
        var output = opt_output !== undefined ? opt_output : new Array(length);
        for (var i = 0; i < length; i += dimension) {
            var point = coordTransform([input[i], input[i + 1]]);
            output[i] = point[0];
            output[i + 1] = point[1];
            for (var j = dimension - 1; j >= 2; --j) {
                output[i + j] = input[i + j];
            }
        }
        return output;
    });
}
```

**Comment by kdy1** [comment]
Closing as fixed

https://play.swc.rs/?version=1.2.244&code=H4sIAAAAAAAAA4VSy26DMBC85yumN%2FIkaaUekpC2alWpp156Q1ZEg9MagY2M6UMR%2F15jGxJIpPqAd83s7Mzavg8uYrrNRFymtPBF6udSJLOkQMo4xc38dkB%2FciEV9iXfKSY4dpJGir7JiBd7IbNnKbJHIWTM%2BOmxt6vP2nSIwwB6SapKyeGZxB%2BNzI4R7vNIRhkOD1JGv2teZu9UbiownpcKL%2FV39g80FLnailJpKMGr2c9KLNhhY5ZRXmhHBE9NeKxwQvtdusS%2B2dvJeEbuBEclNm47NVOo11ckkVL%2BoT4RWJ8zm646kLZWozpcuAoClDyme31RMe56f5e47hJZQY7FJZco3K8lOP2Gce9ZXcMjn75ReDUp03zzld7WzksdjwNcdNwoyQXjtZDuC%2FFCM4SQkQlchDEWhJz0rZfVp2GawTCFc3IZYcpb1KKHaj0kONGLKRYrfbQJ9PwwnSZ9A70GCWluz6XdJtXgPHIvy5JYeKU9Vn%2FZ%2BUlijAMAAA%3D%3D&config=H4sIAAAAAAAAA0WMMQrDMBAE%2F7K12zSq3eYRx%2BUsYhJJ7J0hQuTvtgvjbhdmZmB1RRpoQjeey3sJ%2BSEhejNXvltgwsu0UqLSkYKb%2FScEpfhS%2BT2tj2XRPl%2FUDQmzxVEzf%2BD4XjeqPaVdnR26dNBCggAAAA%3D%3D
