### ISSUE TITLE
Cannot install on node 12.11.1

### ISSUE THREAD

**Issue by verydanny** [swc-project/swc#430]
I get a build error, even using rust nightly.

```
', /Users/daniilveremchuk/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: std::panicking::begin_panic_fmt
   8: gcc::fail
   9: gcc::Build::compile
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/daniilveremchuk/source/ssr-example/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/daniilveremchuk/source/ssr-example/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/daniilveremchuk/source/ssr-example/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/daniilveremchuk/source/ssr-example/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by kdy1** [comment]
I published @swc/core@1.0.46, which provides prebuilt binary for node@12
