### ISSUE TITLE
Compiler panicks when compiling a type-only TS module to AMD

### ISSUE THREAD

**Issue by anandthakker** [swc-project/swc#4316]
### Describe the bug

Using the Rust API to compile a TS file that has no runtime code--e.g., a file that does nothing but import and export types--the compiler panicks with "The module contains only dummy spans".  

### Input code

```typescript
export type T = number;
```

### Config

```json
{
    "module": {
        "type": "amd",
        "strict": false,
        "strictMode": true,
        "lazy": false,
        "noInterop": false
    },
    "jsc": {
        "externalHelpers": false,
        "parser": {
            "syntax": "typescript",
            "tsx": true
        },
        "transform": {
            "react": {
                "pragma": "DCGView.createElement",
                "development": false,
                "useBuiltins": true
            }
        }
    },
    "sourceMaps": "inline"
}
```

### Expected behavior

The input is compiled to

```js
define([
    "exports"
], function(_exports) {
    "use strict";
    Object.defineProperty(_exports, "__esModule", {
        value: true
    });
});

//# sourceMappingURL=[...]
```

### Actual behavior

Panic:

```
thread 'main' panicked at 'The module contains only dummy spans
define([
    "exports"
], function(_exports) {
    "use strict";
    Object.defineProperty(_exports, "__esModule", {
        value: true
    });
});
', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:592:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: swc::Compiler::print::{{closure}}
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:592:17
   3: scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
   4: better_scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/better_scoped_tls-0.1.0/src/lib.rs:55:9
   5: swc::Compiler::run
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:378:9
   6: swc::Compiler::print
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:551:9
   7: swc::Compiler::process_js_inner::{{closure}}
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:1243:13
   8: scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
   9: better_scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/better_scoped_tls-0.1.0/src/lib.rs:55:9
  10: swc::Compiler::run
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:378:9
  11: swc::Compiler::process_js_inner
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:1219:9
  12: swc::Compiler::process_js_with_custom_pass::{{closure}}
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:1052:13
  13: scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  14: better_scoped_tls::ScopedKey<T>::set
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/better_scoped_tls-0.1.0/src/lib.rs:55:9
  15: swc::Compiler::run
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:378:9
  16: swc::Compiler::process_js_with_custom_pass
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.167.0/src/lib.rs:1007:9
  17: empty_module_bug::main
             at ./src/bin/amd-empty-module-bug.rs:43:18
  18: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Version

Rust crate swc 0.167.0

### Additional context

Self-contained reproduction:

```rs
use std::path::Path;
use swc::config::{Options, Config, JscConfig, ModuleConfig, SourceMapsConfig};
use swc::Compiler;
use swc_common::FileName;
use swc_common::sync::Lrc;
use swc_common::{
    errors::{ColorConfig, Handler},
    SourceMap,
};
use swc_ecma_parser::Syntax;


fn main() {
    let cm: Lrc<SourceMap> = Default::default();
    let handler = Handler::with_tty_emitter(ColorConfig::Auto, true, false, Some(cm.clone()));

    let filepath = Path::new("test.ts").to_path_buf();
    let file = cm.new_source_file(FileName::Real(filepath), String::from("export type T = number;"));

    let compiler = Compiler::new(cm.clone());

    let opts = Options {
        config: Config {
            module: Some(ModuleConfig::Amd(Default::default())),
            jsc: JscConfig {
                syntax: Some(Syntax::Typescript(Default::default())),
                ..JscConfig::default()
            },
            ..Default::default()
        },
        source_maps: Some(SourceMapsConfig::Str("inline".to_string())),
        ..Default::default()
    };

    let target = opts.config.jsc.target.unwrap_or_default();
    let syntax = opts.config.jsc.syntax.unwrap_or_default();
    let program = compiler
        .parse_js(file.clone(), &handler, target, syntax, opts.is_module, None)
        .expect("failed to parse");

    println!("{}", serde_json::to_string_pretty(&program).unwrap());

    let result = compiler
        .process_js_with_custom_pass(
            file,
            None,
            &handler,
            &opts,
            |_, _| swc_ecma_transforms::pass::noop(),
            |_, _| swc_ecma_transforms::pass::noop(),
        )
        .expect("failed to compile");

    println!("{}", result.code);
}


```

**Comment by kdy1** [comment]
Oh I investigated this and this was due to a wrong debug assertion
