### ISSUE TITLE
Transpiled transit-js node module is broken when using module.type=commonjs

### ISSUE THREAD

**Issue by Skywalker13** [swc-project/swc#4367]
### Describe the bug

The transpiled https://www.npmjs.com/package/transit-js node module is no longer loadable when using the commonjs module type.

here the steps to reproduce:
```
mkdir swc-bug
cd swc-bug
npm init
npm i -D @swc/cli @swc/core
npm i transit-js

# This command must just return immediately and without error
node node_modules/transit-js/transit.js

npx swc node_modules/transit-js/transit.js -o test.js -C module.type=commonjs

node test.js
/mnt/tux/devel/swc-bug/test.js:53
goog.global = (void 0) || self;
                          ^

ReferenceError: self is not defined
    at Object.<anonymous> (/mnt/tux/devel/swc-bug/test.js:53:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

Note that without `module.type=commonjs`, `this` is not replaced by `(void 0)` but remains `this`.

Regards

### Expected behavior

no error

### Version

"@swc/cli": "^0.1.57",     "@swc/core": "^1.2.168"

**Comment by Skywalker13** [comment]
Thank you, it works with:

```
npx swc node_modules/transit-js/transit.js -o test.js -C module.allowTopLevelThis=true -C module.type=commonjs
node test.js
```

Regards
