### ISSUE TITLE
v1.2.130 breaks "this" context in the backbone model

### ISSUE THREAD

**Issue by jakub-tucek** [swc-project/swc#4389]
### Describe the bug

Version 1.2.130 and above (1.2.170 has this issue too) breaks backbone models in our application with the following error:

```
//george/swc-backbone-reproduction/build/test.js:12
    return attrs[this.model.prototype.idAttribute || 'id'];
                                      ^

TypeError: Cannot read property 'idAttribute' of undefined
    at CardCollection.Collection.modelId (//swc-backbone-reproduction/build/test.js:12:39)
    at CardCollection.Collection.get (//swc-backbone-reproduction/build/test.js:16:17)
    at Object.<anonymous> (//george/swc-backbone-reproduction/build/test.js:25:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47


```

the issue happens on this line in the backbone library:

```
    modelId: function(attrs) {
     // this.model is undefined in this context
      return attrs[this.model.prototype.idAttribute || 'id'];
    },
```

On version 1.2.129, this works fine.

### Input code

```typescript
class Collection {

}
class Model {

}
Model.prototype.idAttribute = 'id'

Collection.prototype.model = Model;

Collection.prototype.modelId = function(attrs) {
    return attrs[this.model.prototype.idAttribute || 'id'];
}
Collection.prototype.get = function(obj) {
    if (obj == null) return void 0;
    return this.modelId(obj)
};

export class CardCollection extends Collection {
    model() {
        return Model;
    }
}


const collection = new CardCollection()

collection.get('someId');
```

### Config

```json
{
  "test": ".jsx?$",
  "sourceMaps": true,
  "inlineSourcesContent": true,
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "transform": {
      "react": {
        "throwIfNamespace": true,
        "refresh": true,
        "useBuiltins": false,
        "runtime": "automatic"
      }
    },
    "target": "es2015"
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false,
    "ignoreDynamic": true
  }
}
```

### Expected behavior

Does not fail on accessing idAttribute

### Actual behavior

Fails on access

### Version

1.2.130+

### Additional context

https://github.com/jakub-tucek/swc-backbone-reproduction

**Comment by jakub-tucek** [comment]
This issue seems to be not reproducible in play.swc.rs, where the output is the same.

Locally the transpiled code is very different though. ES2015 vs ES5 maybe? Yet the config is the same

**Comment by kdy1** [comment]
Can you post the local output then?

**Comment by jakub-tucek** [comment]
Sorry, put it to the repo only: https://github.com/jakub-tucek/swc-backbone-reproduction


1.3.170

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
class Collection {
}
class Model {
}
Model.prototype.idAttribute = 'id';
Collection.prototype.model = Model;
Collection.prototype.modelId = function(attrs) {
    return attrs[this.model.prototype.idAttribute || 'id'];
};
Collection.prototype.get = function(obj) {
    if (obj == null) return void 0;
    return this.modelId(obj);
};
class CardCollection extends Collection {
    model() {
        return Model;
    }
}
exports.CardCollection = CardCollection;
const collection = new CardCollection();
collection.get('someId');

//# sourceMappingURL=test.js.map
```

1.3.129

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.CardCollection = void 0;
function _assertThisInitialized(self) {
    if (self === void 0) {
        throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
    }
    return self;
}
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
function _defineProperties(target, props) {
    for(var i = 0; i < props.length; i++){
        var descriptor = props[i];
        descriptor.enumerable = descriptor.enumerable || false;
        descriptor.configurable = true;
        if ("value" in descriptor) descriptor.writable = true;
        Object.defineProperty(target, descriptor.key, descriptor);
    }
}
function _createClass(Constructor, protoProps, staticProps) {
    if (protoProps) _defineProperties(Constructor.prototype, protoProps);
    if (staticProps) _defineProperties(Constructor, staticProps);
    return Constructor;
}
function _getPrototypeOf(o) {
    _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) {
        return o.__proto__ || Object.getPrototypeOf(o);
    };
    return _getPrototypeOf(o);
}
function _inherits(subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
        throw new TypeError("Super expression must either be null or a function");
    }
    subClass.prototype = Object.create(superClass && superClass.prototype, {
        constructor: {
            value: subClass,
            writable: true,
            configurable: true
        }
    });
    if (superClass) _setPrototypeOf(subClass, superClass);
}
function _possibleConstructorReturn(self, call) {
    if (call && (_typeof(call) === "object" || typeof call === "function")) {
        return call;
    }
    return _assertThisInitialized(self);
}
function _setPrototypeOf(o, p) {
    _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
        o.__proto__ = p;
        return o;
    };
    return _setPrototypeOf(o, p);
}
var _typeof = function(obj) {
    "@swc/helpers - typeof";
    return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol ? "symbol" : typeof obj;
};
function _isNativeReflectConstruct() {
    if (typeof Reflect === "undefined" || !Reflect.construct) return false;
    if (Reflect.construct.sham) return false;
    if (typeof Proxy === "function") return true;
    try {
        Boolean.prototype.valueOf.call(Reflect.construct(Boolean, [], function() {}));
        return true;
    } catch (e) {
        return false;
    }
}
function _createSuper(Derived) {
    var hasNativeReflectConstruct = _isNativeReflectConstruct();
    return function _createSuperInternal() {
        var Super = _getPrototypeOf(Derived), result;
        if (hasNativeReflectConstruct) {
            var NewTarget = _getPrototypeOf(this).constructor;
            result = Reflect.construct(Super, arguments, NewTarget);
        } else {
            result = Super.apply(this, arguments);
        }
        return _possibleConstructorReturn(this, result);
    };
}
var Collection = function Collection() {
    "use strict";
    _classCallCheck(this, Collection);
};
var Model = function Model() {
    "use strict";
    _classCallCheck(this, Model);
};
Model.prototype.idAttribute = 'id';
Collection.prototype.model = Model;
Collection.prototype.modelId = function(attrs) {
    return attrs[this.model.prototype.idAttribute || 'id'];
};
Collection.prototype.get = function(obj) {
    if (obj == null) return void 0;
    return this.modelId(obj);
};
var CardCollection = /*#__PURE__*/ function(Collection) {
    "use strict";
    _inherits(CardCollection, Collection);
    var _super = _createSuper(CardCollection);
    function CardCollection() {
        _classCallCheck(this, CardCollection);
        return _super.apply(this, arguments);
    }
    _createClass(CardCollection, [
        {
            key: "model",
            value: function model() {
                return Model;
            }
        }
    ]);
    return CardCollection;
}(Collection);
exports.CardCollection = CardCollection;
var collection = new CardCollection();
collection.get('someId');

//# sourceMappingURL=test.js.map
```

**Comment by kdy1** [comment]
Seems like `.swcrc` is different for each build?
`v1.3.170` one seems to not apply `es2015` => `es5`

**Comment by jakub-tucek** [comment]
Seems so. I used this command each time & haven't touched the config:

`swc src/test.js --config-file .swcrc.json -d build`

**Comment by jakub-tucek** [comment]
The same thing happens in our "real" environment, where we use the swc-loader with webpack

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/discussions/4390#discussioncomment-2607696

I'm not sure if it's an issue of regex

**Comment by kdy1** [comment]
I found that untranspiled version is throwing.

`src/test.js`:
```js
class Collection {

}
class Model {

}
Model.prototype.idAttribute = 'id'

Collection.prototype.model = Model;

Collection.prototype.modelId = function(attrs) {
    return attrs[this.model.prototype.idAttribute || 'id'];
}
Collection.prototype.get = function(obj) {
    if (obj == null) return void 0;
    return this.modelId(obj)
};

class CardCollection extends Collection {
    model() {
        return Model;
    }
}


const collection = new CardCollection()

collection.get('someId');

```

`node src/test.js`:

```
swc-backbone-reproduction on  master [!] is 📦 v1.0.0 via  v16.14.2
❯ node src/test.js
/Users/kdy1/projects/lab/swc-backbone-reproduction/src/test.js:12
    return attrs[this.model.prototype.idAttribute || 'id'];
                                      ^

TypeError: Cannot read properties of undefined (reading 'idAttribute')
    at CardCollection.Collection.modelId (/Users/kdy1/projects/lab/swc-backbone-reproduction/src/test.js:12:39)
    at CardCollection.Collection.get (/Users/kdy1/projects/lab/swc-backbone-reproduction/src/test.js:16:17)
    at Object.<anonymous> (/Users/kdy1/projects/lab/swc-backbone-reproduction/src/test.js:28:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

```


So preivous one is miscompiled and fixed as a side effect of miscompilation.
The new behavior of swc is correct

**Comment by kdy1** [comment]
(I only removed `export` keyword from the file, to make it script instead of module)

**Comment by jakub-tucek** [comment]
Thanks for looking into this.
