### ISSUE TITLE
SWC (since 1.2.187) does not compile TypeScript decorators anymore

### ISSUE THREAD

**Issue by michael42** [swc-project/swc#4734]
### Describe the bug

After updating to the most recent SWC version, I can't run my TypeScript + jest + @swc/jest based tests anymore, because SWC doesn't seem to parse TypeScript decorators anymore. Interestingly, I was not able to reproduce it using the swc playground, so here's a [reproduction repo that uses @swc/cli](https://github.com/michael42/swc-1.2.186-decorator-bug). The issue disappears when downgrading @swc/core to 1.2.186.

### Input code

```typescript
class TestClass {
  @foo
  abc() {}
}

function foo(target: unknown, propertyKey: string | symbol) {
  console.log(`Decorating ${target}.${String(propertyKey)}`)
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true
    },
    "target": "es2020"
  }
}
```

### Expected behavior

SWC should output valid code that calls the decorator, as SWC 1.2.186 did:

```
$ npm install --save-exact @swc/core@1.2.186 && npm test
Successfully compiled 1 file with swc.
```

```js
// var __decorate = ...
class TestClass {
    abc() {}
}
__decorate([
    foo
], TestClass.prototype, "abc", null);
function foo(target, propertyKey) {
    console.log(`Decorating ${target}.${String(propertyKey)}`);
}
// ... (source map)
```

### Actual behavior

```
$ npm install --save-exact @swc/core@1.2.187 && npm test

  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
   ╭─[test.ts:2:3]
 2 │ @foo
   · ─
   ╰────


Caused by:
    0: failed to process input file
    1: Syntax Error
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (swc-decorators/node_modules/@swc/cli/lib/swc/util.js:113:15)
    at files (swc-decorators/node_modules/@swc/cli/lib/swc/file.js:173:18)
    at async _default (swc-decorators/node_modules/@swc/cli/lib/swc/file.js:192:9)
```

### Version

@swc/cli 0.1.57 and @swc/core 1.2.187

**Comment by kdy1** [comment]
Can you try it with `SWC_DEBUG=1`?

**Comment by kdy1** [comment]
I unpublished the new version

**Comment by kdy1** [comment]
Oh, my bad...

**Comment by kdy1** [comment]
Use `v1.2.188` instead

**Comment by michael42** [comment]
1.2.188 has the same issue for me, unfortunately:

```
$ npm install --save-exact @swc/core@1.2.188 && SWC_DEBUG=1 swc test.ts

  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
   ╭─[test.ts:2:3]
 2 │ @foo
   · ─
   ╰────


Caused by:
    0: failed to process input file
    1: Parser config: Typescript(TsConfig { tsx: false, decorators: false, dts: false, no_early_errors: false })
    2: Syntax Error
Error: Failed to compile 1 file with swc.
    at Object.assertCompilationResult (swc-decorators/node_modules/@swc/cli/lib/swc/util.js:113:15)
    at files (swc-decorators/node_modules/@swc/cli/lib/swc/file.js:173:18)
    at async _default (swc-decorators/node_modules/@swc/cli/lib/swc/file.js:192:9)
```
