### ISSUE TITLE
@swc/core breaks yarn which in-turn breaks Grafana on IBM s390x machines

### ISSUE THREAD

**Issue by sinceresiva** [swc-project/swc#5219]
### Describe the bug

Yarn (version 4.0.0-rc.12) is broken when we execute **yarn start** on IBM s390x systems (zLinux). This is because @swc-core gives an error **Unsupported architecture on Linux: s390x**:
The full error text is given below:

-sh-4.2$ sudo yarn start
/root/.yarn/berry/cache/@swc-core-npm-1.2.160-4f6417fe5e-9.zip/node_modules/@swc/core/binding.js:234
                throw new Error(`Unsupported architecture on Linux: ${arch}`);
                      ^
Error: Unsupported architecture on Linux: s390x
    at Object.<anonymous> (/root/.yarn/berry/cache/@swc-core-npm-1.2.160-4f6417fe5e-9.zip/node_modules/@swc/core/binding.js:234:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require$$0.Module._extensions..js (/srv/grafana-install/grafana-8.5.0/.pnp.cjs:59955:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/srv/grafana-install/grafana-8.5.0/.pnp.cjs:59795:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.yarn/berry/cache/@swc-core-npm-1.2.160-4f6417fe5e-9.zip/node_modules/@swc/core/index.js:39:88)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Previously with the classic versions of yarn both yarn and Grafana were working fine. Now that the latest versions of yarn is using @swc-core this is breaking yarn and in-turn Grafana recent versions as well (such as Grafana 8.5.0 and above).

Requesting SWC to please allow support for big-endian systems such as IBM s390x systems (zLinux). 

My environment:
OS: zLinux (s390x)
NodeJS version: v16.15.1
yarn version: 4.0.0-rc.12
npm version: 8.11.0

Thanks.

### Expected behavior

@swc-core-npm-1.2.160-4f6417fe5e-9.zip/node_modules/@swc/core/binding.js:234 must support big-endian systems such as IBM s390x(zLinux) so that both yarn and in-turn grafana can seamless build on s390x systems. 

### Version

@swc-core-npm-1.2.160-4f6417fe5e-9

**Comment by kwonoj** [comment]
@kdy1 I do not believe we'll expand another native build targets in a short timeframe, instead (I recall we discussed somewhere else) we may need some automatic fallback mechanism to swc/wasm as similar to next-swc does. Thoughts?

**Comment by kdy1** [comment]
I think it would be super useful

**Comment by kwonoj** [comment]
I'll close this one, and later file a tracking issue to support seamless fallback to `@swc/wasm` for the platforms does not have native binaries.

To be more clear, we do not expect to support more native build targets at this moment unless there is a strong active user base.

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/5221 is filed for tracking.

**Comment by merceyz** [comment]
> @swc/core breaks yarn
> Now that the latest versions of yarn is using @swc-core

Yarn isn't using swc so Yarn is unrelated to this issue.

**Comment by sinceresiva** [comment]
My apologies. Yes, Yarn is unrelated to this issue.
