### ISSUE TITLE
issue using `@swc/plugin-emotion` with `swc` `.swcrc` - `failed to process input file`

### ISSUE THREAD

**Issue by pietrop** [swc-project/swc#5453]
### Discussed in https://github.com/swc-project/swc/discussions/5450

<div type='discussions-op-text'>

<sup>Originally posted by **pietrop** August 11, 2022</sup>
👋 Hello,
I am trying to use `@swc/plugin-emotion` with `swc` from [swc-project/plugins/packages/emotion](https://github.com/swc-project/plugins/tree/main/packages/emotion) in `.swcrc` :

```json
{
  "jsc": {
    ...
   "experimental": {
     "plugins": [ ["@swc/plugin-emotion", {}]]
  },
```

But when I run `swc` (`npx swc ./src --config-file ./swcrc/.swcrc.commonjs -d dist/cjs`) I get an error:

> `failed to process input file`

_For context, it seems to work fine if I remove the `experimental` and `plugins` attributes_
----

And when I try to check the `.swcrc` in [swc.rs/playground](http://swc.rs/playground) for  `"experimental"`  I get

> Property experimental is not allowed
<img width="751" alt="Screen Shot 2022-08-11 at 11 46 07 AM" src="https://user-images.githubusercontent.com/4661975/184174782-508b7db0-6388-4900-88d3-61a815648002.png">

Btw I also get the same for `"exclude"` in case that's relevant.

So I wanted to double check if I am doing something wrong? or whether there are known issues with plugins and/or the emotion plugin? 🙏 

I also added an example repo to reproduce [github.com/pietrop/cra-swc-emotion-plugin-example](https://github.com/pietrop/cra-swc-emotion-plugin-example)

_Let me know if you need any other info, pretty stuck on this_</div>

**Comment by pietrop** [comment]
originally as github discussion https://github.com/swc-project/swc/discussions/5450

**Comment by kdy1** [comment]
Does older version of plugin work?

**Comment by pietrop** [comment]
Sorry for the delay. No, I just saw https://github.com/swc-project/plugins/issues/69 and tried with `2.1.0` and didn't work either. I also tried `2.2.0`

**Comment by pietrop** [comment]
I can also try go further back if there's a version you think might work?

**Comment by kwonoj** [comment]
Just fyi, we found some regressions which requires to update `@swc/core` and plugins **both**. Probably worth to retry once there are some new changes.

**Comment by pietrop** [comment]
Thanks, I just tried with `"@swc/core": "^1.2.226"` I get this error:

<details><summary>error log</summary>

```sh
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    0: failed to invoke `@swc/plugin-emotion` as js transform plugin at node_modules/@swc/plugin-emotion/swc_plugin_emotion.wasm
    1: RuntimeError: out of bounds memory access
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x33ca3)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::hf2e6124d5e412f93 (<module>[586]:0x7e22e)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73ca4)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h6717a5f1b1cd910b (<module>[571]:0x73a99)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73e49)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h6717a5f1b1cd910b (<module>[571]:0x73a99)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73e49)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x34cea)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x34db0)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2f86a6b8a9b8c11f (<module>[263]:0x4d1d8)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::hb527b33d1a3564d7 (<module>[69]:0x96a8)
           at swc_ecma_ast::function::_::<impl rkyv::Deserialize<swc_ecma_ast::function::Function,__D> for <swc_ecma_ast::function::Function as rkyv::Archive>::Archived>::deserialize::h6b75fb64aa5e30b5 (<module>[227]:0x41f1c)
           at swc_ecma_ast::decl::_::<impl rkyv::Deserialize<swc_ecma_ast::decl::Decl,__D> for <swc_ecma_ast::decl::Decl as rkyv::Archive>::Archived>::deserialize::h18b4adb5f5eb2595 (<module>[225]:0x40a4e)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2f86a6b8a9b8c11f (<module>[263]:0x4dcca)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h180b95bdbfcc8197 (<module>[68]:0x8fbc)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::hed4d3813b848536b (<module>[67]:0x7e50)
           at swc_common::plugin::serialized::deserialize_from_ptr::h7da9db581ae8757d (<module>[66]:0x7d7e)
           at __transform_plugin_process_impl (<module>[677]:0x84e10)
           at __transform_plugin_process_impl.command_export (<module>[3857]:0x14ff74)
    2: heap_get_oob', crates/swc/src/plugin.rs:222:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    0: failed to invoke `@swc/plugin-emotion` as js transform plugin at node_modules/@swc/plugin-emotion/swc_plugin_emotion.wasm
    1: RuntimeError: out of bounds memory access
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x33ca3)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::hf2e6124d5e412f93 (<module>[586]:0x7e22e)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73ca4)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h6717a5f1b1cd910b (<module>[571]:0x73a99)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73e49)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h6717a5f1b1cd910b (<module>[571]:0x73a99)
           at rkyv::impls::alloc::boxed::<impl rkyv::Deserialize<alloc::boxed::Box<T>,D> for rkyv::boxed::ArchivedBox<<T as rkyv::ArchiveUnsized>::Archived>>::deserialize::h62fbf351e6807ba2 (<module>[572]:0x73e49)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x34cea)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::hb5d1fbbf11595d70 (<module>[214]:0x34db0)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2f86a6b8a9b8c11f (<module>[263]:0x4d1d8)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::hb527b33d1a3564d7 (<module>[69]:0x96a8)
           at swc_ecma_ast::function::_::<impl rkyv::Deserialize<swc_ecma_ast::function::Function,__D> for <swc_ecma_ast::function::Function as rkyv::Archive>::Archived>::deserialize::h6b75fb64aa5e30b5 (<module>[227]:0x41f1c)
           at swc_ecma_ast::decl::_::<impl rkyv::Deserialize<swc_ecma_ast::decl::Decl,__D> for <swc_ecma_ast::decl::Decl as rkyv::Archive>::Archived>::deserialize::h18b4adb5f5eb2595 (<module>[225]:0x40a4e)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h2f86a6b8a9b8c11f (<module>[263]:0x4dcca)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h180b95bdbfcc8197 (<module>[68]:0x8fbc)
           at swc_common::plugin::serialized::PluginSerializedBytes::deserialize::hed4d3813b848536b (<module>[67]:0x7e50)
           at swc_common::plugin::serialized::deserialize_from_ptr::h7da9db581ae8757d (<module>[66]:0x7d7e)
           at __transform_plugin_process_impl (<module>[677]:0x84e10)
           at __transform_plugin_process_impl.command_export (<module>[3857]:0x14ff74)
    2: heap_get_oob
Successfully compiled: 1 file with swc (42.44ms)
Failed to compile 1 file with swc.
Error: Failed to compile:
src/App.js
    at initialCompilation (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:172:19)
    at async dir (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:16:5)
    ```
    
    </details>
    
So I guess you are saying I should wait for a new release of `@swc/core` that combined with version `@swc/plugin-emotion@2.2.2` should have the fix ?

**Comment by kwonoj** [comment]
> I should wait for a new release of @swc/core that combined with version

Yes, we expect so.

**Comment by pietrop** [comment]
Awesome, thanks 🤞 🙏 
Happy to test it out, once it's ready 😄

**Comment by pietrop** [comment]
👋 With the latest version of everything 

```json
  ....
  "@swc/plugin-emotion": "^2.2.4",
  }
  "devDependencies": {
    "@swc/cli": "^0.1.57",
    "@swc/core": "^1.2.233"
  }
  ```
  
I get a different error now

```
0: Failed to create plugin instance
1: Error while importing "env"."__span_to_lines_proxy": incompatible import type. 
```

<details><summary> full error here </summary>

  ```js
  > npx swc ./src --config-file ./.swcrc.commonjs -d dist/cjs

thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("src/index.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__span_to_lines_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32, I32, I32], results: [I32] })failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__span_to_lines_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32, I32, I32], results: [I32] })', ', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.214.6/src/plugin.rs/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.214.6/src/plugin.rs::215215:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:14
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("src/index.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__span_to_lines_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32, I32, I32], results: [I32] })
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__span_to_lines_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32, I32, I32], results: [I32] })
Failed to compile 2 files with swc.
Error: Failed to compile:
src/App.js
src/index.js
    at initialCompilation (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:172:19)
    at async dir (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:16:5)
```

</details>

**Comment by kwonoj** [comment]
We did not update the issue if it's resolved.

**Comment by pietrop** [comment]
👋 I _think_ I have some good news

I updated the plugin and `swc` to the latest version and it _seems_ to work.
```json
"@swc/plugin-emotion": "^2.2.5",
"@swc/cli": "^0.1.57",
"@swc/core": "^1.2.239"
```


I made a PR with the change in the example repo, to also show the transpiled output https://github.com/pietrop/cra-swc-emotion-plugin-example/pull/1

----

I am not super familiar with the plugin transpiling process, and what the output should look like. But wanted to confirm if this ⬇️  looks right to you?

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: !0
}), Object.defineProperty(exports, "default", {
    enumerable: !0,
    get: function() {
        return _default;
    }
});
var _jsxRuntime = require("react/jsx-runtime");
require("./App.css");
var _react = require("@emotion/react"), _default = function() {
    var baseClassName = (0, _react.css)("display:block;background-color:red;width:100px;height:100px;", "baseClassName");
    return (0, _jsxRuntime.jsx)(_react.ClassNames, {
        children: function(param) {
            var _$css = param.css, cx = param.cx;
            return (0, _jsxRuntime.jsx)("div", {
                className: cx(_$css(baseClassName)),
                children: "Test"
            });
        }
    });
};
```

**Comment by kwonoj** [comment]
We can't validate the output if it's what you desired or not, unfortunately. Would like to recommend trying it in the application / or test suite to verify. 

Meanwhile, I believe the issue itself is reasonably resolved, so closing issue for now. Using the latest `@swc/core` and `swc_core` would resolve issues.

**Comment by pietrop** [comment]
Could we re open this? with latest `@swc/core` this is broken again.

```
"@swc/cli": "^0.1.57",
 "@swc/core": "^1.2.242"
 ```
 
 Log:
 ```js
 
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    Missing export __get_transform_plugin_core_pkg_diagfailed to invoke plugin: failed to invoke plugin on 'Some("src/index.js")'

Caused by:
    Missing export __get_transform_plugin_core_pkg_diag', ', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.218.4/src/plugin.rs/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.218.4/src/plugin.rs::216216::1414

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("src/App.js")'

Caused by:
    Missing export __get_transform_plugin_core_pkg_diag
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("src/index.js")'

Caused by:
    Missing export __get_transform_plugin_core_pkg_diag
Failed to compile 2 files with swc.
Error: Failed to compile:
src/App.js
src/index.js
    at initialCompilation (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:172:19)
    at async dir (/Users/pietropassarelli/CODE/cra-swc-emotion-plugin-example/node_modules/@swc/cli/lib/swc/dir.js:16:5)
```

**Comment by kdy1** [comment]
Please file a new issue instead
