### ISSUE TITLE
Thread panics at Option::unwrap()

### ISSUE THREAD

**Issue by AGawrys** [swc-project/swc#5797]
### Describe the bug

Hi, I'm trying to build a project with Parcel and optimize using the latest version of `SWC` but the code panics. I'm not sure I can post a reproduction but will try. 

Any tips on debugging or steps for a repro would be appreciated 😄 

The config is from https://github.com/parcel-bundler/parcel/blob/v2/packages/optimizers/swc/src/SwcOptimizer.js#:~:text=let%20config%20%3D,%7D%3B and I'm simply updating the version of `swc/core` here

### Config

```json
let config = {
      mangle: true,
      compress: true,
      ...userConfig,
      sourceMap: bundle.env.sourceMap
        ? {
            filename: path.relative(
              options.projectRoot,
              path.join(bundle.target.distDir, bundle.name),
            ),
          }
        : false,
      toplevel:
        bundle.env.outputFormat === 'esmodule' ||
        bundle.env.outputFormat === 'commonjs',
      module: bundle.env.outputFormat === 'esmodule',
    };
```

### Expected behavior

No error.

### Actual behavior

A thread panics and we exit the project

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_minifier-0.152.18/src/compress/optimize/mod.rs:2655:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'We should not drop synthesized stmts', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_minifier-0.152.18/src/compress/optimize/mod.rs:2874:13
stack backtrace:
   0:        0x34609e1ec - _napi_register_module_v1
   1:        0x345dafda0 - _blake3_compress_in_place_portable
   2:        0x34607a634 - _napi_register_module_v1
   3:        0x3460a1cf4 - _napi_register_module_v1
   4:        0x3460a2c24 - _napi_register_module_v1
   5:        0x3460a26e8 - _napi_register_module_v1
   6:        0x3460a2680 - _napi_register_module_v1
   7:        0x3460a264c - _napi_register_module_v1
   8:        0x34717bbec - _wasmer_vm_raise_trap
   9:        0x346645414 - _napi_register_module_v1
  10:        0x346544eec - _napi_register_module_v1
  11:        0x34664cad4 - _napi_register_module_v1
  12:        0x34654130c - _napi_register_module_v1
  13:        0x34664cad4 - _napi_register_module_v1
  14:        0x3466520d8 - _napi_register_module_v1
  15:        0x346540b28 - _napi_register_module_v1
  16:        0x34664cad4 - _napi_register_module_v1
  17:        0x346541d24 - _napi_register_module_v1
  18:        0x34664cad4 - _napi_register_module_v1
  19:        0x34666ebac - _napi_register_module_v1
  20:        0x3466724d8 - _napi_register_module_v1
  21:        0x34664c674 - _napi_register_module_v1
  22:        0x34664a3b4 - _napi_register_module_v1
  23:        0x34666335c - _napi_register_module_v1
  24:        0x34666b35c - _napi_register_module_v1
  25:        0x346669fa4 - _napi_register_module_v1
  26:        0x3465415a4 - _napi_register_module_v1
  27:        0x34664cad4 - _napi_register_module_v1
  28:        0x34666ebac - _napi_register_module_v1
  29:        0x3466724d8 - _napi_register_module_v1
  30:        0x34664c674 - _napi_register_module_v1
  31:        0x34664a3b4 - _napi_register_module_v1
  32:        0x34666335c - _napi_register_module_v1
  33:        0x34666b35c - _napi_register_module_v1
  34:        0x346669fa4 - _napi_register_module_v1
  35:        0x3466589ac - _napi_register_module_v1
  36:        0x34664cad4 - _napi_register_module_v1
  37:        0x346541d24 - _napi_register_module_v1
  38:        0x34664cad4 - _napi_register_module_v1
  39:        0x34654130c - _napi_register_module_v1
  40:        0x34664cad4 - _napi_register_module_v1
  41:        0x34654db2c - _napi_register_module_v1
  42:        0x34666335c - _napi_register_module_v1
  43:        0x34678caa8 - _napi_register_module_v1
  44:        0x346659d10 - _napi_register_module_v1
  45:        0x346659888 - _napi_register_module_v1
  46:        0x3465ce718 - _napi_register_module_v1
  47:        0x346797b50 - _napi_register_module_v1
  48:        0x346726448 - _napi_register_module_v1
  49:        0x346336d34 - _napi_register_module_v1
  50:        0x345b74e64 - <unknown>
  51:        0x345bbbbb8 - <unknown>
  52:        0x10302abd4 - _worker
  53:        0x1909f426c - __pthread_deallocate
thread panicked while panicking. aborting.
```

### Version

1.2.249

**Comment by kdy1** [comment]
Can you share the input?
This issue is impossible to debug without input

**Comment by AGawrys** [comment]
Sorry! It seemed to be a config issue on my end 😄
