### ISSUE TITLE
`bundle` - Panic on arrays with 64 or more numbers 

### ISSUE THREAD

**Issue by Nerixyz** [swc-project/swc#5891]
### Describe the bug

When an input file for `@swc/core`'s `bundle()` contains a declaration of an array with 64 or more numbers, `bundle` panics.

### Input code

```typescript
// foo.js
const foo = [
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
];
```

### Config

```json
// index.js
// no .swcrc
const {bundle} = require('@swc/core');

(async () => {
    await bundle({
        entry: __dirname + '/foo.js',
        output: {
            path: __dirname,
            name: '/bar.js',
        },
        module: {},
    });
})();
```

### Expected behavior

This should emit an empty file or a file that only contains this array.

### Actual behavior

`bundle` panics:

```
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-1.0.0\src\lib.rs:168:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                    
node:internal/process/promises:288                                                                                                                                                                               
            triggerUncaughtException(err, true /* fromPromise */);                                                                                                                                               
            ^                                                                                                                                                                                                    

[Error: panic detected] { code: 'GenericFailure' }

Node.js v18.0.0
```

<details>
<summary>With RUST_BACKTRACE=full</summary>

```
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-1.0.0\src\lib.rs:168:9
stack backtrace:
   0:     0x7ffb16013f5f - wasmer_vm_raise_trap
   1:     0x7ffb16030eba - wasmer_vm_raise_trap
   2:     0x7ffb1600db49 - wasmer_vm_raise_trap
   3:     0x7ffb160169cb - wasmer_vm_raise_trap
   4:     0x7ffb1601664b - wasmer_vm_raise_trap
   5:     0x7ffb16016f79 - wasmer_vm_raise_trap
   6:     0x7ffb16e5535a - wasmer_vm_raise_trap
   7:     0x7ffb16e55327 - wasmer_vm_raise_trap
   8:     0x7ffb1771a6fd - wasmer_vm_raise_trap
   9:     0x7ffb16e13443 - wasmer_vm_raise_trap
  10:     0x7ffb16df0bdc - wasmer_vm_raise_trap
  11:     0x7ffb15f482f1 - wasmer_vm_raise_trap
  12:     0x7ffb15f4b42f - wasmer_vm_raise_trap
  13:     0x7ffb16def03c - wasmer_vm_raise_trap
  14:     0x7ffb15f47df4 - wasmer_vm_raise_trap
  15:     0x7ffb15f4a9d1 - wasmer_vm_raise_trap
  16:     0x7ffb15f4a922 - wasmer_vm_raise_trap
  17:     0x7ffb15f48f76 - wasmer_vm_raise_trap
  18:     0x7ffb15c86836 - Ordinal0
  19:     0x7ffb15c7d3c3 - Ordinal0
  20:     0x7ffb15b4634a - Ordinal0
  21:     0x7ffb15b9aa39 - Ordinal0
  22:     0x7ffb15b59396 - Ordinal0
  23:     0x7ffb15bda5ab - Ordinal0
  24:     0x7ffb15b13479 - Ordinal0
  25:     0x7ff70e1ebc3e - uv_queue_work
  26:     0x7ff70e1d7d4d - uv_poll_stop
  27:     0x7ff70f182060 - v8::internal::compiler::ToString
  28:     0x7ffb89e47034 - BaseThreadInitThunk
  29:     0x7ffb8a5e26a1 - RtlUserThreadStart
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: panic detected] { code: 'GenericFailure' }

Node.js v18.0.0
```
</details>

### Version

1.3.1

### Additional context

I reported this initially in swc-project/cli#163 but I realized the issue is in the `bundle` function which is in this repository.

Bundling `foo.js` with `deno bundle foo.js` and compiling it with `npx swc foo.js` works fine.

**Comment by Nerixyz** [comment]
You can reproduce the panic by adding a test-case in `node-swc`:

```diff
diff --git a/node-swc/__tests__/spack/simple_test.js b/node-swc/__tests__/spack/simple_test.js
index ca041a6f9c..26b072476c 100644
--- a/node-swc/__tests__/spack/simple_test.js
+++ b/node-swc/__tests__/spack/simple_test.js
@@ -35,4 +35,17 @@ it('should handle loader', async () => {
     console.log(result)
     expect(result.simple).toBeTruthy();
     expect(result.simple.code.replace('\n', '')).toBe(`console.log("Foo");`);
+});
+
+it('should handle arrays', async () => {
+    const result = await swc.bundle({
+        name: 'array',
+        entry: {
+            array: path.join(__dirname, '../../tests/spack/array/a.js')
+        },
+    });
+
+    console.log(result)
+    expect(result.array).toBeTruthy();
+    expect(result.array.code.replace('\n', '')).toBe('');
 });
\ No newline at end of file
diff --git a/node-swc/tests/spack/array/a.js b/node-swc/tests/spack/array/a.js
new file mode 100644
index 0000000000..2236dcd59d
--- /dev/null
+++ b/node-swc/tests/spack/array/a.js
@@ -0,0 +1,18 @@
+const foo = [
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+    1, 1, 1, 1,
+];
\ No newline at end of file
```

Then run the `test` script.

**Comment by Tronix117** [comment]
It does the same with an object with at least 8 keys :
```
console.log({
  a: null,
  b: null,
  c: null,
  d: null,
  e: null,
  f: null,
  g: null,
  h: null,
});
```

In a docker container using `node` image, just `spack` on this code and we get the error.
Couldn't find a workaround, I have no special settings, nothing, just this code in a `main.ts`.
Also unusable for me at this stade.

Works fine using `swc`

**Comment by Tjerk-Haaye-Henricus** [comment]
Same issue here: Did you manage to make it work ?
