### ISSUE TITLE
export * from 'bar' not supported

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#605]
**Input code**

a.js
```
import * as namespace from 'b';
console.log({ namespace });
```

b.js
```
export * from 'c';
```

c.js
```
export const FOO = 'foo';
export const BAR = 'bar';
```

**Config**
```json
{
  "jsc": {
    "target": "es2015",
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "classProperty": true,
      "exportNamespaceFrom": true,
      "exportDefaultFrom": true
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Expected behavior**
All consts from `c` should be reflected out of `b`.
https://tc39.es/ecma262/#table-42

**Version**
The version of @swc/core: 

```
$ grep swc package.json
    "@swc/cli": "0.1.22",
    "@swc/core": "1.1.14",
    "swc-loader": "0.1.6",
```

**Comment by duncanbeevers** [comment]
@kdy1 This doesn't appear to have changed the behavior I was seeing.

```
$ grep swc package.json
    "@swc/cli": "0.1.22",
    "@swc/core": "1.1.15",
    "swc-loader": "0.1.6",
```

```
$ swc a.js | node
./b.js:1
(function (exports, require, module, __filename, __dirname) { export * from 'c';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by kdy1** [comment]
It seems like swc is not invoked for b.js

**Comment by duncanbeevers** [comment]
I see what you're saying about swc not being invoked for b.js

In the real-world project from which example was extracted, a statement of the same form causes swc to panic (error code 134).

So maybe it's parsing correctly, but something else is broken further down the toolchain. I'll see about creating a small webpack project that reproduces the error, but likely not until next week.
