### ISSUE TITLE
Won't build under node 13.x

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc#606]
I tried using `@swc/core` in a project pinned to a new-ish node version 13.6.0.
When I try to build I get a gnarly gyp error

```
  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc: In function ‘void {anonymous}::TargetCallback(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&)’:
../src/weakref.cc:147:73: error: no matching function for call to ‘v8::Function::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value> [1])’
   globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);
                                                                         ^
In file included from /home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/v8.h:4335:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
                                           ^~~~
/home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/v8.h:4335:43: note:   candidate expects 4 arguments, 3 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Create(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:168:75: error: no matching function for call to ‘v8::ObjectTemplate::NewInstance()’
   Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
                                                                           ^
In file included from /home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/v8.h:6565:44: note: candidate: v8::MaybeLocal<v8::Object> v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
                                            ^~~~~~~~~~~
/home/duncanbeevers/.cache/node-gyp/13.6.0/include/node/v8.h:6565:44: note:   candidate expects 1 argument, 0 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::IsNearDeath(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:223:55: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
                                                       ^~~~~~~~~~~
weakref.target.mk:111: recipe for target 'Release/obj.target/weakref/src/weakref.o' failed
make: Leaving directory '/home/duncanbeevers/Projects/plexinc/plex-web-client/node_modules/weak/build'
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/duncanbeevers/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command \"/home/duncanbeevers/.nvm/versions/node/v13.6.0/bin/node\" \"/home/duncanbeevers/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
```

The same @swc/core version builds fine under node 10.14.1

**Comment by kdy1** [comment]
Are you sure that this is an issue of swc? I failed to reproduce the issue on ubuntu 18.04 with node 13.6.0

**Comment by duncanbeevers** [comment]
It looks like this issue may be with `weak`. https://github.com/TooTallNate/node-weak/issues/99

**Comment by duncanbeevers** [comment]
This appears to be unrelated to `swc`. Mea culpa.
