### ISSUE TITLE
As of version 1.2.206 running jest tests with swc as transformer might fail

### ISSUE THREAD

**Issue by yharaskrik** [swc-project/swc#6189]
### Describe the bug

When mocking modules jest started to throw and error at v1.2.206 and above (1.2.205 works)

```
> nx run util:test

 FAIL   util  packages/util/src/lib/util.spec.ts
  util
    ✕ should work (1 ms)

  ● util › should work

    TypeError: Cannot redefine property: util2
        at Function.defineProperty (<anonymous>)

      4 | describe('util', () => {
      5 |   it('should work', () => {
    > 6 |     jest.spyOn(util2, 'util2').mockImplementation(() => {})
        |          ^
      7 |     expect(util()).toEqual('util');
      8 |   });
      9 | });

      at ModuleMocker.spyOn (../../node_modules/jest-mock/build/index.js:820:16)
      at Object.<anonymous> (src/lib/util.spec.ts:6:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.534 s
Ran all test suites.
```

`util2.ts`
```
export function util2() {}
```

`util.spec.ts`
```
import { util } from './util';
import * as util2 from './util2'

describe('util', () => {
  it('should work', () => {
    jest.spyOn(util2, 'util2').mockImplementation(() => {})
    expect(util()).toEqual('util');
  });
});
```

I am assuming it was this change

https://github.com/swc-project/swc/commit/fa68cbd74ad2b36c0f1aaec563320114d5603cae

### Expected behavior

Should be able to mock modules correctly like in 1.2.205

### Version

1.2.206

### Additional context

Full package JSON (all other swc deps are up to date)

```
{
  "name": "swc-mock-issues",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {
    "@swc/helpers": "0.4.12",
    "tslib": "^2.3.0"
  },
  "devDependencies": {
    "@nrwl/cli": "15.0.0",
    "@nrwl/eslint-plugin-nx": "15.0.0",
    "@nrwl/jest": "15.0.0",
    "@nrwl/js": "15.0.0",
    "@nrwl/linter": "15.0.0",
    "@nrwl/workspace": "15.0.0",
    "@swc/cli": "0.1.57",
    "@swc/core": "1.2.206",
    "@swc/jest": "0.2.23",
    "@types/jest": "28.1.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "nx": "15.0.0",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }
}
```

**Comment by kwonoj** [comment]
https://github.com/swc-project/swc/issues/5205

**Comment by yharaskrik** [comment]
@kwonoj don't think I am using ESM? My code should be running through SWC first to commonjs and then running. Is this still an issue with ESM if so I will figure out another way to do this. Thank you.

```
{
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "decoratorMetadata": true,
      "legacyDecorator": true
    },
    "keepClassNames": true,
    "externalHelpers": true,
    "loose": true
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "noInterop": true
  },
  "sourceMaps": true,
  "exclude": ["jest.config.ts",".*.spec.tsx?$",".*.test.tsx?$","./src/jest-setup.ts$","./**/jest-setup.ts$",".*.js$"]
}
```

**Comment by kwonoj** [comment]
Please follow through the thread itself. If you are using esm import syntax we preserve correct esm module behavior.

**Comment by yharaskrik** [comment]
> Please follow through the thread itself. If you are using esm import syntax we preserve correct esm module behavior.

Oh I missed that part sorry. Thank you!
