### ISSUE TITLE
[@swc/core - @swc/jest] - Upgrading from @swc/core 1.3.4 to 1.3.5

### ISSUE THREAD

**Issue by jnarwold** [swc-project/swc#6347]
### Describe the bug

After upgrading `@swc/core` from `1.3.4` to `1.3.5`, all of our tests fail with the same error:

```
  ● Test suite failed to run

    failed to process input file

    Caused by:
        cannot process file because it's ignored by .swcrc

      at Compiler.transformSync (../../../node_modules/.pnpm/@swc+core@1.3.5/node_modules/@swc/core/index.js:241:29)
      at transformSync (../../../node_modules/.pnpm/@swc+core@1.3.5/node_modules/@swc/core/index.js:348:21)
      at Object.process (../../../node_modules/.pnpm/@swc+jest@0.2.23_@swc+core@1.3.5/node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

### Config

```json
No `.swcrc` file
```

### Expected behavior

Passing tests, or at least the tests failing on execution and not initialization.

### Version

1.3.5

### Additional context

We're not fully converted over to `swc` at this time, ergo the lack of a `.swcrc` file. First step was migrating our tests and then circling back to update everything else from `babel` to `swc.

The only block of our `jest.config` that I had to update after switching to `@swc/jest` was the transform:

```
transform: {
    '^.+\\.(js|jsx)$': [
      '@swc/jest',
      {
        test: '.jsx?$',
        jsc: {
          parser: {
            jsx: true,
          },
        },
      },
    ],
    '^.+\\.(ts|tsx)$': [
      '@swc/jest',
      {
        test: '.tsx?$',
        jsc: {
          parser: {
            syntax: 'typescript',
            tsx: true,
          },
        },
      },
    ],
    '^.+\\.(ttf|svg|png|jpg|gif)$': `${__dirname}/staticAssetMock.js`,
  }
```

**Comment by kdy1** [comment]
Please provide a repro
