### ISSUE TITLE
[Bug]: Class in computed field of itself

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6350]
### Describe the bug

Running `input1.js`, `input2.js` and `input3.js` should all result in `ReferenceError`.
However, transpilation outputs, `output1.js`, `output2.js` and `output3.js` behave differently; `output1.js` and `output2.js` throws `Error` and `SyntaxError` respectively, and `output3.js` terminates normally.

### Input code

```typescript
// Expected: ReferenceError

// input1.js
class x { [ x ] } // got Error

// input2.js
class x { [ x ++ ] } // got SyntaxError

// input3.js
class x { [ x = 0 ] } // normal termination
```

### Expected behavior

Running `input1.js`, `input2.js` and `input3.js` should all result in `ReferenceError`:
```console
$ node input1.js
input1.js:1
class x { [ x ] }
            ^

ReferenceError: Cannot access 'x' before initialization
    at Object.<anonymous> (/input1.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0

$ node input2.js
input2.js:1
class x { [ x ++ ] }
              ^

ReferenceError: Cannot access 'x' before initialization
...

$ node input3.js
input3.js:1
class x { [ x = 0 ] }
              ^

ReferenceError: Cannot access 'x' before initialization
...
```

### Actual behavior

Transpilation outputs, `output1.js`, `output2.js` and `output3.js` don't throw `ReferenceError`; they behave differently:
```console
$ node output1.js # throws Error
output1.js:8
function _classNameTDZError(name) { throw new Error("Class \"" + name + "\" cannot be referenced in computed property keys."); }
                                    ^

Error: Class "x" cannot be referenced in computed property keys.
    at _classNameTDZError (output1.js:8:43)
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/output.js:9:9)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0

$ node output2.js # throws SyntaxError
output2.js:9
_ref = (_classNameTDZError("x"), x)++;
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid left-hand side expression in postfix operation
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0

$ node output3.js # terminates without error
```

### Version

1.3.11 (default SWC playground)

### Additional context

[Playground link 1](https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA9PXV3CtKEhNLklNsVIISk1LLUrNS051LSrKL%2BLi0tdXyMwrKC0x1Msq5krOSSwuVqhQqFaIBpKxCrUKQOn0%2FBIFsGIAu9MDz0gAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)
[Playground link 2](https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA9PXV3CtKEhNLklNsVIISk1LLUrNS051LSrKL%2BLi0tdXyMwrKC0x0ssq5lJIzkksLlaoUKhWiAaS2toKsQq1CkAl6fklCsGVeSWJFRBtAPnMNCFTAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)
[Playground link 3](https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA9PXV3CtKEhNLklNsVIISk1LLUrNS051LSrKL%2BLi0tdXyMwrKC0x1ssq5krOSSwuVqhQqFaIBpK2CgYKsQq1CkAleflFuYk5CiWpRbmZeYklmfl5AOwPHNdVAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)

**Comment by Austaras** [comment]
Current JS build tools like babel or terser almost always ignore TDZ errors, I believe SWC behave the same.

This issue can be closed.

**Comment by kdy1** [comment]
Thanks!
