### ISSUE TITLE
[Bug]: Generator with array pattern parameter

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6375]
### Describe the bug

The input program is expected to throw `TypeError` but the transpiled program terminates without any error.
In the transpiled program,`TypeError` is thrown only after `f().next();` method of the generator is called.

### Input code

```typescript
function * f([]){};
f();
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0srzUsuyczPU9BSSNOIjtWsrrXmStPQtAYAEIYO6RgAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

```console
$ node input.js
input.js:1
function * f([]){};
            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at f (input.js:1:13)
    at Object.<anonymous> (input.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

`output.js` is terminated without any error:
```console
$ node output.js # no error
```

### Version

1.3.14 (default SWC playground)

**Comment by p51lee** [comment]
We are doing a research related to fuzzing. Right now, we're looking at the basic experimental results, but we're also thinking of targeting minifiers after that. Thank you for your interest.
