### ISSUE TITLE
[Bug]: Deleting super property

### ISSUE THREAD

**Issue by p51lee** [swc-project/swc#6389]
### Describe the bug

`ReferenceError` is expected when running the input code, but output code is terminated normally.

### Input code

```typescript
class x { static y = delete super [ 0 ] ; }
```

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAA0vOSSwuVqhQqFYoLkksyUxWqFSwVUhJzUktSVUoLi1ILVKIVjBQiFWwVqgFAGhAQhIrAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`input.js` throws `ReferenceError`:
```console
$ node input.js
input.js:1
class x { static 0 = delete super [ 0 ] ; }
                     ^

ReferenceError: Unsupported reference to 'super'
    at <static_initializer> (input.js:1:22)
    at Object.<anonymous> (input.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

`output.js` is terminated normally:
```console
$ node output.js # no error
```

### Version

1.3.14 (default SWC playground)

**Comment by Austaras** [comment]
Since nobody is relying on this and it would always leads to a `ReferenceError`, the best solution would be simply ban it on parse time.

**Comment by kdy1** [comment]
I'm not sure if this worth a fix
