### ISSUE TITLE
Error: terser@npm:@swc/core isn't supported by any available resolver

### ISSUE THREAD

**Issue by green1052** [swc-project/swc#6482]
### Describe the bug

```logs
➤ YN0001: │ Error: terser@npm:@swc/core isn't supported by any available resolver
    at Wf.getResolverByDescriptor (.yarn\releases\yarn-3.3.0.cjs:391:1647)
    at Wf.bindDescriptor (.yarn\releases\yarn-3.3.0.cjs:391:1036)
    at reduceDependency (.yarn\releases\yarn-3.3.0.cjs:390:26618)
    at Ga.reduceHook (.yarn\releases\yarn-3.3.0.cjs:392:3512)
    at Z (\.yarn\releases\yarn-3.3.0.cjs:439:6710)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 31)
    at async eo (.yarn\releases\yarn-3.3.0.cjs:390:8293)
```

package.json
```logs
{
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@babel/preset-env": "^7.20.2",
    "@swc/core": "^1.3.18",
    "@types/node": "^18.11.9",
    "@types/webextension-polyfill": "^0.9.1",
    "@types/webpack": "^5.28.0",
    "@types/webpack-env": "^1.18.0",
    "@typescript-eslint/eslint-plugin": "^5.43.0",
    "@typescript-eslint/parser": "^5.43.0",
    "browserslist": "^4.21.4",
    "clean-terminal-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.2",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-prettier-standard": "^4.0.1",
    "eslint-config-standard": "^17.0.0",
    "eslint-import-resolver-node": "^0.3.6",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "html-webpack-plugin": "^5.5.0",
    "mini-css-extract-plugin": "^2.7.0",
    "prettier": "^2.7.1",
    "pug": "^3.0.2",
    "pug-loader": "^2.4.0",
    "regenerator-runtime": "^0.13.11",
    "sass": "^1.56.1",
    "sass-loader": "^13.2.0",
    "swc-loader": "^0.2.3",
    "typescript": "^4.9.3",
    "vue-loader": "15.10.1",
    "vue-template-compiler": "^2.7.14",
    "webextension-polyfill": "^0.10.0",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.0",
    "webpack-merge": "^5.8.0"
  },
  "dependencies": {
    "vue": "2.7.14"
  },
  "packageManager": "yarn@3.3.0",
  "resolutions": { "terser": "npm:@swc/core" }
}
```

### Config

```json
{
    "minify": true,
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "decorators": false,
            "dynamicImport": false
        },
        "target": "es2022"
    },
    "env": {
        "targets": "defaults"
    }
}
```

### Expected behavior

https://swc.rs/docs/configuration/minification#replacing-terser

i tried replacing terser but not working

### Version

1.3.18

**Comment by kwonoj** [comment]
Just tried locally and it works fine:

```
{
  "name": "fff",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@swc/core": "^1.3.18"
  },
  "resolutions": {
    "terser": "npm:@swc/core"
  },
  "packageManager": "yarn@3.3.0"
}
```

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1210596/202867696-115f083d-cd07-47ba-987a-c38b84986934.png">


In either case, I believe this is yarn-related issue, not swc-related issue.
