### ISSUE TITLE
Installation failing with error code 404

### ISSUE THREAD

**Issue by samjmckenzie** [swc-project/swc#653]
Trying to install swc with `npm i -D @swc/core @swc/cli` on macOS 10.15.3, node v11.7.0 and npm v6.13.7.

This is the console log.

```
sammckenzie@MacBookPro13-Sam sammckenzie.be % npm i -D @swc/core @swc/cli 

> @swc/core@1.1.20 install /Users/sammckenzie/PhpstormProjects/sammckenzie.be/node_modules/@swc/core
> node scripts/install.js || neon build --release

Thank you for using swc ( https://github.com/swc-project/swc ): super-fast javascript and typescript compiler 

The project needs your help! Please consider supporting swc on Open Collective: 
> https://opencollective.com/swc 

Downloading binary from https://github.com/swc-project/node-swc/releases/download/v1.1.20/darwin-x64-67.node
Cannot download "https://github.com/swc-project/node-swc/releases/download/v1.1.20/darwin-x64-67.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
npm WARN sammckenzie.be No repository field.
npm WARN sammckenzie.be No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @swc/core@1.1.20 install: `node scripts/install.js || neon build --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @swc/core@1.1.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sammckenzie/.npm/_logs/2020-02-11T19_10_51_864Z-debug.log
```

Am I running the wrong version of something?

**Comment by kdy1** [comment]
I'm sorry, but currently node js 11 is not supported.

Supported versions are 8, 10, 12, and 13. I'll update the doc.

**Comment by samjmckenzie** [comment]
Ah right, no problem. The doc page where it said node 11 was supported is here: https://swc-project.github.io/docs/installation

**Comment by kdy1** [comment]
@samjmckenzie I've updated the documentation.
