### ISSUE TITLE
Cannot run Nest.js app after compiling

### ISSUE THREAD

**Issue by techvlad** [swc-project/swc#666]
**Describe the bug**
swc successful compile [Nest.js](https://github.com/nestjs/nest), but cannot run after compiling

```
➜ npx swc src -s -d ./dist && node dist/main.js
Successfully compiled 5 files with swc.
[Nest] 23731   - 02/14/2020, 5:27:26 PM   [NestFactory] Starting Nest application...
[Nest] 23731   - 02/14/2020, 5:27:26 PM   [ExceptionHandler] Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []
 +5ms
Error: Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.

(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope []

    at NestContainer.addModule (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/injector/container.js:42:19)
    at DependenciesScanner.insertModule (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/scanner.js:50:31)
    at DependenciesScanner.scanForModules (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/scanner.js:27:43)
    at DependenciesScanner.scan (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/scanner.js:21:20)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/nest-factory.js:80:17
    at async Function.asyncRun (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/errors/exceptions-zone.js:17:13)
    at async NestFactoryStatic.initialize (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/nest-factory.js:79:13)
    at async NestFactoryStatic.create (/home/hex/Sandbox/nestjs-swc-build/node_modules/@nestjs/core/nest-factory.js:30:9)
    at async bootstrap (/home/hex/Sandbox/nestjs-swc-build/dist/main.js:5:17)`
```
**.swcrc**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    },
    "target": "es2018"
  },
  "module": {
    "type": "commonjs"
  }
}
```

[Example repo](https://github.com/techvlad/nestjs-swc-build)

**Comment by techvlad** [comment]
Nest.js project was created via default [nest-cli](https://github.com/nestjs/nest-cli)

**Comment by kdy1** [comment]
@techvlad I did some investigation. It seems like the behavior of the swc almost matches it of babel.

swc generates
```js
var _dec = _common.Module({
  imports: [],
  controllers: [_appController.AppController],
  providers: [_appService.AppService],
});
let AppModule =
  _dec(
    (_class = (function() {
      class AppModule {}
      return AppModule;
    })()),
  ) || _class;
```

while babel generates

```js
var AppModule =
  ((_dec = (0, _common.Module)({
    imports: [],
    controllers: [_app.AppController],
    providers: [_app2.AppService],
  })),
  _dec(
    (_class = function AppModule() {
      _classCallCheck(this, AppModule);
    }),
  ) || _class);
```

When I changed the output of swc to 
```js
let AppModule =
  _dec(
    (_class = (function() {
      class AppModule {}
      return AppModule;
    })()),
  ) || _class;
```
, it's behavior become exactly same as babel's one. But the same error occurs anyway.


Thus, I'm not sure if this is issue of the swc.  Is this really a bug of swc?

**Comment by kdy1** [comment]
Note: tsc generates
```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};

AppModule = __decorate([
    Module({
        imports: [],
        controllers: [AppController],
        providers: [AppService],
    })
], AppModule);
```

which reduces to a call to `Reflect.decorate()`. I'm not sure if this is correct behavior for legacy decorators.

**Comment by unlight** [comment]
NestJS requires `emitDecoratorMetadata: true` setting.
This metadata is used by NestJS's dependency injection system.

I think swc should mimic behavior [babel-plugin-decorator-metadata](https://github.com/stephanos/babel-plugin-decorator-metadata) or [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata)

Is there are any plans to implement this?

**Comment by kdy1** [comment]
@unlight Of course. Some decorator fixes are wip.

**Comment by kdy1** [comment]
I've implemented this, but I want some execution test suite. How did you configured nest-cli to use swc?

**Comment by techvlad** [comment]
nest-cli does not have any compiler options.
Just compile via swc: `npx swc src -s -d ./dist && node dist/main.js`

**Comment by kdy1** [comment]
@techvlad Thanks!
