### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'endCol')

### ISSUE THREAD

**Issue by tjunghans** [swc-project/swc#6710]
### Describe the bug

When updating from @swc/core@1.3.3 to 1.3.4 and re-run tests, the following error occurs for some, but not all, test suites:

 Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'endCol')

      at module.exports.sliceRange (node_modules/v8-to-istanbul/lib/range.js:30:54)
      at node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:139:19
          at Array.forEach (<anonymous>)
      at node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:125:20
          at Array.forEach (<anonymous>)
      at V8ToIstanbul.applyCoverage (node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:124:12)
      at node_modules/@jest/reporters/build/CoverageReporter.js:530:21
          at async Promise.all (index 21)
      at CoverageReporter._getCoverageResult (node_modules/@jest/reporters/build/CoverageReporter.js:499:35)
      at CoverageReporter.onRunComplete (node_modules/@jest/reporters/build/CoverageReporter.js:172:34)
      at ReporterDispatcher.onRunComplete (node_modules/@jest/core/build/ReporterDispatcher.js:64:9)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:296:5)
      at runJest (node_modules/@jest/core/build/runJest.js:349:19)

I've been unable to spot the difference between test suits that don't result in this error and those that do. 

The error above is visible in the latest version (1.3.24) of @swc/core as well.

### Input code

```typescript
Not available
```

### Config

```json
Not available.
```

### Expected behavior

The TypeError should not be thrown or a more useful error message displayed.

### Actual behavior

TypeError is thrown after running tests: 

```
TypeError: Cannot read properties of undefined (reading 'endCol')

      at module.exports.sliceRange (node_modules/v8-to-istanbul/lib/range.js:30:54)
      at node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:139:19
          at Array.forEach (<anonymous>)
      at node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:125:20
          at Array.forEach (<anonymous>)
      at V8ToIstanbul.applyCoverage (node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:124:12)
      at node_modules/@jest/reporters/build/CoverageReporter.js:530:21
          at async Promise.all (index 21)
      at CoverageReporter._getCoverageResult (node_modules/@jest/reporters/build/CoverageReporter.js:499:35)
      at CoverageReporter.onRunComplete (node_modules/@jest/reporters/build/CoverageReporter.js:172:34)
      at ReporterDispatcher.onRunComplete (node_modules/@jest/core/build/ReporterDispatcher.js:64:9)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:296:5)
      at runJest (node_modules/@jest/core/build/runJest.js:349:19)
```

### Version

1.3.4 onwards

### Additional context

As a workaround I am using 1.3.3.

**Comment by kdy1** [comment]
Closing as there's no information for reproduction

**Comment by tjunghans** [comment]
If I can find time to narrow down the issue or create a reproduceable example, I'll come back here.
