### ISSUE TITLE
watch is not working on macOS

### ISSUE THREAD

**Issue by moltar** [swc-project/swc#673]
**Describe the bug**

Running the command in watch mode results in error being thrown:

```
The optional dependency chokidar failed to install and is required for --watch. Chokidar is likely not supported on your platform.
{ Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.requireChokidar (~pkg/node_modules/@swc/cli/lib/src/util.js:106:16)
    at ~pkg/node_modules/@swc/cli/lib/src/dir.js:128:35
    at Generator.next (<anonymous>)
    at fulfilled (~pkg/node_modules/@swc/cli/lib/src/dir.js:4:58) code: 'MODULE_NOT_FOUND' }
```

**Input code**

```
npm i --save-dev @swc/cli @swc/core
npx swc ./src -d lib -w
```

**Config**

No added config.

**Expected behavior**

Watch mode to work.

**Version**

```
@swc/cli: 0.1.23
@swc/core: 1.1.24
```

**Additional context**

macOS Catalina
10.15.3 (19D76)

**Comment by moltar** [comment]
Simple fix:

```
npm i -D chokidar
```

So I am not even sure if this qualifies as bug. Maybe a documentation bug?

**Comment by kdy1** [comment]
I think so. I'll document it soon.
