### ISSUE TITLE
panic: swc on typescript directory

### ISSUE THREAD

**Issue by nhumrich** [swc-project/swc#675]
I can run `npx swc src/somefile.ts` just fine, but when I run it with my directory `npx swc src -d dist`, all I get is:

```
fatal runtime error: failed to initiate panic, error 5
fish: “npx swc src -d dist” terminated by signal SIGABRT (Abort)
```

1. Cant include all source code, have no idea which file is causing things to fail

2. `.swcrc` file. Dont have one. I have tried adding one based on docs, and that doesn't change anything.

3. Error message gained from `swc --sync <input.js>`
(--sync is required to get panic message)

```
error: Expected Comma, got Some(Dot)
 --> src/app/errors.ts:8:43
  |
8 |     Object.setPrototypeOf(this, new.target.prototype)
  |                                           ^

Error: internal error in Neon module: internal error: entered unreachable code: for-of statement should be removed by es2015::for_of pass
ForOfStmt { span: Span { lo: BytePos(13390), hi: BytePos(13660), ctxt: #0 }, await_token: Some(Span { lo: BytePos(13394), hi: BytePos(13399), ctxt: #0 }), left: Pat(Ident(Ident { span: Span { lo: BytePos(13407), hi: BytePos(13410), ctxt: #19 }, sym: Atom('row' type=inline), type_ann: None, optional: false })), right: Ident(Ident { span: Span { lo: BytePos(13414), hi: BytePos(13420), ctxt: #18 }, sym: Atom('stream' type=inline), type_ann: None, optional: false }), body: Block(BlockStmt { span: Span { lo: BytePos(13422), hi: BytePos(13660), ctxt: #0 }, stmts: [If(IfStmt { span: Span { lo: BytePos(13434), hi: BytePos(13486), ctxt: #0 }, test: Unary(UnaryExpr { span: Span { lo: BytePos(13438), hi: BytePos(13450), ctxt: #0 }, op: "!", arg: Member(MemberExpr { span: Span { lo: BytePos(13439), hi: BytePos(13450), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13439), hi: BytePos(13442), ctxt: #19 }, sym: Atom('row' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(13443), hi: BytePos(13450), ctxt: #0 }, sym: Atom('results' type=inline), type_ann: None, optional: false }), computed: false }) }), cons: Block(BlockStmt { span: Span { lo: BytePos(13452), hi: BytePos(13486), ctxt: #0 }, stmts: [Continue(ContinueStmt { span: Span { lo: BytePos(13466), hi: BytePos(13474), ctxt: #0 }, label: None })] }), alt: None }), Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Seq(SeqExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, exprs: [Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorNormalCompletion' type=dynamic), type_ann: None, optional: false })), right: Lit(Bool(Bool { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: true })) }), Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_didIteratorError' type=dynamic), type_ann: None, optional: false })), right: Lit(Bool(Bool { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: false })) }), Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorError' type=dynamic), type_ann: None, optional: false })), right: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('undefined' type=static), type_ann: None, optional: false }) })] }) }), Try(TryStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, block: BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [For(ForStmt { span: Span { lo: BytePos(13497), hi: BytePos(13650), ctxt: #0 }, init: Some(Expr(Seq(SeqExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, exprs: [Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iterator' type=dynamic), type_ann: None, optional: false })), right: Call(CallExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, callee: Expr(Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Member(MemberExpr { span: Span { lo: BytePos(13513), hi: BytePos(13524), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13513), hi: BytePos(13516), ctxt: #19 }, sym: Atom('row' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(13517), hi: BytePos(13524), ctxt: #0 }, sym: Atom('results' type=inline), type_ann: None, optional: false }), computed: false })), prop: Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('Symbol' type=static), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('iterator' type=static), type_ann: None, optional: false }), computed: false }), computed: true })), args: [], type_args: None }) })] }))), test: Some(Unary(UnaryExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "!", arg: Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorNormalCompletion' type=dynamic), type_ann: None, optional: false })), right: Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_step' type=inline), type_ann: None, optional: false })), right: Call(CallExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, callee: Expr(Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iterator' type=dynamic), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('next' type=inline), type_ann: None, optional: false }), computed: false })), args: [], type_args: None }) })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('done' type=inline), type_ann: None, optional: false }), computed: false }) }) })), update: Some(Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorNormalCompletion' type=dynamic), type_ann: None, optional: false })), right: Lit(Bool(Bool { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: true })) })), body: Block(BlockStmt { span: Span { lo: BytePos(13526), hi: BytePos(13650), ctxt: #0 }, stmts: [Expr(ExprStmt { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #0 }, expr: Seq(SeqExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, exprs: [Assign(AssignExpr { span: Span { lo: BytePos(13508), hi: BytePos(13509), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13508), hi: BytePos(13509), ctxt: #20 }, sym: Atom('r' type=inline), type_ann: None, optional: false })), right: Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_step' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('value' type=inline), type_ann: None, optional: false }), computed: false }) })] }) }), If(IfStmt { span: Span { lo: BytePos(13540), hi: BytePos(13614), ctxt: #0 }, test: Unary(UnaryExpr { span: Span { lo: BytePos(13544), hi: BytePos(13569), ctxt: #0 }, op: "!", arg: Call(CallExpr { span: Span { lo: BytePos(13545), hi: BytePos(13569), ctxt: #0 }, callee: Expr(Member(MemberExpr { span: Span { lo: BytePos(13545), hi: BytePos(13566), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13545), hi: BytePos(13551), ctxt: #19 }, sym: Atom('counts' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(13552), hi: BytePos(13566), ctxt: #0 }, sym: Atom('hasOwnProperty' type=dynamic), type_ann: None, optional: false }), computed: false })), args: [ExprOrSpread { spread: None, expr: Ident(Ident { span: Span { lo: BytePos(13567), hi: BytePos(13568), ctxt: #20 }, sym: Atom('r' type=inline), type_ann: None, optional: false }) }], type_args: None }) }), cons: Block(BlockStmt { span: Span { lo: BytePos(13571), hi: BytePos(13614), ctxt: #0 }, stmts: [Expr(ExprStmt { span: Span { lo: BytePos(13587), hi: BytePos(13600), ctxt: #0 }, expr: Assign(AssignExpr { span: Span { lo: BytePos(13587), hi: BytePos(13600), ctxt: #0 }, op: "=", left: Expr(Member(MemberExpr { span: Span { lo: BytePos(13587), hi: BytePos(13596), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13587), hi: BytePos(13593), ctxt: #19 }, sym: Atom('counts' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(13594), hi: BytePos(13595), ctxt: #20 }, sym: Atom('r' type=inline), type_ann: None, optional: false }), computed: true })), right: Lit(Num(Number { span: Span { lo: BytePos(13599), hi: BytePos(13600), ctxt: #0 }, value: 0.0 })) }) })] }), alt: None }), Expr(ExprStmt { span: Span { lo: BytePos(13627), hi: BytePos(13638), ctxt: #0 }, expr: Update(UpdateExpr { span: Span { lo: BytePos(13627), hi: BytePos(13638), ctxt: #0 }, op: "++", prefix: false, arg: Member(MemberExpr { span: Span { lo: BytePos(13627), hi: BytePos(13636), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13627), hi: BytePos(13633), ctxt: #19 }, sym: Atom('counts' type=inline), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(13634), hi: BytePos(13635), ctxt: #20 }, sym: Atom('r' type=inline), type_ann: None, optional: false }), computed: true }) }) })] }) })] }, handler: Some(CatchClause { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, param: Some(Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('err' type=inline), type_ann: None, optional: false })), body: BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_didIteratorError' type=dynamic), type_ann: None, optional: false })), right: Lit(Bool(Bool { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, value: true })) }) }), Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Assign(AssignExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "=", left: Pat(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorError' type=dynamic), type_ann: None, optional: false })), right: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('err' type=inline), type_ann: None, optional: false }) }) })] } }), finalizer: Some(BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [Try(TryStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, block: BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [If(IfStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, test: Bin(BinExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "&&", left: Unary(UnaryExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "!", arg: Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorNormalCompletion' type=dynamic), type_ann: None, optional: false }) }), right: Bin(BinExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, op: "!=", left: Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iterator' type=dynamic), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('return' type=static), type_ann: None, optional: false }), computed: false }), right: Lit(Null(Null { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 } })) }) }), cons: Block(BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [Expr(ExprStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, expr: Call(CallExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, callee: Expr(Member(MemberExpr { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, obj: Expr(Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iterator' type=dynamic), type_ann: None, optional: false })), prop: Ident(Ident { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, sym: Atom('return' type=static), type_ann: None, optional: false }), computed: false })), args: [], type_args: None }) })] }), alt: None })] }, handler: None, finalizer: Some(BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [If(IfStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, test: Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_didIteratorError' type=dynamic), type_ann: None, optional: false }), cons: Block(BlockStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, stmts: [Throw(ThrowStmt { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, arg: Ident(Ident { span: Span { lo: BytePos(13502), hi: BytePos(13509), ctxt: #24 }, sym: Atom('_iteratorError' type=dynamic), type_ann: None, optional: false }) })] }), alt: None })] }) })] }) })] }) }
    at Compiler.transformFileSync (/home/nhumrich/hw/cmd-backend/node_modules/@swc/core/index.js:155:22)
    at Object.transformFileSync (/home/nhumrich/hw/cmd-backend/node_modules/@swc/core/index.js:197:21)
    at Object.<anonymous> (/home/nhumrich/hw/cmd-backend/node_modules/@swc/cli/lib/src/util.js:77:24)
    at Generator.next (<anonymous>)
    at /home/nhumrich/hw/cmd-backend/node_modules/@swc/cli/lib/src/util.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/nhumrich/hw/cmd-backend/node_modules/@swc/cli/lib/src/util.js:3:12)
    at Object.compile (/home/nhumrich/hw/cmd-backend/node_modules/@swc/cli/lib/src/util.js:74:12)
    at /home/nhumrich/hw/cmd-backend/node_modules/@swc/cli/lib/src/file.js:155:47
    at Generator.next (<anonymous>)
```

Oddly, based on this error, I did some more debugging.

I can comment out the line that causes this error, the `new.target.prototype`. When I do that and run the following: `npx swc --sync src -d dist`. Everything works! I get a `Successfully compiled...`, but as soon as I take the `--sync` off, and run the exact same command minus the sync, I get the panic, error 5 again.

![2020-02-17-161608_screenshot](https://user-images.githubusercontent.com/4661889/74691672-f9747e80-51a0-11ea-8599-56da9dab0ff8.png)

**Comment by nhumrich** [comment]
After more research, looks like it might actually be breaking on this line. If I run npx swc on a completely different file I get a panic, the --sync shows similar output as about about for-of. I think it might be this line of code:
```
 for await (const row of stream) {```

**Comment by kdy1** [comment]
I think there are two bugs. Seems like a concurrency bug (I though I fixed it...,) .and await-for being not implemneted. I'll fix it soon.

**Comment by kdy1** [comment]
@nhumrich Which version of swc are you using? I failed to reproduce concurrency issue

**Comment by nhumrich** [comment]
+ @swc/cli@0.1.23
+ @swc/core@1.1.26

**Comment by nhumrich** [comment]
Oddly, I just reinstalled, and now `--sync` and without `--sync` have the same error. So maybe the concurrency bug is fixed, i just wasn't installing latest somehow?
