### ISSUE TITLE
Compiler.transformSync crashes in jest tests

### ISSUE THREAD

**Issue by arnassavickas** [swc-project/swc#6789]
### Describe the bug

I am using `swc` to compile `jest` tests. When upgrading `@swc/jest` and `@swc/core` to the latest versions and adding `jest_workaround`, tests sometimes crash in `Jenkins` CI pipeline.

Crash only happens sometimes, and I can never reproduce it locally.

Error message for one of the tests:
```
21:04:11  thread '<unnamed>' panicked at 'range end index 7551504 out of range for slice of length 2326496', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-engine-universal-2.3.0/src/artifact.rs:102:38
21:04:11  stack backtrace:
21:04:11  thread '<unnamed>' panicked at 'range end index 7551504 out of range for slice of length 2699232', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-engine-universal-2.3.0/src/artifact.rs:102:38
21:04:11  stack backtrace:
21:04:11  thread '<unnamed>' panicked at 'range end index 7551504 out of range for slice of length 3547104', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-engine-universal-2.3.0/src/artifact.rs:102:38
21:04:11  stack backtrace:
21:04:11  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
21:04:11  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
21:04:11  FAIL client/app/xxx.test.tsx
21:04:11    ● Test suite failed to run
21:04:11  
21:04:11      failed to handle: range end index 7551504 out of range for slice of length 2699232
21:04:11  
21:04:11      Stack backtrace:
21:04:11         0: <unknown>
21:04:11         1: <unknown>
21:04:11         2: <unknown>
21:04:11         3: <unknown>
21:04:11         4: <unknown>
21:04:11         5: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
21:04:11         6: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
21:04:11         7: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
21:04:11         8: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
21:04:11         9: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
21:04:11  
21:04:11        at Compiler.transformSync (node_modules/.pnpm/@swc+core@1.3.25/node_modules/@swc/core/index.js:241:29)
21:04:11        at transformSync (node_modules/.pnpm/@swc+core@1.3.25/node_modules/@swc/core/index.js:348:21)
21:04:11        at Object.process (node_modules/.pnpm/@swc+jest@0.2.24_@swc+core@1.3.25/node_modules/@swc/jest/index.js:73:45)
21:04:11        at ScriptTransformer.transformSource (node_modules/.pnpm/@jest+transform@28.1.3/node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
21:04:11        at ScriptTransformer._transformAndBuildScript (node_modules/.pnpm/@jest+transform@28.1.3/node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
21:04:11        at ScriptTransformer.transform (node_modules/.pnpm/@jest+transform@28.1.3/node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

#### jest.config.js
```js
// ...
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        jsc: {
          experimental: {
            plugins: [['jest_workaround', {}]],
          },
        },
        module: {
          type: 'commonjs',
        },
      },
    ],
  },
// ...
```

### Expected behavior

Tests should run in CI the same as locally.

### Version

```
"@swc/core": "^1.3.25",
"@swc/jest": "^0.2.24",
"jest_workaround": "^0.1.13"
```

**Comment by kwonoj** [comment]
This is likely due to the inside of plugin / or comunicating between plugin to host have some issues. However without reproducible inputs, it is nearly impossible to dig further.

**Comment by arnassavickas** [comment]
Any other way for me to provide more info without a repro?
It might be a plugin, but I can't check because, without it, my tests don't run at all, so I don't know how to check that.

**Comment by kwonoj** [comment]
we'll likely need to attach debug or getting log + full backtrace when it happens, which required debug build. Which means, every attempt requires reproducible case unfortunately.

**Comment by arnassavickas** [comment]
Update: soon after merging, the same errors reappeared again in Jenkins builds.

Can I pass some options for debugging to get a fuller backtrace that would help you?
