### ISSUE TITLE
jsc.paths produce absolute paths like //?/E:/project/my-project/src/config

### ISSUE THREAD

**Issue by tiavina-mika** [swc-project/swc#6858]
### Describe the bug

The imports in dist directory use absolute paths instead of relative paths

`app.ts`
```
import { NODE_ENV } from "@config";
```

`dist/app.js`
```
const _config = require("//?/E:/project/my-project/src/config");
```
This cause the following error because it can not find the files with absolute paths:
```

Error: Cannot find module '//?/E:/1lalana/1lalana-server/src/config'
Require stack:
- E:\project\my-project\dist\app.js
- E:\project\my-project\dist\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\1lalana\1lalana-server\dist\app.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\project\\my-project\\dist\\app.js',
    'E:\\project\\my-projectr\\dist\\server.js'
  ]
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "dynamicImport": true,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2017",
    "externalHelpers": false,
    "keepClassNames": true,
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"],
      "@config": ["config"],
      "@controllers/*": ["controllers/*"],
      "@dtos/*": ["dtos/*"],
      "@exceptions/*": ["exceptions/*"],
      "@interfaces/*": ["interfaces/*"],
      "@middlewares/*": ["middlewares/*"],
      "@models/*": ["models/*"],
      "@routes/*": ["routes/*"],
      "@services/*": ["services/*"],
      "@utils/*": ["utils/*"],
      "@cloud/*": ["cloud/*"],
      "@types/*": ["types/*"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

### Expected behavior

const _config = require("./config");

### Actual behavior

const _config = require("//?/E:/project/my-project/src/config");

### Version

1.3.29

**Comment by kdy1** [comment]
Closing as duplicate
