### ISSUE TITLE
New beta version of @swc/cli is now available via 'swcx'  crashes on Mac

### ISSUE THREAD

**Issue by hopefullToo** [swc-project/swc#7114]
### Describe the bug

With the installation of @swc/core: 1.2.66, @swc/cli: 0.1.62 comes the note 'Beta version of @swc/cli is now available via 'swcx' command. ... Please give it a try'

On my Apple computer I have problems with calling swcx.

I work on an Apple M1 machine. arch: arm64.
The problem described occurs regardless of whether swc_cli is also available as a binary installed by cargo.

As described here [(https://swc.rs/docs/getting-started)](https://github.com/swc-project/swc/issues/4017) I installed @swc/cli and @swc/core.

Then when I call npx swc --help it shows the help,
When I call npx swcx --help I get this error message:

Error: No binary found matching your system. It's probably not supported.
at BinWrapper.download (/....../swc_cli/node_modules/@mole-inc/bin-wrapper/index.cjs:33675:10)
at BinWrapper.findExisting (/....../swc_cli/node_modules/@mole-inc/bin-wrapper/index.cjs:33658:17)
at async BinWrapper.run (/........./swc_cli/node_modules/@mole-inc/bin-wrapper/index.cjs:33619:3)
at async executeBinary (/......../swc_cli/node_modules/@swc/cli/lib/swcx/index.js:145:5)

swcx is available at node_modules/.bin/.

The swc.darwin-arm64.node file is located in the node_modules/@swc/core-darwin-arm64/ directory. I tentatively made swc.darwin-arm64.node executable with chmod 755. But I can't run it stand alone. This error message appears:
zsh: exec format error: ./swc.darwin-arm64.node

### Expected behavior

swcx --help should be displayed.

### Version

@swc/core: 1.2.66, @swc/cli: 0.1.62

**Comment by RnbWd** [comment]
same here

**Comment by nv6** [comment]
Incredible this is still an issue almost 3 years later

**Comment by kdy1** [comment]
Just because it’s not reproducible
