### ISSUE TITLE
SourceMapProxy::lookup_char_pos causes out of bounds memory access

### ISSUE THREAD

**Issue by kwonoj** [swc-project/swc#7238]
### Describe the bug

```
Caused by:
    0: failed to invoke `/home/git_repo/swc-coverage-instrument/target/wasm32-wasi/debug/swc_plugin_coverage.wasm` as js transform plugin at /home/git_repo/swc-coverage-instrument/target/wasm32-wasi/debug/swc_plugin_coverage.wasm
    1: RuntimeError: out of bounds memory access
           at rkyv::impls::core::primitive::_::<impl rkyv::Deserialize<u32,D> for u32>::deserialize::hf987dcd4d5a23f0f (<module>[17174]:0x5db044)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::BytePos,__D> for <swc_common::syntax_pos::BytePos as rkyv::Archive>::Archived>::deserialize::h5163a6ad2e68099f (<module>[15351]:0x54ac2b)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h76e0cc48824035e5 (<module>[15382]:0x54edcc)
           at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::h0fa332b260d140d0 (<module>[15121]:0x5378db)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::SourceFile,__D> for <swc_common::syntax_pos::SourceFile as rkyv::Archive>::Archived>::deserialize::hec4b05966557a119 (<module>[15354]:0x54c143)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::h2d776c7271413762 (<module>[15376]:0x54e631)
           at rkyv::de::SharedDeserializeRegistry::deserialize_shared::h300466f196606cc5 (<module>[15505]:0x55ef10)
           at rkyv::impls::alloc::rc::<impl rkyv::Deserialize<alloc::sync::Arc<T>,D> for rkyv::rc::ArchivedRc<<T as rkyv::ArchiveUnsized>::Archived,rkyv::impls::alloc::rc::ArcFlavor>>::deserialize::hf1e0d3210d8c554a (<module>[15266]:0x53e959)
           at rkyv::impls::core::option::<impl rkyv::Deserialize<core::option::Option<T>,D> for rkyv::option::ArchivedOption<<T as rkyv::Archive>::Archived>>::deserialize::h80d9a1718ba44314 (<module>[15265]:0x53e806)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::PartialLoc,__D> for <swc_common::syntax_pos::PartialLoc as rkyv::Archive>::Archived>::deserialize::h9301913a9cc51a47 (<module>[15353]:0x54b61a)
           at rkyv::util::from_bytes_unchecked::had57a043483f3d49 (<module>[15118]:0x537246)
           at swc_common::plugin::serialized::deserialize_from_ptr_into_fallible::h8a098d42fad0d1a3 (<module>[15415]:0x5578d6)
           at swc_plugin_proxy::memory_interop::read_returned_result_from_host::read_returned_result_from_host_fallible::h44c6572f8961a0f5 (<module>[15290]:0x546e26)
           at <swc_plugin_proxy::source_map::plugin_source_map_proxy::PluginSourceMapProxy as swc_common::errors::SourceMapper>::lookup_char_pos::h5c8986d68be38919 (<module>[15458]:0x559fa4)
           at swc_coverage_instrument::utils::lookup_range::get_range_from_span::h8ed700f54031791c (<module>[8352]:0x2c5242)
           at swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S>::create_stmt_increase_counter_expr::h5c67ab25644db914 (<module>[9571]:0x371f27)
           at swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S>::mark_prepend_stmt_counter::he63a39e2437af405 (<module>[9305]:0x33efa6)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_expr_stmt::hb731676e9217ffc2 (<module>[9320]:0x34b301)
           at swc_ecma_visit::visit_mut_stmt::hb954d5e69df8c163 (<module>[1657]:0xd0389)
           at swc_ecma_visit::VisitMut::visit_mut_stmt::hbde661e6e3a05786 (<module>[9402]:0x36d409)
           at swc_ecma_visit::visit_mut_module_item::hd35b66b661a84631 (<module>[2346]:0xe93b1)
           at <swc_ecma_ast::module::ModuleItem as swc_ecma_visit::VisitMutWith<V>>::visit_mut_children_with::hc28859ead0708ddc (<module>[8350]:0x2c5142)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_module_items::h2a3ad5c3e035b5ef (<module>[9367]:0x36570a)
           at swc_ecma_visit::visit_mut_module::h63a35a742db5514f (<module>[1799]:0xd581e)
           at swc_ecma_visit::VisitMut::visit_mut_module::hd66a286600ffdc14 (<module>[9411]:0x36d6b5)
           at swc_ecma_visit::visit_mut_program::h6232fc15a0263211 (<module>[1902]:0xd92da)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::VisitMutWith<V>>::visit_mut_children_with::h5efa94f711ebc180 (<module>[8349]:0x2c50f6)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_program::h3a1de69664758423 (<module>[9307]:0x341ada)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::VisitMutWith<V>>::visit_mut_with::hecc44617e977a2da (<module>[8348]:0x2c50aa)
           at <swc_ecma_visit::Folder<V> as swc_ecma_visit::Fold>::fold_program::h58c3af9f8cb6d60b (<module>[3176]:0x105da3)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::FoldWith<V>>::fold_with::ha1f23ad846ccf783 (<module>[8347]:0x2c505e)
           at swc_plugin_coverage::process::hcd587a0687530c45 (<module>[6394]:0x2776d5)
           at __transform_plugin_process_impl (<module>[6399]:0x2784d0)
           at __transform_plugin_process_impl.command_export (<module>[27584]:0x96462b)
    2: heap_get_oob', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.1/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("anon")'

Caused by:
    0: failed to invoke `/home/git_repo/swc-coverage-instrument/target/wasm32-wasi/debug/swc_plugin_coverage.wasm` as js transform plugin at /home/git_repo/swc-coverage-instrument/target/wasm32-wasi/debug/swc_plugin_coverage.wasm
    1: RuntimeError: out of bounds memory access
           at rkyv::impls::core::primitive::_::<impl rkyv::Deserialize<u32,D> for u32>::deserialize::hf987dcd4d5a23f0f (<module>[17174]:0x5db044)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::BytePos,__D> for <swc_common::syntax_pos::BytePos as rkyv::Archive>::Archived>::deserialize::h5163a6ad2e68099f (<module>[15351]:0x54ac2b)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<[U],D> for [T]>::deserialize_unsized::h76e0cc48824035e5 (<module>[15382]:0x54edcc)
           at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::h0fa332b260d140d0 (<module>[15121]:0x5378db)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::SourceFile,__D> for <swc_common::syntax_pos::SourceFile as rkyv::Archive>::Archived>::deserialize::hec4b05966557a119 (<module>[15354]:0x54c143)
           at rkyv::impls::core::<impl rkyv::DeserializeUnsized<T,D> for <T as rkyv::Archive>::Archived>::deserialize_unsized::h2d776c7271413762 (<module>[15376]:0x54e631)
           at rkyv::de::SharedDeserializeRegistry::deserialize_shared::h300466f196606cc5 (<module>[15505]:0x55ef10)
           at rkyv::impls::alloc::rc::<impl rkyv::Deserialize<alloc::sync::Arc<T>,D> for rkyv::rc::ArchivedRc<<T as rkyv::ArchiveUnsized>::Archived,rkyv::impls::alloc::rc::ArcFlavor>>::deserialize::hf1e0d3210d8c554a (<module>[15266]:0x53e959)
           at rkyv::impls::core::option::<impl rkyv::Deserialize<core::option::Option<T>,D> for rkyv::option::ArchivedOption<<T as rkyv::Archive>::Archived>>::deserialize::h80d9a1718ba44314 (<module>[15265]:0x53e806)
           at swc_common::syntax_pos::_::<impl rkyv::Deserialize<swc_common::syntax_pos::PartialLoc,__D> for <swc_common::syntax_pos::PartialLoc as rkyv::Archive>::Archived>::deserialize::h9301913a9cc51a47 (<module>[15353]:0x54b61a)
           at rkyv::util::from_bytes_unchecked::had57a043483f3d49 (<module>[15118]:0x537246)
           at swc_common::plugin::serialized::deserialize_from_ptr_into_fallible::h8a098d42fad0d1a3 (<module>[15415]:0x5578d6)
           at swc_plugin_proxy::memory_interop::read_returned_result_from_host::read_returned_result_from_host_fallible::h44c6572f8961a0f5 (<module>[15290]:0x546e26)
           at <swc_plugin_proxy::source_map::plugin_source_map_proxy::PluginSourceMapProxy as swc_common::errors::SourceMapper>::lookup_char_pos::h5c8986d68be38919 (<module>[15458]:0x559fa4)
           at swc_coverage_instrument::utils::lookup_range::get_range_from_span::h8ed700f54031791c (<module>[8352]:0x2c5242)
           at swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S>::create_stmt_increase_counter_expr::h5c67ab25644db914 (<module>[9571]:0x371f27)
           at swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S>::mark_prepend_stmt_counter::he63a39e2437af405 (<module>[9305]:0x33efa6)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_expr_stmt::hb731676e9217ffc2 (<module>[9320]:0x34b301)
           at swc_ecma_visit::visit_mut_stmt::hb954d5e69df8c163 (<module>[1657]:0xd0389)
           at swc_ecma_visit::VisitMut::visit_mut_stmt::hbde661e6e3a05786 (<module>[9402]:0x36d409)
           at swc_ecma_visit::visit_mut_module_item::hd35b66b661a84631 (<module>[2346]:0xe93b1)
           at <swc_ecma_ast::module::ModuleItem as swc_ecma_visit::VisitMutWith<V>>::visit_mut_children_with::hc28859ead0708ddc (<module>[8350]:0x2c5142)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_module_items::h2a3ad5c3e035b5ef (<module>[9367]:0x36570a)
           at swc_ecma_visit::visit_mut_module::h63a35a742db5514f (<module>[1799]:0xd581e)
           at swc_ecma_visit::VisitMut::visit_mut_module::hd66a286600ffdc14 (<module>[9411]:0x36d6b5)
           at swc_ecma_visit::visit_mut_program::h6232fc15a0263211 (<module>[1902]:0xd92da)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::VisitMutWith<V>>::visit_mut_children_with::h5efa94f711ebc180 (<module>[8349]:0x2c50f6)
           at <swc_coverage_instrument::visitors::coverage_visitor::CoverageVisitor<C,S> as swc_ecma_visit::VisitMut>::visit_mut_program::h3a1de69664758423 (<module>[9307]:0x341ada)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::VisitMutWith<V>>::visit_mut_with::hecc44617e977a2da (<module>[8348]:0x2c50aa)
           at <swc_ecma_visit::Folder<V> as swc_ecma_visit::Fold>::fold_program::h58c3af9f8cb6d60b (<module>[3176]:0x105da3)
           at <swc_ecma_ast::module::Program as swc_ecma_visit::FoldWith<V>>::fold_with::ha1f23ad846ccf783 (<module>[8347]:0x2c505e)
           at swc_plugin_coverage::process::hcd587a0687530c45 (<module>[6394]:0x2776d5)
           at __transform_plugin_process_impl (<module>[6399]:0x2784d0)
           at __transform_plugin_process_impl.command_export (<module>[27584]:0x96462b)
    2: heap_get_oob
    at Compiler.transformSync (/home/git_repo/swc-coverage-instrument/node_modules/@swc/core/index.js:241:29)
    at transformSync (/home/git_repo/swc-coverage-instrument/node_modules/@swc/core/index.js:348:21)
    at instrumentSync (/home/git_repo/swc-coverage-instrument/spec/util/verifier.ts:74:23)
    at Object.<anonymous> (/home/git_repo/swc-coverage-instrument/spec/fixture.spec.ts:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/git_repo/swc-coverage-instrument/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .ts] (/home/git_repo/swc-coverage-instrument/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/home/git_repo/swc-coverage-instrument/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
    at Object.exports.loadFilesAsync (/home/git_repo/swc-coverage-instrument/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at singleRun (/home/git_repo/swc-coverage-instrument/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/home/git_repo/swc-coverage-instrument/node_modules/mocha/lib/cli/run.js:370:5)
```

### Expected behavior

should not oob

### Version

latest

**Comment by kwonoj** [comment]
Note I could observe this only on aarch64 machines so far (m1 / aarch64 linux) but x86_64 passes. Possibly another case of https://github.com/swc-project/swc/issues/5406.

**Comment by kwonoj** [comment]
Actually this seems like https://github.com/swc-project/swc/issues/6852.

**Comment by kwonoj** [comment]
https://github.com/wasmerio/wasmer/issues/3764

**Comment by rnarkk** [comment]
Actually, I have been getting the same error on *x86_64* with rustc 1.70.0-nightly when building Next.js.

```sh
$ uname -a
```

```
Linux b3385b0e41fb 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 Linux
```

```sh
$ npm run build
```

```
...
info  - Creating an optimized production build ..thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/path/to/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/path/to/main.wasm` as js transform plugin at /path/to/main.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.255.23/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to disp
info  - Creating an optimized production build ...Segmentation fault
...
```

```sh
$ npx next info
```

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Sep 13 07:51:46 UTC 2022
Binaries:
  Node: 19.4.0
  npm: 9.6.4
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.3.0
  eslint-config-next: 13.3.0
  react: 18.2.0
  react-dom: 18.2.0
```

**Comment by kwonoj** [comment]
next.js issue is not relevant here since next.js is not using the corresponding swc_core yet.

**Comment by kwonoj** [comment]
Tentatively closing as we applied workaround.
