### ISSUE TITLE
`@swc/helpers` does not pass `npx es-check@7.0.1 es5`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#7264]
### Describe the bug

Due to the way we generate the common js index file, it's not a valid ES5, and it prevents me from updating `@swc/helpers` in `next.js` I guess.

```js
    /* @Annotate start: the CommonJS named exports for ESM import in node */
    _apply_decorated_descriptor: null,
    _array_like_to_array: null,
    _array_with_holes: null,
    _array_without_holes: null,
    _assert_this_initialized: null,


```

Note: This is a guess and I'm not sure if this is the actual cause. I need to investigate by creating a next.js app and look at the built files.

### Expected behavior

The test at https://github.com/vercel/next.js/blob/43519cf5868c6781f203c07c0b4794a9b6bd4c7e/test/production/escheck-output/index.test.ts#L27-L50 should pass

### Version

@swc/helpers@v0.5.0

**Comment by kdy1** [comment]
@magic-akari Are those properties required?

**Comment by kdy1** [comment]
I got

```
error: ES-Check: there were 1 ES version matching errors.
info:
          ES-Check Error:
          ----
          · erroring file: packages/swc-helpers/cjs/index.cjs
          · error: SyntaxError: Redefinition of property (104:8)
          · see the printed err.stack below for context
          ----

          SyntaxError: Redefinition of property (104:8)
    at Parser.pp$4.raise (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp$5.checkPropClash (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2414:16)
    at Parser.pp$5.parseObj (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:3086:30)
    at Parser.pp$5.parseExprAtom (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2820:19)
    at Parser.pp$5.parseExprSubscripts (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2636:21)
    at Parser.pp$5.parseMaybeUnary (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2602:19)
    at Parser.pp$5.parseExprOps (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2529:21)
    at Parser.pp$5.parseMaybeConditional (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2512:21)
    at Parser.pp$5.parseMaybeAssign (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2479:21)
    at Parser.pp$5.parseMaybeAssign (/Users/kdy1/.npm/_npx/1764c7d2441e918a/node_modules/acorn/dist/acorn.js:2497:25)

(base)
```

from

npx es-check@7.0.1 es5 'packages/swc-helpers/cjs/*.cjs'

**Comment by magic-akari** [comment]
> @magic-akari Are those properties required?

It's not required. 
ESM import is another entry.

However, for best compatibility, I have added it. 
I do not know if there are methods that I am not aware of that import the cjs entry from esm module.

Additionally, in fact, we do not use entry points in our @swc/core, and all imports are deep paths.

**Comment by magic-akari** [comment]
> Duplicate property names used to be considered a [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) in strict mode. With the introduction of [computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer), making duplication possible at runtime, this restriction was removed in ES2015.

[from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#:~:text=Copy%20to%20Clipboard-,Duplicate%20property%20names,-Duplicate%20property%20names)
