### ISSUE TITLE
`node_modules` can behave as partly not excluded

### ISSUE THREAD

**Issue by pp0rtal** [swc-project/swc#7325]
### Describe the bug

Even if I put `node_modules` in the `exclude` config list, it can behave inconsistently:
- It can make the compiler fail
- It can result to silent high resources consumption _([cf closed issues complex to reproduce](https://github.com/swc-project/swc/issues/7324))_

As I need to install packages, I can't give an example on the [playground](https://play.swc.rs/).However, I [hosted a minimal example](https://github.com/pp0rtal/swc-bug-node_modules-interfer) with every step to reproduce it in local.

### Input code

```typescript
./backend/node_modules/.bin/swc ./backend/ --out-dir ./backend_dist
```

### Config

```json
{
  "exclude": [
    "excluded_file",
    "node_modules"
  ]
}
```

### Playground link

https://github.com/pp0rtal/swc-bug-node_modules-interfer

### Expected behavior

Successfully compiled: 1 file with swc (63.37ms)

### Actual behavior

```
failed to load file

Caused by:
    stream did not contain valid UTF-8
failed to load file

Caused by:
    stream did not contain valid UTF-8
Successfully compiled: 1 file with swc (70.04ms)
Failed to compile 2 files with swc.
Error: Failed to compile:
backend/node_modules/map-or-similar/map-or-similar.min.gzip.js
backend/node_modules/memoizerific/memoizerific.min.gzip.js
    at initialCompilation (/swc-bug-node_modules-interfer/backend/node_modules/@swc/cli/lib/swc/dir.js:163:19)
    at async dir (/swc-bug-node_modules-interfer/backend/node_modules/@swc/cli/lib/swc/dir.js:228:5)
# exited with code 1
```

### Version

1.3.53

### Additional context

I chose `memoizerific` package to make swc fail, but it can happen with other packages.
Also, I noted that `node_modules` don't behave as excluded and impact significantly performances.  

**Interesting note:** If I remove `node_module` from the exclude list, I have way more errors. It demonstrates that swc ignores most of `node_modules` files, but not everything. The error is not my `.swcrc` exclude list config.

**Comment by lwagner-getmomo** [comment]
This is blocking for us as well. We have a dependency called `faker`. Importing `faker` straight up breaks `swc`. Even when excluding `node_modules`.
