### ISSUE TITLE
Cannot access 'XXX' before initialization[Reopen]

### ISSUE THREAD

**Issue by pashak09** [swc-project/swc#7371]
### Describe the bug

I know there is a cyclic dependency between classes (we can't clean up our codebase right now). But is it possible to do something in this case to fix the problem? I prepared a repository to reproduce and added an output file. 

https://github.com/pashak09/reproduce-bug-initialization

"@swc/core": "^1.3.57",
"@swc/register": "^0.1.10",
Node.js v18.16.0

### Input code

```typescript
import { Entity, OneToOne, PrimaryGeneratedColumn, ObjectType } from 'typeorm';
import { Employee } from '@app/employee/entities/Employee';

@Entity()
export class Doctor {
  @PrimaryGeneratedColumn()
  id: number = 0;

  @OneToOne(
    (): ObjectType<Employee> => Employee,
    (employee: Employee): Promise<Doctor> | Doctor => employee.doctor,
    {
      nullable: true,
      lazy: true,
    },
  )
  employee: Promise<Employee> | Employee;

  constructor(employee: Employee) {
    this.employee = employee;
  }
}

import { ObjectType, Field } from '@nestjs/graphql';
import {
  Column,
  Entity,
  OneToOne,
  ObjectType as TypeOrmObjectType,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Doctor } from '@app/employee/entities/Doctor';

@ObjectType()
@Entity()
export class Employee {
  @Field()
  @PrimaryGeneratedColumn()
  id: number = 0;

  @Field({ nullable: true })
  @Column({ type: 'varchar' })
  city: string = '';

  @OneToOne(
    (): TypeOrmObjectType<Doctor> => Doctor,
    (doctor: Doctor): Promise<Employee> | Employee => doctor.employee,
    {
      nullable: true,
      lazy: true,
    },
  )
  doctor: Promise<Doctor> | Doctor;

  constructor(doctor: Doctor) {
    this.doctor = doctor;
  }
}
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./"
  },
  "minify": false
}
```

### Expected behavior

Dependencies will be resolved correctly. There will be no error

### Actual behavior

```
$ NODE_ENV=test node -r @swc/register -r tsconfig-paths/register -r dotenv-flow/config tests/core/bootstrap.ts
/home/test/Downloads/reproduce-bug-initialization/src/employee/entities/Employee.ts:8
        return Employee;
        ^

ReferenceError: Cannot access 'Employee' before initialization
    at Object.get [as Employee] (/home/test/Downloads/reproduce-bug-initialization/src/employee/entities/Employee.ts:8:9)
    at Object.<anonymous> (/home/test/Downloads/reproduce-bug-initialization/src/employee/entities/Doctor.ts:19:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/home/test/Downloads/reproduce-bug-initialization/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .ts] (/home/test/Downloads/reproduce-bug-initialization/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)

Node.js v18.16.0
```

### Version

1.3.57

**Comment by kwonoj** [comment]
> I know there is a cyclic dependency between classes (we can't clean up our codebase right now)

Looks like you already know the root cause, even though it's something you can't fix right away. I can empathy the pain as I've been through similar but I do not expect swc core will apply specific workaround for some edge cases unless this behavior does not conform spec.

**Comment by kdy1** [comment]
SWC is correct here
