### ISSUE TITLE
Crash when sourcemap is empty

### ISSUE THREAD

**Issue by pierfale** [swc-project/swc#7454]
### Describe the bug

We use bazel and rules_swc to transpile our typescript.

If a file do not generate javascript (have only typescript definition) swc raise an error.

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/types.rs:655:
```

This bug was partially solved in #7229 but sourcemap is not generated at output:
```
output 'platform/test.js.map' was not create
```
Bug was reintroduced in #7307 

### Input code

```typescript
export interface Test {
  key: string;
}
```

### Config

```json
{
  "sourceMaps": true,
  "module": {
    "type": "commonjs",
    "strictMode": true,
    "noInterop": true
  },
  "jsc": {
    "externalHelpers": false,
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true,
      "react": {
        "throwIfNamespace": false,
        "useBuiltins": false,
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "importSource": "react"
      }
    },
    "keepClassNames": true
  }
}
```

### Expected behavior

An empty sourcemap is generated

### Actual behavior

Swc panic:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/types.rs:655:
```

### Version

1.3.60

### Additional context

Bazel use the following command:
```
external/swc_linux-x64-gnu/swc-linux-x64-gnu compile --source-maps true --source-file-name test.ts --config-file bazel-out/k8-fastbuild/bin/platform/.swcrc.build --out-file bazel-out/k8-fastbuild/bin/platform/test.js platform/test.ts
```

**Comment by kdy1** [comment]
Can you post the backtrace?
