### ISSUE TITLE
Unexpected change between 1.3.58 and 1.3.59

### ISSUE THREAD

**Issue by DaveTryon** [swc-project/swc#7506]
### Describe the bug

`@swc/core` has broken how it captures stack frames in the `stack` property of an `Error` object. We encountered this in https://github.com/microsoft/accessibility-insights-web/pull/6678, and I've placed a stripped down version at https://github.com/DaveTryon/accessibility-insights-web/tree/swe-core-demo. Copying from the README.md at that branch, 

In versions up to 1.3.58, the `stack` property of the `Error` object created in the `get-stack-trace` tests is as follows:

```
Error: 
    at getStackTrace (C:\\src\\common\\get-stack-trace.ts:10:22)
    at namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:12:34)
    at Object.namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:14:9)
    at Promise.then.completed (C:\\node_modules\\jest-circus\\build\\utils.js:293:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\\node_modules\\jest-circus\\build\\utils.js:226:10)
    at _callCircusTest (C:\\node_modules\\jest-circus\\build\\run.js:297:40)
    at _runTest (C:\\node_modules\\jest-circus\\build\\run.js:233:3)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:135:9)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:130:9)
    at run (C:\\node_modules\\jest-circus\\build\\run.js:68:3)
    at runAndTransformResultsToJestFormat (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)
    at jestAdapter (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)
    at runTestInternal (C:\\node_modules\\jest-runner\\build\\runTest.js:367:16)
    at runTest (C:\\node_modules\\jest-runner\\build\\runTest.js:444:34)
```

However, if you use `@swc/core` versions 1.3.59 or higher, the stack is reported as follows:
```
Error: 
    at getStackTrace (C:\\src\\common\\get-stack-trace.ts:5:22)
    at getStackTrace (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:9:21)
    at Object.namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:11:9)
    at Promise.then.completed (C:\\node_modules\\jest-circus\\build\\utils.js:293:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\\node_modules\\jest-circus\\build\\utils.js:226:10)
    at _callCircusTest (C:\\node_modules\\jest-circus\\build\\run.js:297:40)
    at _runTest (C:\\node_modules\\jest-circus\\build\\run.js:233:3)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:135:9)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:130:9)
    at run (C:\\node_modules\\jest-circus\\build\\run.js:68:3)
    at runAndTransformResultsToJestFormat (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)
    at jestAdapter (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)
    at runTestInternal (C:\\node_modules\\jest-runner\\build\\runTest.js:367:16)
    at runTest (C:\\node_modules\\jest-runner\\build\\runTest.js:444:34)
```

The _only_ difference between the 2 returned stacks is on the second stack frame:

Detail | up to 1.3.58 | 1.3.59 and beyond
--- | --- | ---
Reported function name | `namedCallingFunction` | `getStackTrace`
Reported location | `get-stack-trace.test.ts:12:34` | `get-stack-trace.test.ts:12:21`

### Input code

```typescript
Copied from https://github.com/DaveTryon/accessibility-insights-web/tree/swe-core-demo#repro-steps: 

Running the test is simple:
1. Clone the https://github.com/DaveTryon/accessibility-insights-web
2. Check out the swe-core-demo branch
2. Set the version of `@swc/core` in line 18 of `package.json`
2. `yarn install`
3. `yarn test`
```

### Config

```json
From https://github.com/DaveTryon/accessibility-insights-web/blob/swe-core-demo/.swcrc:

{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true
        }
    },
    "module": {
        "type": "commonjs"
    },
    "env": {},
    "sourceMaps": "inline"
}
```

### Playground link

The swc playground doesn't support the Errror type

### Expected behavior

Each stack frame should be correctly captured in the stack trace. This is the case in the old version, where each frame is correctly identified. Notice that it reports `namedCallingFunction` in the second stack frame:
```
Error: 
    at getStackTrace (C:\\src\\common\\get-stack-trace.ts:10:22)
    at namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:12:34)
    at Object.namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:14:9)
    at Promise.then.completed (C:\\node_modules\\jest-circus\\build\\utils.js:293:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\\node_modules\\jest-circus\\build\\utils.js:226:10)
    at _callCircusTest (C:\\node_modules\\jest-circus\\build\\run.js:297:40)
    at _runTest (C:\\node_modules\\jest-circus\\build\\run.js:233:3)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:135:9)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:130:9)
    at run (C:\\node_modules\\jest-circus\\build\\run.js:68:3)
    at runAndTransformResultsToJestFormat (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)
    at jestAdapter (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)
    at runTestInternal (C:\\node_modules\\jest-runner\\build\\runTest.js:367:16)
    at runTest (C:\\node_modules\\jest-runner\\build\\runTest.js:444:34)
```

### Actual behavior

The `namedCallingFunction` gets replaced by a duplicate of the `getStackTrace` function:
```
Error: 
    at getStackTrace (C:\\src\\common\\get-stack-trace.ts:5:22)
    at getStackTrace (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:9:21)
    at Object.namedCallingFunction (C:\\src\\tests\\unit\\tests\\common\\get-stack-trace.test.ts:11:9)
    at Promise.then.completed (C:\\node_modules\\jest-circus\\build\\utils.js:293:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\\node_modules\\jest-circus\\build\\utils.js:226:10)
    at _callCircusTest (C:\\node_modules\\jest-circus\\build\\run.js:297:40)
    at _runTest (C:\\node_modules\\jest-circus\\build\\run.js:233:3)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:135:9)
    at _runTestsForDescribeBlock (C:\\node_modules\\jest-circus\\build\\run.js:130:9)
    at run (C:\\node_modules\\jest-circus\\build\\run.js:68:3)
    at runAndTransformResultsToJestFormat (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)
    at jestAdapter (C:\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)
    at runTestInternal (C:\\node_modules\\jest-runner\\build\\runTest.js:367:16)
    at runTest (C:\\node_modules\\jest-runner\\build\\runTest.js:444:34)
```

### Version

Works with 1.3.58, breaks with 1.3.59

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/7309 is the cause, but I'm not sure about the fix.

**Comment by kdy1** [comment]
## Investigation

 - [Correct](https://evanw.github.io/source-map-visualization/#NTc0AC8vIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLiBBbGwgcmlnaHRzIHJlc2VydmVkLgovLyBMaWNlbnNlZCB1bmRlciB0aGUgTUlUIExpY2Vuc2UuCiJ1c2Ugc3RyaWN0IjsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgewogICAgdmFsdWU6IHRydWUKfSk7CmNvbnN0IF9nZXRzdGFja3RyYWNlID0gcmVxdWlyZSgiY29tbW9uL2dldC1zdGFjay10cmFjZSIpOwpkZXNjcmliZSgnZ2V0LXN0YWNrLXRyYWNlJywgKCk9PnsKICAgIGl0KCJzaG91bGQgaW5jbHVkZSB0aGUgY2FsbGluZyBmdW5jdGlvbidzIG5hbWUgaW4gdGhpcmQgbGluZSIsICgpPT57CiAgICAgICAgbGV0IHN0YWNrOwogICAgICAgIGZ1bmN0aW9uIG5hbWVkQ2FsbGluZ0Z1bmN0aW9uKCkgewogICAgICAgICAgICBzdGFjayA9ICgwLCBfZ2V0c3RhY2t0cmFjZS5nZXRTdGFja1RyYWNlKSgpOwogICAgICAgIH0KICAgICAgICBuYW1lZENhbGxpbmdGdW5jdGlvbigpOwogICAgICAgIGV4cGVjdChzdGFja1syXSkudG9Db250YWluKCduYW1lZENhbGxpbmdGdW5jdGlvbicpOwogICAgfSk7Cn0pOwo5NzEAewogICJtYXBwaW5ncyI6ICJBQUFBLDREQUE0RDtBQUM1RCxrQ0FBa0M7Ozs7OytCQUNKO0FBRTlCQSxTQUFTLG1CQUFtQixJQUFNO0lBQzlCQyxHQUFHLDREQUE0RCxJQUFNO1FBQ2pFLElBQUlDO1FBQ0osU0FBU0MsdUJBQXVCO1lBQzVCRCxRQUFRRSxJQUFBQSw0QkFBYTtRQUN6QjtRQUNBRDtRQUVBRSxPQUFPSCxLQUFLLENBQUMsRUFBRSxFQUFFSSxTQUFTLENBQUM7SUFDL0I7QUFDSiIsCiAgIm5hbWVzIjogWwogICAgImRlc2NyaWJlIiwKICAgICJpdCIsCiAgICAic3RhY2siLAogICAgIm5hbWVkQ2FsbGluZ0Z1bmN0aW9uIiwKICAgICJnZXRTdGFja1RyYWNlIiwKICAgICJleHBlY3QiLAogICAgInRvQ29udGFpbiIKICBdLAogICJzb3VyY2VzIjogWwogICAgIi4uLy4uL2lucHV0L2luZGV4LnRzIgogIF0sCiAgInNvdXJjZXNDb250ZW50IjogWwogICAgIi8vIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLiBBbGwgcmlnaHRzIHJlc2VydmVkLlxuLy8gTGljZW5zZWQgdW5kZXIgdGhlIE1JVCBMaWNlbnNlLlxuaW1wb3J0IHsgZ2V0U3RhY2tUcmFjZSB9IGZyb20gJ2NvbW1vbi9nZXQtc3RhY2stdHJhY2UnO1xuXG5kZXNjcmliZSgnZ2V0LXN0YWNrLXRyYWNlJywgKCkgPT4ge1xuICAgIGl0KFwic2hvdWxkIGluY2x1ZGUgdGhlIGNhbGxpbmcgZnVuY3Rpb24ncyBuYW1lIGluIHRoaXJkIGxpbmVcIiwgKCkgPT4ge1xuICAgICAgICBsZXQgc3RhY2s6IHN0cmluZ1tdIHwgdW5kZWZpbmVkO1xuICAgICAgICBmdW5jdGlvbiBuYW1lZENhbGxpbmdGdW5jdGlvbigpIHtcbiAgICAgICAgICAgIHN0YWNrID0gZ2V0U3RhY2tUcmFjZSgpO1xuICAgICAgICB9XG4gICAgICAgIG5hbWVkQ2FsbGluZ0Z1bmN0aW9uKCk7XG5cbiAgICAgICAgZXhwZWN0KHN0YWNrWzJdKS50b0NvbnRhaW4oJ25hbWVkQ2FsbGluZ0Z1bmN0aW9uJyk7XG4gICAgfSk7XG59KTsiCiAgXSwKICAidmVyc2lvbiI6IDMKfQo=)
- [Wrong](https://evanw.github.io/source-map-visualization/#NTc0AC8vIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLiBBbGwgcmlnaHRzIHJlc2VydmVkLgovLyBMaWNlbnNlZCB1bmRlciB0aGUgTUlUIExpY2Vuc2UuCiJ1c2Ugc3RyaWN0IjsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgewogICAgdmFsdWU6IHRydWUKfSk7CmNvbnN0IF9nZXRzdGFja3RyYWNlID0gcmVxdWlyZSgiY29tbW9uL2dldC1zdGFjay10cmFjZSIpOwpkZXNjcmliZSgnZ2V0LXN0YWNrLXRyYWNlJywgKCk9PnsKICAgIGl0KCJzaG91bGQgaW5jbHVkZSB0aGUgY2FsbGluZyBmdW5jdGlvbidzIG5hbWUgaW4gdGhpcmQgbGluZSIsICgpPT57CiAgICAgICAgbGV0IHN0YWNrOwogICAgICAgIGZ1bmN0aW9uIG5hbWVkQ2FsbGluZ0Z1bmN0aW9uKCkgewogICAgICAgICAgICBzdGFjayA9ICgwLCBfZ2V0c3RhY2t0cmFjZS5nZXRTdGFja1RyYWNlKSgpOwogICAgICAgIH0KICAgICAgICBuYW1lZENhbGxpbmdGdW5jdGlvbigpOwogICAgICAgIGV4cGVjdChzdGFja1syXSkudG9Db250YWluKCduYW1lZENhbGxpbmdGdW5jdGlvbicpOwogICAgfSk7Cn0pOwo5NDEAewogICJtYXBwaW5ncyI6ICJBQUFBLDREQUE0RDtBQUM1RCxrQ0FBa0M7Ozs7OytCQUNKO0FBRTlCQSxTQUFTLG1CQUFtQjtJQUN4QkMsR0FBRyw0REFBNEQ7UUFDM0QsSUFBSUM7UUFDSixTQUFTQztZQUNMRCxRQUFRRSxJQUFBQTtRQUNaO1FBQ0FEO1FBRUFFLE9BQU9ILEtBQUssQ0FBQyxFQUFFLEVBQUVJLFVBQVU7SUFDL0I7QUFDSiIsCiAgIm5hbWVzIjogWwogICAgImRlc2NyaWJlIiwKICAgICJpdCIsCiAgICAic3RhY2siLAogICAgIm5hbWVkQ2FsbGluZ0Z1bmN0aW9uIiwKICAgICJnZXRTdGFja1RyYWNlIiwKICAgICJleHBlY3QiLAogICAgInRvQ29udGFpbiIKICBdLAogICJzb3VyY2VzIjogWwogICAgIi4uLy4uL2lucHV0L2luZGV4LnRzIgogIF0sCiAgInNvdXJjZXNDb250ZW50IjogWwogICAgIi8vIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLiBBbGwgcmlnaHRzIHJlc2VydmVkLlxuLy8gTGljZW5zZWQgdW5kZXIgdGhlIE1JVCBMaWNlbnNlLlxuaW1wb3J0IHsgZ2V0U3RhY2tUcmFjZSB9IGZyb20gJ2NvbW1vbi9nZXQtc3RhY2stdHJhY2UnO1xuXG5kZXNjcmliZSgnZ2V0LXN0YWNrLXRyYWNlJywgKCkgPT4ge1xuICAgIGl0KFwic2hvdWxkIGluY2x1ZGUgdGhlIGNhbGxpbmcgZnVuY3Rpb24ncyBuYW1lIGluIHRoaXJkIGxpbmVcIiwgKCkgPT4ge1xuICAgICAgICBsZXQgc3RhY2s6IHN0cmluZ1tdIHwgdW5kZWZpbmVkO1xuICAgICAgICBmdW5jdGlvbiBuYW1lZENhbGxpbmdGdW5jdGlvbigpIHtcbiAgICAgICAgICAgIHN0YWNrID0gZ2V0U3RhY2tUcmFjZSgpO1xuICAgICAgICB9XG4gICAgICAgIG5hbWVkQ2FsbGluZ0Z1bmN0aW9uKCk7XG5cbiAgICAgICAgZXhwZWN0KHN0YWNrWzJdKS50b0NvbnRhaW4oJ25hbWVkQ2FsbGluZ0Z1bmN0aW9uJyk7XG4gICAgfSk7XG59KTsiCiAgXSwKICAidmVyc2lvbiI6IDMKfQo=)

**Comment by kdy1** [comment]
Seems like codegen PR is not the cause. I'm bisecting...

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://github.com/swc-project/swc/assets/29931815/5f750518-f193-4ca3-b331-1e9701e86f72">

Left: Working
Right: Regressed

**Comment by kdy1** [comment]
git bisect points a79a9cf6ffbc7a90a38b587b6e3b37764000235e

**Comment by kdy1** [comment]
Oops, I wasted an enormous amount of time because of caching...
