### ISSUE TITLE
why did require become require1

### ISSUE THREAD

**Issue by chenyulun** [swc-project/swc#779]
**Describe the bug**
core-js+asyncFunction+module.type=commonjs

**Input code**
`./src/testcorejs.js`
```javascript
import 'core-js'
async function a () {
  return 1;
}
a().then(console.log)
```
**Config**
```json
{
  "test": [".*.tsx$",".*.ts$", ".*.js$"],
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": {
      "chrome": "79",
      "ie": "11",
      "safari": "11.1"
    },
    "mode": "entry",
    "coreJs": 3
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2016",
    "loose": true,
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    }
  }
}
```

**Expected behavior**
```shell
node -r '@swc/register' ./src/index.js
➜  swctest node -r '@swc/register' ./src/index.js
/Users/chenyulun390/learn/swctest/src/index.js:2
require1('core-js/modules/es.typed-array.from');
^

ReferenceError: require1 is not defined
    at Object.<anonymous> (/Users/username/learn/swctest/src/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (/Users/username/learn/swctest/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.newLoader [as .js] (/Users/username/learn/swctest/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
➜  swctest 
```
```shell
swc ./src -d ./lib
```
`./lib/testcorejs.js`
```javascript
'use strict';
require1('core-js/modules/es.typed-array.from');
```

**Version**
The version of @swc/core: 
"@swc/cli": "^0.1.24",
    "@swc/core": "^1.1.43",
    "@swc/register": "^0.1.7",
**Additional context**
why did `require` become `require1`

**Comment by chenyulun** [comment]
The following code compiles normally
```javascript
import 'core-js'
const a = Promise.resolve('111')
a().then(console.log)
```
output
```javascript
require('core-js/modules/es.number.parse-int');
require('core-js/modules/es.string.starts-with');
require('core-js/modules/esnext.set.find');
var a = Promise.resolve('111');
a().then(console.log);
```
But `core-js+asyncFunction` reported an error

**Comment by kdy1** [comment]
It seems like a bug of env preset. I'll fix it soon.

**Comment by chenyulun** [comment]
#724 Is the issues the same problem?

**Comment by kdy1** [comment]
@chenyulun I don't think so. Although it's quite similar and I guess a similar change would fix the issue, it's a bit different.

**Comment by chenyulun** [comment]
@kdy1 
`npm info @swc/core`
output
`latest: 1.1.43`
update npm package to '1.1.44'?

**Comment by kdy1** [comment]
@chenyulun  Publised v1.1.44

**Comment by chenyulun** [comment]
@kdy1 
Update to 1.1.44, same configuration and command as yesterday, build 0 files without any error
```shell
➜  swctest tree -a -C --dirsfirst -L 3 -I 'node_modules|.git|.DS_Store'
.
├── lib
├── src
│   ├── index.js
│   ├── main.tsx
│   └── testcorejs.js
├── .browserslistrc
├── .swcrc
├── build.js
├── output.js
├── package-lock.json
└── package.json

2 directories, 9 files
➜  swctest yarn swc ./src -d ./lib                                     
yarn run v1.22.0
$ /Users/MyUserName/learn/swctest/node_modules/.bin/swc ./src -d ./lib
Successfully compiled 0 files with swc.
✨  Done in 0.97s.
➜  swctest 
```
`package.json`
```json
{
  "name": "swctest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "swc ./src -d ./lib"
  },
  "devDependencies": {},
  "dependencies": {
    "@swc/cli": "^0.1.24",
    "@swc/core": "^1.1.44",
    "@swc/register": "^0.1.7",
    "browserslist": "^4.9.1",
    "core-js": "^3.6.4",
    "react": "^16.13.1",
    "regenerator-runtime": "^0.13.5"
  }
}
```
`.swcrc`
```json
{
  "test": [".*.tsx$",".*.ts$", ".*.js$"],
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": {
      "chrome": "79"
    },
    "mode": "entry",
    "coreJs": 3
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2019",
    "loose": true,
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    }
  }
}
```

**Comment by kdy1** [comment]
I failed to reproduce it.

**Comment by chenyulun** [comment]
After removing all dependencies, it's ok to reinstall the dependencies, but the following code runs as if core-js won't parse it
```javascript
const swc = require("@swc/core");
const output = swc.transformSync(`
import 'core-js'
const a = Promise.resolve('111')
a().then(console.log)
`,
{
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": {
      "chrome": "79",
      "ie": "11",
      "safari": "11.1"
    },
    "mode": "entry",
    "coreJs": 3
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2019",
    "loose": true,
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    }
  }
}
)
console.log(output.code)
// 'use strict';
// require('core-js');
// const a = Promise.resolve('111');
// a().then(console.log);
```
Core-js parsing failed

**Comment by kdy1** [comment]
Oh.. I got it. Let's move to the new issue.
