### ISSUE TITLE
`using` keyword does not work for disposeAsync variant

### ISSUE THREAD

**Issue by ffMathy** [swc-project/swc#7902]
### Describe the bug

See https://github.com/swc-project/jest/issues/158.

This issue was closed prematurely, and then re-opened as https://github.com/swc-project/swc/issues/7879.

There, it was fixed, but not entirely. It only works when using `Symbol.dispose`, not `Symbol.disposeAsync` for async functions.

### Input code

```typescript
test("disposeAsync", async () => {
    class AsyncDisposableExample implements AsyncDisposable {
        async [Symbol.asyncDispose]() { }
    }

    await using asyncDisposable = new AsyncDisposableExample();
})
```

### Config

```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "exclude": [],
    "jsc": {
      "parser": {
        "syntax": "typescript",
        "decorators": true
      },
      "target": "esnext",
      "externalHelpers": false,
      "transform": {
        "decoratorMetadata": true
      }
    },
    "minify": false
  }
```

### Expected behavior

It works correctly.

### Actual behavior

> TypeError: Property [Symbol.dispose] is not a function

### Version

1.3.81

**Comment by kdy1** [comment]
This is not a bug of swc. `Symbol.asyncDispose` is used, but it's `undefined` in your case.

Look at the transpiled code.


https://play.swc.rs/?version=1.3.82&code=H4sIAAAAAAAAA0vOSSwuVnAsrsxLdsksLsgvTkzKSXWtSMwtyElVyASRual5JRgqFKq5FIAgESSqEB1cmZuUn6OXiFCTGquhqVCtUMtVy8WVWJ6YWaJQWpyZl66QiGaMrUJeajkO6zU0rbkAy8yv8p8AAAA%3D&config=H4sIAAAAAAAAA32QTQ6CMBCF95yCzNoFuDDGO3gGM6kDqba06RQiIdzd8lMEJW768973OunrkjSFBwu4pF04hotFx%2BSWe1C4rTy%2BggK%2BtcTCSevhEF3Pg1WgYhqlfnLAoyvJDyniY3bM5wQoY5hiYta0rGTRrmcKo60j5i04oFiVilboMMpYRQ2pbzhYTyJ7EwqZK9T081wkir%2BudbJBT2E3dg%2BSdN5RGQt0Ms827YR%2BkriOTYE293r1obHjqbUTfKBY0DIEJF9j0ruakv4NUVsYQMsBAAA%3D

**Comment by ffMathy** [comment]
But then how is this the stacktrace?

```
    TypeError: Property [Symbol.dispose] is not a function.



      at _using (src/domain/actions/FooAction.test.ts:57:15)
      at src/domain/actions/FooAction.test.ts:8:7
      at ../../../node_modules/.pnpm/p-limit@3.1.0/node_modules/p-limit/index.js:23:31
      at run (../../../node_modules/.pnpm/p-limit@3.1.0/node_modules/p-limit/index.js:23:43)
      at ../../../node_modules/.pnpm/p-limit@3.1.0/node_modules/p-limit/index.js:45:20
```

It's really weird. It happens in a Jest test with `@swc/jest`.

I do see that it seems it emits the right code, but doesn't look like it's working for me. Perhaps using external helpers will work?

**Comment by kdy1** [comment]
`Symbol.asyncDispose` is `undefined` in your environment, I guess.

**Comment by kdy1** [comment]
You should read the code. The `_using` helper uses `Property [Symbol.dispose] is not a function` as the error message even if `isAwait` is true and `Symbol.asyncDispose` is used for checking.

**Comment by ffMathy** [comment]
Yeah I agree. Just didn't understand why. Didn't know these symbols had to be polyfilled at runtime.
