### ISSUE TITLE
Vanilla React Native project doesn't work with @swc/jest based on usage instructions

### ISSUE THREAD

**Issue by jzaefferer** [swc-project/swc#8198]
### Describe the bug

When creating a vanilla React Native project, based on https://reactnative.dev/docs/environment-setup (run npx react-native@latest init AwesomeProjectSwc), then following the @swc/jest instructions for using swc with jest ( https://swc.rs/docs/usage/jest ), running yarn test will then fail with this unexpected error:

```
$ yarn test
yarn run v1.22.19
$ jest
 FAIL  __tests__/App.test.tsx
  ● Test suite failed to run


      × Expected ';', '}' or <eof>
        ╭─[~/AwesomeProjectSwc/node_modules/@react-native/js-polyfills/error-guard.js:11:1]
     11 │
     12 │ let _inGuard = 0;
     13 │
     14 │ type ErrorHandler = (error: mixed, isFatal: boolean) => void;
        · ──┬─ ────────────
        ·   ╰── This is the expression part of an expression statement
     15 │ type Fn<Args, Return> = (...Args) => Return;
     16 │
     17 │ /**
        ╰────


    Caused by:
        Syntax Error

      at Compiler.transformSync (node_modules/@swc/core/index.js:244:29)
      at transformSync (node_modules/@swc/core/index.js:351:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:726:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.074 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Playground link (or link to the minimal reproduction)

https://github.com/jzaefferer/swc-jest-react-native-repro

### SWC Info output

$ npx -y swc-info@latest

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Max

    Binaries:
        Node: 16.19.1
        npm: 8.19.3
        Yarn: 1.22.19
        pnpm: 8.10.0

    Relevant Packages:
        @swc/core: 1.3.95
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 4.8.4

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

Jest tests should run

### Version

"@swc/core": "^1.3.95",     "@swc/jest": "^0.2.29",

### Additional context

https://github.com/swc-project/jest/issues/40#issuecomment-980023466 looks somewhat related, but the suggested fix didn't work for me.

Looking for jest and this file name, which seems to be implemented in flow, I also found https://github.com/react-native-community/upgrade-support/issues/152 - but adding the suggested transformIgnorePatterns didn't help either.

**Comment by kdy1** [comment]
https://github.com/swc-project/jest/issues/85

It's not a bug of swc
