### ISSUE TITLE
`transform` exception exists in `inputSourceMap`

### ISSUE THREAD

**Issue by noyobo** [swc-project/swc#8545]
### Describe the bug

https://stackblitz.com/~/github.com/noyobo/swc-issues

```
~/noyobo/swc-issues main
❯ yarn install && npm run build
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

✨  Done in 4.10s.

> swc-issues@1.0.0 build
> RUST_BACKTRACE=full node ./build.mjs

panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/builder.rs:117:29:
index out of bounds: the len is 1779 but the index is 1779

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/noyobo/swc-issues/node_modules/@swc/core/wasm.js:578:17)
```

### Playground link (or link to the minimal reproduction)

https://stackblitz.com/~/github.com/noyobo/swc-issues

### Expected behavior

transform code to cjs 

### Actual behavior

```js
import { transform } from '@swc/core';
import fs from 'fs';
import path from 'path';

const __dirname = new URL('.', import.meta.url).pathname;

const code = fs.readFileSync(path.resolve(__dirname, './a.js'), 'utf-8');
const map = fs.readFileSync(path.resolve(__dirname, './a.js.map'), 'utf-8');

const cjs = await transform(code, {
  filename: 'a.js',
  sourceMaps: true,
  inputSourceMap: map,
  jsc: { target: 'es5' },
  module: { type: 'commonjs', strictMode: false },
}).catch((e) => {
  console.error('[esm2cjs]', e);
});
```

```
panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sourcemap-6.2.3/src/builder.rs:117:29:
index out of bounds: the len is 1779 but the index is 1779

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/noyobo/swc-issues/node_modules/@swc/core/wasm.js:578:17)
```

_No response_

### Version

1.3.105

**Comment by kdy1** [comment]
This is fixed. 
![Uploading image.png…]()
