### ISSUE TITLE
Error: Cannot find module './binding.js'

### ISSUE THREAD

**Issue by xqin** [swc-project/swc#8995]
### Describe the bug

`@swc/core@1.5.19`  && `@swc/core@1.5.20`  install error.

```
$ npm i @swc/core@1.5.20
npm ERR! code 1
npm ERR! path /root/node_modules/@swc/core
npm ERR! command failed
npm ERR! command sh -c -- node postinstall.js
npm ERR! Error: Cannot find module './binding.js'
npm ERR! Require stack:
npm ERR! - /root/node_modules/@swc/core/postinstall.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at /root/node_modules/@swc/core/postinstall.js:136:23
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at /root/node_modules/@swc/core/postinstall.js:85:74
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at __awaiter (/root/node_modules/@swc/core/postinstall.js:64:16)
npm ERR!     at validateBinary (/root/node_modules/@swc/core/postinstall.js:119:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/root/node_modules/@swc/core/postinstall.js' ]
npm ERR! }
npm ERR! @swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
npm ERR! node:internal/modules/cjs/loader:400
npm ERR!       const err = new Error(
npm ERR!                   ^
npm ERR!
npm ERR! Error: Cannot find module '/root/node_modules/@swc/core/src/index.js'. Please verify that the package.json has a valid "main" entry
npm ERR!     at tryPackage (node:internal/modules/cjs/loader:400:19)
npm ERR!     at Module._findPath (node:internal/modules/cjs/loader:613:18)
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
npm ERR!     at /root/node_modules/@swc/core/postinstall.js:184:34
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at /root/node_modules/@swc/core/postinstall.js:85:74
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at __awaiter (/root/node_modules/@swc/core/postinstall.js:64:16)
npm ERR!     at validateBinary (/root/node_modules/@swc/core/postinstall.js:119:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: '/root/node_modules/@swc/core/package.json',
npm ERR!   requestPath: '@swc/core'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-05-29T07_04_11_341Z-debug-0.log
```

### Input code

```typescript
npm i @swc/core@1.5.20

npm i @swc/core@1.5.19
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/

### Expected behavior

install without error.

### Version

1.5.19 && 1.5.20

**Comment by xqin** [comment]
This file `binding.js` does not exist in the package.

```
➜  ~ curl -s https://registry.npmjs.org/@swc/core/-/core-1.5.20.tgz | tar -t
package/package.json
package/postinstall.js
package/scripts/npm/darwin-arm64/README.md
package/scripts/npm/darwin-arm64/package.json
package/scripts/npm/darwin-x64/README.md
package/scripts/npm/darwin-x64/package.json
package/scripts/npm/linux-arm-gnueabihf/README.md
package/scripts/npm/linux-arm-gnueabihf/package.json
package/scripts/npm/linux-arm64-gnu/README.md
package/scripts/npm/linux-arm64-gnu/package.json
package/scripts/npm/linux-arm64-musl/README.md
package/scripts/npm/linux-arm64-musl/package.json
package/scripts/npm/linux-x64-gnu/README.md
package/scripts/npm/linux-x64-gnu/package.json
package/scripts/npm/linux-x64-musl/README.md
package/scripts/npm/linux-x64-musl/package.json
package/scripts/npm/win32-arm64-msvc/README.md
package/scripts/npm/win32-arm64-msvc/package.json
package/scripts/npm/win32-ia32-msvc/README.md
package/scripts/npm/win32-ia32-msvc/package.json
package/scripts/npm/win32-x64-msvc/README.md
package/scripts/npm/win32-x64-msvc/package.json
➜  ~
➜  ~
➜  ~ curl -s https://registry.npmjs.org/@swc/core/-/core-1.5.19.tgz | tar -t
package/package.json
package/scripts/npm/darwin-arm64/README.md
package/scripts/npm/darwin-arm64/package.json
package/scripts/npm/darwin-x64/README.md
package/scripts/npm/darwin-x64/package.json
package/scripts/npm/linux-arm-gnueabihf/README.md
package/scripts/npm/linux-arm-gnueabihf/package.json
package/scripts/npm/linux-arm64-gnu/README.md
package/scripts/npm/linux-arm64-gnu/package.json
package/scripts/npm/linux-arm64-musl/README.md
package/scripts/npm/linux-arm64-musl/package.json
package/scripts/npm/linux-x64-gnu/README.md
package/scripts/npm/linux-x64-gnu/package.json
package/scripts/npm/linux-x64-musl/README.md
package/scripts/npm/linux-x64-musl/package.json
package/scripts/npm/win32-arm64-msvc/README.md
package/scripts/npm/win32-arm64-msvc/package.json
package/scripts/npm/win32-ia32-msvc/README.md
package/scripts/npm/win32-ia32-msvc/package.json
package/scripts/npm/win32-x64-msvc/README.md
package/scripts/npm/win32-x64-msvc/package.json

```

**Comment by kdy1** [comment]
See the pinned issue

**Comment by xqin** [comment]
@kdy1 I reported that a specific version could not be installed, not an installation problem with `npm i @swc/core`.

**Comment by kdy1** [comment]
I'm aware of it and I already did dist-tag for it.
