### ISSUE TITLE
Cannot find module './binding.js' - v1.5.20

### ISSUE THREAD

**Issue by valentinpalkovic** [swc-project/swc#8996]
### Describe the bug

While installing the latest stable version of `@swc/core`, I'll get the following error:

```
# This file contains the result of Yarn building a package (@swc/core@virtual:d1d3fe94c2114b57b7e60cb512bfb2dd6cf8c51f5af1a478afbe943b681fac8c29ecdf49e4de5fd8541089ffa17e73f459962f52c3a73dd8c376caf1c29323bf#npm:1.5.20)
# Script name: postinstall

Error: Cannot find module './binding.js'
Require stack:
- <sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at <sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:136:23
    at Generator.next (<anonymous>)
    at <sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:85:74
    at new Promise (<anonymous>)
    at __awaiter (<sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:64:16)
    at validateBinary (<sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:119:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js'
  ]
}
@swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
node:internal/modules/cjs/loader:437
      const err = new Error(
                  ^

Error: Cannot find module '<sanitized>/storybook-next/scripts/node_modules/@swc/core/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at <sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:184:34
    at Generator.next (<anonymous>)
    at <sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:85:74
    at new Promise (<anonymous>)
    at __awaiter (<sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:64:16)
    at validateBinary (<sanitized>/storybook-next/scripts/node_modules/@swc/core/postinstall.js:119:5) {
  code: 'MODULE_NOT_FOUND',
  path: '<sanitized>/storybook-next/scripts/node_modules/@swc/core/package.json',
  requestPath: '@swc/core'
}

Node.js v18.19.1

```

### Playground link (or link to the minimal reproduction)

https://github.com/valentinpalkovic/yarn-v4-swc-repo/tree/main

### SWC Info output

Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
        CPU: (10 cores)
            Models: Apple M1 Pro

    Binaries:
        Node: 18.19.1
        npm: 10.2.4
        Yarn: 4.1.1
        pnpm: N/A

    Relevant Packages:
        @swc/core: 1.5.20
        @swc/helpers: N/A
        @swc/types: 0.1.7
        typescript: 5.4.5

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

I can install the latest published stable version of `@swc/core` without issues

### Version

1.5.20

**Comment by kdy1** [comment]
Can you try installing `@swc/core@nightly`?

**Comment by valentinpalkovic** [comment]
I've tried nightly (@swc/core@npm:1.5.21-nightly-20240529.1), but I get the following error message:

```
# This file contains the result of Yarn building a package (@swc/core@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:1.5.21-nightly-20240529.1)
# Script name: postinstall

Error: Failed to load native binding
    at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:339:15)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at require$$0.Module._extensions..js (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5683:33)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at require$$0.Module._load (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5531:31)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:136:23 {
  [cause]: [
    Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
    
    Source path: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-universal.node
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-universal.node
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-universal.node.js
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-universal.node.json
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-universal.node.node
    
    Require stack:
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js
        at require$$0.Module._resolveFilename (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640:13)
        at Module._load (node:internal/modules/cjs/loader:975:27)
        at require$$0.Module._load (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5531:31)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at requireNative (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:136:20)
        at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:312:17)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at require$$0.Module._extensions..js (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5683:33),
    Error: @swc/core tried to access @swc/core-darwin-universal, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
    
    Required package: @swc/core-darwin-universal
    Required by: @swc/core@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:1.5.21-nightly-20240529.1 (via /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/)
    
    Require stack:
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js
        at require$$0.Module._resolveFilename (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640:13)
        at Module._load (node:internal/modules/cjs/loader:975:27)
        at require$$0.Module._load (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5531:31)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at requireNative (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:141:20)
        at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:312:17)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at require$$0.Module._extensions..js (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5683:33),
    Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.
    
    Source path: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-arm64.node
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-arm64.node
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-arm64.node.js
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-arm64.node.json
    Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/swc.darwin-arm64.node.node
    
    Require stack:
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js
        at require$$0.Module._resolveFilename (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640:13)
        at Module._load (node:internal/modules/cjs/loader:975:27)
        at require$$0.Module._load (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5531:31)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at requireNative (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:159:24)
        at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:312:17)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at require$$0.Module._extensions..js (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5683:33),
    Error: @swc/core tried to access @swc/core-darwin-arm64, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
    
    Required package: @swc/core-darwin-arm64
    Required by: @swc/core@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:1.5.21-nightly-20240529.1 (via /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/)
    
    Require stack:
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js
    - /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js
        at require$$0.Module._resolveFilename (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640:13)
        at Module._load (node:internal/modules/cjs/loader:975:27)
        at require$$0.Module._load (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5531:31)
        at Module.require (node:internal/modules/cjs/loader:1225:19)
        at require (node:internal/modules/helpers:177:18)
        at requireNative (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:164:24)
        at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/binding.js:312:17)
        at Module._compile (node:internal/modules/cjs/loader:1356:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
        at require$$0.Module._extensions..js (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5683:33)
  ]
}
@swc/core was not able to resolve native bindings installation. It'll try to use @swc/wasm as fallback instead.
/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640
      Error.captureStackTrace(firstError);
            ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/src/index.js
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/src/index.js.js
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/src/index.js.json
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/src/index.js.node
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/.js
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/.json
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/.node
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/index.js
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/index.json
Not found: /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/index.node

Require stack:
- /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js
    at require$$0.Module._resolveFilename (/Users/valentinpalkovic/Projects/yarn-4-swc/.pnp.cjs:5640:13)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:184:34
    at Generator.next (<anonymous>)
    at /Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:85:74
    at new Promise (<anonymous>)
    at __awaiter (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:64:16)
    at validateBinary (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:119:5)
    at Object.<anonymous> (/Users/valentinpalkovic/Projects/yarn-4-swc/.yarn/unplugged/@swc-core-virtual-fe538b6c29/node_modules/@swc/core/postinstall.js:224:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)

Node.js v18.19.1
```

**Comment by pladaria** [comment]
I was getting this issue using vite. Installing the package as dev dependency doesn't solves the issue because then you end with two swc packages.

```
$ yarn why @swc/core
├─ @vitejs/plugin-react-swc@npm:3.7.0
│  └─ @swc/core@npm:1.5.20 (via npm:^1.5.7)
│
├─ @vitejs/plugin-react-swc@npm:3.7.0 [3dc46]
│  └─ @swc/core@npm:1.5.20 [9ce60] (via npm:^1.5.7 [9ce60])
│
└─ mistica-example-vite@workspace:.
   └─ @swc/core@npm:1.5.21-nightly-20240529.1 [3dc46] (via npm:^1.5.21-nightly-20240529.1 [3dc46])
```

To workaround this, using the `"resolutions"` property in the package json and forcing the version to `1.5.7` (without the `^`), it seems to work as expected:

```json
   ...
    "resolutions": {
        "@swc/core": "1.5.7"
    }
   ...
```

after that:
```txt
$ yarn
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 275ms
```

**Comment by xqin** [comment]
https://github.com/swc-project/swc/issues/8995

**Comment by magic-akari** [comment]
It seems that yarn indeed does not comply with dist-tag.



```
❯ pnpm add @vitejs/plugin-react-swc
Packages: +16
++++++++++++++++
Progress: resolved 62, reused 16, downloaded 0, added 16, done
node_modules/.pnpm/@swc+core@1.5.7/node_modules/@swc/core: Running postinstall script, done in 190ms
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 258ms

dependencies:
+ @vitejs/plugin-react-swc 3.7.0

Done in 3.5s
```

```
❯ yarn add  @vitejs/plugin-react-swc   
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @vitejs/plugin-react-swc@npm:3.7.0, @swc/core@npm:1.5.20, @swc/counter@npm:0.1.3, @swc/types@npm:0.1.7
➤ YN0000: └ Completed in 0s 355ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ test-esm@workspace:. doesn't provide vite (pcf7af), requested by @vitejs/plugin-react-swc.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @swc/core@npm:1.5.20 [3c90d] must be built because it never has been before or the last one failed
➤ YN0009: │ @swc/core@npm:1.5.20 [3c90d] couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/sp/db958__94k5gkq2vpm3jrgp00000gn/T/xfs-a844ca37/build.log)
➤ YN0000: └ Completed in 0s 349ms
➤ YN0000: · Failed with errors in 0s 718ms
```

Additionally, I have tested npm as well, which does not print the specific version of the installation, but the installation result is correct.

**Comment by mcdurdin** [comment]
We use ts-node which has a peer dependency on swc/@core in @keymanapp/keyman (npm, not yarn) and experienced this issue too: https://github.com/keymanapp/keyman/issues/11609

It seems to have been resolved (without reference to this issue) in 4c0b2e81d92e317b2c7931b3098e608eae61f207?

**Comment by kdy1** [comment]
Does this still haplen with a new version?

**Comment by mcdurdin** [comment]
Which version in particular?

**Comment by kdy1** [comment]
Finally it's fixed.
