### ISSUE TITLE
panic: decorator cause panic in parser

### ISSUE THREAD

**Issue by bartlomieju** [swc-project/swc#913]
**NOTE** This was working properly with
```
swc_ecma_ast =0.23.1
swc_ecma_parser =0.27.0
```

But panics using
```
swc_ecma_ast =0.26.0
swc_ecma_parser =0.31.0
```

Parser code:
https://github.com/denoland/deno_lint/blob/c3a51caa9ec6e8086c81cbfec780a3c3ca0cba64/src/swc_util.rs#L153-L189

Syntax config:
https://github.com/denoland/deno_lint/blob/c3a51caa9ec6e8086c81cbfec780a3c3ca0cba64/src/swc_util.rs#L51-L57

Source code causing crash: 
https://github.com/drashland/deno-drash/blob/master/tests/unit/decorators/middleware_test.ts

Backtrace
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `BytePos(6764)`,
 right: `BytePos(6763)`', /Users/rossi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   1: core::fmt::write
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   2: std::io::Write::write_fmt
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   3: std::panicking::default_hook::{{closure}}
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   4: std::panicking::default_hook
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   5: std::panicking::rust_panic_with_hook
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   6: rust_begin_unwind
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
   7: std::panicking::begin_panic_fmt
             at src/libcore/../stdarch/crates/core_arch/src/macros.rs:403
   8: swc_ecma_parser::parser::class_and_fn::<impl swc_ecma_parser::parser::Parser<I>>::parse_decorator
             at /Users/rossi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16
   9: swc_ecma_parser::parser::class_and_fn::<impl swc_ecma_parser::parser::Parser<I>>::parse_decorators
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.31.0/src/parser/class_and_fn.rs:193
  10: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_stmt_like
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.31.0/src/parser/stmt.rs:79
  11: swc_ecma_parser::parser::stmt::<impl swc_ecma_parser::parser::Parser<I>>::parse_block_body
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.31.0/src/parser/stmt.rs:29
  12: swc_ecma_parser::parser::Parser<I>::parse_module
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.31.0/src/parser/mod.rs:135
  13: deno_lint::swc_util::AstParser::parse_module::{{closure}}
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.19/src/swc_util.rs:181
  14: scoped_tls::ScopedKey<T>::set
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  15: deno_lint::swc_util::AstParser::parse_module
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.19/src/swc_util.rs:163
  16: deno_lint::linter::Linter::lint
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.19/src/linter.rs:222
  17: sauron::linter::lint_file
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:1122
  18: <sauron::linter::Linter as sauron::check::Check>::check_file
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:1122
  19: sauron::main
             at src/main.rs:74
  20: std::rt::lang_start::{{closure}}
             at /Users/rossi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  21: std::rt::lang_start_internal
             at /Users/rossi/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.13/src/packed/teddy/runtime.rs:1019
  22: std::rt::lang_start
             at /Users/rossi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23: main
```

**Comment by kdy1** [comment]
Fixed it
